### PR TITLE
Eliminate factory mocks for catalogItemProduct

### PR DESCRIPTION
**Pull request by trojanh**
Resolves https://github.com/reactioncommerce/reaction/issues/4284
Impact: **minor**  
Type: **test|chore**

## Issue
Use Factory mocks for Catalog integration and removes `tests/mocks`

## Testing
1. Make sure tests pass

### CODE REVIEW

**Comment by willopez** [comment]
@trojanh one of your commits is not signed off, please follow instructions here: https://github.com/reactioncommerce/reaction/pull/5892/checks?check_run_id=343813454

**Comment by willopez** [comment]
@trojanh the DCO check is still failing, this is the specific commit that is missing the sign off: https://github.com/reactioncommerce/reaction/pull/5892/commits/7b162ca858d20447abab6afa28f6b4393fdb2c75

**Comment by trojanh** [comment]
I have fixed that commit @willopez , thanks for helping me with this.

**Comment by trojanh** [comment]
@willopez I have updated the test cases to use Factory mocks but one test is failing as offset doesn't seem to be working as expected i.e no matter what offset value I use it returns the same number of items, so next and previous pages are not present as expected earlier.

You can check the test case [here](https://github.com/trojanh/reaction/blob/eliminate-factory-mocks/tests/integration/api/queries/catalogItems/catalogItems.test.js#L208) 

Let me know if this should be behaving like this or do I need to update my code somewhere.

**Comment by willopez** [comment]
@trojanh Let's revert the updates you made to the `catalogItems.test.js` for the featured sort test case. That particular query will be re-written soon, and the existing test case will work for now. This will allow us to move forward with this PR.

**Comment by trojanh** [comment]
@willopez are you suggesting I keep using the mock folder for that particular test case, while we update the query to fix the underlying issue? 

If you can confirm there's an issue with the `catalogItems` for featured products query, I could fix that along with this test case. 

If this PR needs to be shipped without the fix, maybe I can comment or skip that particular test case with an explanation and we do it in another PR. 

Let me know your thoughts because the original intention of this PR was to eliminate mocks folder.

**Comment by willopez** [comment]
@trojanh Let's break the `catalogItems` test case into its own PR and move forward with the rest in this PR. There is no bug AFAK with the sort by featured query, what I meant is that it will be re-written to be more performant in the future. So, the test is failing due to the use of the new mock factories, just not sure what is causing the issue. So, if you can debug and find out why that is, that would be great.

**Comment by trojanh** [comment]
@willopez done, will create another PR for `catalogItems` tests and debug the issue. Thanks

**Pull request merged**
