### PR TITLE
Script reorg and CLI updates

### PR DESCRIPTION
**Pull request by jshimko**
- Moves all bash and Docker scripts to new `.reaction` directory.  This consolidates/removes the `bin` and `docker` directories that were in the root of the app.
- Adds a deprecation warning to the old `reaction` command script with info about `reaction-cli`.

### CODE REVIEW

**Comment by zenweasel** [comment]
Approved. Tested and it seems to be working for me.

**Comment by aaronjudd** [comment]
Testing on several docker ubuntu-node images, `reaction init` fails to work.

```
npm install -g reaction-cli
reaction init
  Options:
    -v, --version  Show version number                                   [boolean]
    -h, --help     Show help                                             [boolean]

Cannot read property 'warn' of undefined
# reaction -v
Reaction CLI: 0.3.2

# npm -v
3.6.0
# node -v
v5.6.0
```

occurs with all versions that I was able to try

```
npm info ok
# reaction init
Options:
  -v, --version  Show version number                                   [boolean]
  -h, --help     Show help                                             [boolean]

Cannot read property 'warn' of undefined
# npm -v
3.9.5
# node -v
v6.2.2
#
```

**Comment by aaronjudd** [comment]
On OS X I am now seeing:

```

Reaction successfully installed!

To start your new app, just run:

reaction init

Options:
  -v, --version  Show version number                                   [boolean]
  -h, --help     Show help                                             [boolean]
  -b, --branch   The branch to clone from Github [default: master]
                                                             [default: "master"]

Cannot read property 'bold' of undefined
```

**Comment by jshimko** [comment]
The `reaction init` issues [should be fixed](https://github.com/reactioncommerce/reaction-cli/commit/5c2308cf32d4ab646c3c789e7f33539bd05dee50) in reaction-cli v0.3.3.

**Comment by aaronjudd** [comment]
👍  pulling in, with caveat that I still see issues while testing using `node:latest` but most other cases are working.

**Comment by Tzelon** [comment]
Hey,
I have those versions , but I still getting 
$ reaction init
Cannot read property 'warn' of undefined

$ reaction -v
Reaction: 0.14.0
Reaction CLI: 0.3.7

$ node -v
v6.3.0

**Comment by aaronjudd** [comment]
Created https://github.com/reactioncommerce/reaction-cli/issues/3 to track the "warn" error.

**Pull request merged**
