### PR TITLE
(feat) CSV data imports and exports

### PR DESCRIPTION
**Pull request by ajporlante**
Impact: **major**
Type: **feature**

## Description
    
This is a plugin to allow shop administrator to import and export data into Reaction from/into a CSV file. For this PR, 2 data types are supported for imports and exports: Products and Tags.
    
There are three ways to import data with a CSV file.
    
Manual - admin will upload the file through the Reaction dashboard
AWS S3 - the file will be fetched from an S3 bucket
SFTP - the file will be fetched from an SFTP server
    
Similarly, there are three ways by which you can export data into a CSV file:
    
Manual - you will download the file from your Reaction dashboard
AWS S3 - the file will be sent to an AWS S3 bucket
SFTP - the file will be sent to an SFTP server
    
The plugin also has the feature of being able to save a mapping template, a mapping between CSV columns and Reaction schema, so that an administrator can reuse the mapping.
    
Also, the plugin has the feature to reuse a job which loads the file source/destination, data type, and mapping template of the previous job.

## Testing
    
**A. SFTP and S3 configuration**
    
1. Go to the dashboard CSV connector panel and click the settings icon at the upper right corner of the icon.
2. Enter invalid SFTP credentials and click "Save changes." Click "Test for import and export". An error alert should be displayed.
3. Enter valid SFTP credentials and click "Save Changes". Click "Test for import and export". A success alert should be displayed.
4. Do steps 2 and 3 for AWS credentials.

**B. Tags Inserts Import**
    
1. From the main CSV connector panel, check "Import." Click "Next."
2. Select "New job", "Manual" for file source, "Tags" for data type, "Create new mapping" for mapping template. Enter a job name. Upload a CSV file for tags (below is a sample CSV file). Check "First row has column names". Click "Next."
```
"Name","Slug","ParentTagSlug"
"Cat-1","",""
"Cat-2","cat-2",""
"","",""
"Cat-2-1","cat-2-1","cat-2"
"Cat-2-2","cat-2-2","cat-2"
"Cat-2-1-1","","cat-2-1"
"Cat-3-1","","cat-3"
```
3. Now, map Name to Name, Slug to Slug, and ParentTagSlug to Parent Tag Slug.
4. Click "Save to a new mapping template." and enter a new mapping template.
5. Click "Done."
6. You will be back in the main screen and the job you just created will be in job queue table.
7. Wait for a minute, the tags from the imported file should be saved and the status of the job should be completed and there should be a link which you can click to download errors.
8. Download the errors file and see that the error messages are accurate in the corresponding column numbers are correct.

**C. Tags Export**
1. From the main CSV connector panel, check "Export." Click "Next."
2. Select Tags for data type, Default Mapping Template for mapping template, and enter a job name.
3. Click Done.
4. Wait for the job to be completed and download the CSV file export in the job queue. Verify that fields and field values are correctly shown in the file.

**D. Tags Updates Import**
1. Create a new CSV file based on the exports file from C. In the new file, keep the IDs column, and change some attributes of some tags like name, slug, visibility, and parent. Feel free to enter invalid values, like a parent tag that does not exist.
2. In the CSV connector panel, check "Import", click "Next."
3. In the details screen, click "Manual", upload the CSV file you created, select Tags for data type, "Create new template" for mapping template, enter a job name, and check "First row has column names." Click "Next."
4. In the mapping screen, map the fields accordingly. Do not forget to map the ID column to ID. Click "Save to a new mapping template." and enter a new mapping template. Then click "Done."
5. Wait for the job to be completed and verify that the updates in the uploaded file were processed. Download the errors file and verify that the error messages are correct.

**E. Products Inserts Import**
Repeat the process in Tags Inserts Import above, but this time, select "Products" as data type. Below is a sample CSV file content:
```
"Title","Option title","Parent title","Description","Slug","Vendor","Origin Country","Tag Slugs","Metafields","Is Visible","Height","Width","Width","Weight","Price","Compares at price","Taxable","Tax Code","Images","Track inventory?","Allow backorder?","Quantity","Quantity","Fulfillment types"
"Option 2 - Green Tomato","Green","Basic Example Variant 2","","","","","","","1","3","10","10","25","12.99","","1","0","","1","1","42","10","shipping"
"Basic Example Variant 2","","Basic Reaction Product 2","","","","AS","","","1","0","0","0","35","19.99","","1","0","http://placekitten.com/200/300 || https://placekitten.com/200/138","1","1","15","10","shipping"
"Option 1 - Red Dwarf","Red","Basic Example Variant 2","","","","","","","1","3","10","10","25","19.99","","1","0","","1","1","19","10","shipping"
"Basic Reaction Product 2","","","Sign in as administrator to edit.
You can clone this product from the product grid.
You can upload images click or drag in image box on the left here.
Tag this product below, and then add tag in navigation.
Click the bookmark in the tag to set product url.
Option variants, price, quantity, and child variants are created by clicking on the variant below, clone the variant to add more options.
Details can be added below the image for more specific product information.
 Login next to the cart, and then click the dashboard icon for more tools.","","Example Manufacturer","","example-product || shop","Material : Cotton || Quality : Excellent","1","","","","","","","","","","","","","","shipping"
```

**F. Products Export**
Repeat steps in Tags Export but select "Products" as data type.

**G. Products Updates Import**
From the exports file, create a CSV file for product updates. Repeat the same steps as in Tags Updates Import.

**H. S3 and SFTP Imports**
1. Create a new import file for any data type (either for inserts or updates). Place the file somewhere in the bucket you have previously set up.
2. Repeat steps for imports, but instead of "Manual" for file source, select S3. Enter the file name or the path of the file if it is inside a directory in the bucket.
3. Verify that the import has been correctly processed.
4. Create another import file and place the file somewhere in an SFTP server.
5. Repeat steps for imports, but instead of "Manual" for file source, select SFTP. Enter the file name or the path of the file if it is inside a directory in the server.
6. Verify that the import has been correctly processed.

**I. S3 and SFTP Exports**
Create an export job, but this time, check export to both S3 and SFTP. Provide file names of the destination files. Verify that export file is in the bucket and SFTP server with the correct file name or file path.

**J. Import from Previous Job**
1. Create a new CSV file for import.
2. Click "Import", click "Next", then check "From previous job." Select a previous job.
3. Check that the details from the previous job are loaded (data type, mapping, file source).
4. When job is completed, verify that the import was correctly processed according to the previous job's configuration.

**K. Export from Previous Job**
1. Click "Export", click "Next", then check "From previous job." Select a previous job.
2. Check that the details from the previous job are loaded (data type, mapping, file source).
3. When job is completed, verify that the export was correctly processed according to the previous job's configuration.

**L. Validations**
1. In the main screen, click "Import." In the details screen, without entering necessary information, click "Next." See that validation errors for job name, file upload are shown.
2. Enter an existing job name for the selected data type. Click "Next". See that there will be an error message that the job name is already taken.
3. Upload an invalid CSV file like below and enter a job name. Click "Next." See that there will be an error message in the mapping screen.
```
"Name","Slug","Parent Tag Slug",
"Cat-1","c
"Cat-2"
```
4. Click "Back" and upload an empty CSV file, then click "Next." See that there will be an error message in the mapping screen.
5. Upload a valid import file. Click "Next." Click "Back." Check "First row contains column names." Click "Next." Check that column names and sample data have been updated.
6. Click "Back." Change the mapping template. Click "Next." Check that the new mapping template was loaded.
7. Map 2 CSV column names to the same Reaction field. See that there will be an error message.

### CODE REVIEW

**Comment by ajporlante** [comment]
Closing this in favor of https://github.com/reactioncommerce/reaction/pull/4680

**Comment by zenweasel** [comment]
@ajporlante We need real testing instructions

**Comment by Akarshit** [comment]
While testing **B**, I am gettting after clicking "Done"
```
TypeError: Cannot read property 'length' of undefined
    at Object.CSVConnectorContainer.handleSubmitJobItem [as onDone] (csvConnectorContainer.js:260)
    at MappingScreen.handleClickDone (mappingScreen.js:21)
    at modules.js?hash=3c7d1fc8af47f6c9db15ea45ff988faeaef58220:57481
    at invokeFunc (modules.js?hash=3c7d1fc8af47f6c9db15ea45ff988faeaef58220:263787)
    at leadingEdge (modules.js?hash=3c7d1fc8af47f6c9db15ea45ff988faeaef58220:263797)
```

**Comment by ajporlante** [comment]
@Akarshit I fixed it. Please pull most recent commit and try again.

**Comment by Akarshit** [comment]
Getting this:
```
TypeError: Cannot read property 'length' of undefined
    at Object.CSVConnectorContainer.handleSubmitJobItem [as onDone] (csvConnectorContainer.js:253)
    at DetailScreen.handleClickDone (detailScreen.js:49)
    at modules.js?hash=3c7d1fc8af47f6c9db15ea45ff988faeaef58220:57481
    at invokeFunc (modules.js?hash=3c7d1fc8af47f6c9db15ea45ff988faeaef58220:263787)
    at leadingEdge (modules.js?hash=3c7d1fc8af47f6c9db15ea45ff988faeaef58220:263797)```
when repeating a tag import job.

**Comment by Akarshit** [comment]
1. After clicking Done I am taken back to the Jobs's table. But the status there isn't updated automatically. Is that by design?
2. When using the developer tools data, exports works fine, but when trying to import the data. The job is stuck at "Pending". No errors on the browser or server.

**Comment by Akarshit** [comment]
The table that contains the job should be sorted uniformly. Whenever a new job gets added it goes to the bottom. But when the page is refreshed(the table is created again), the sort order is latest -> oldest.

**Comment by ajporlante** [comment]
I added "optimistic" deletes to remove a job from the job queue right away when trash button is clicked. I also fixed the ordering of the job queue table when a new job is added.

**Comment by zenweasel** [comment]
Closing this in favor of creating a new 2.0-compatible version

**Pull request closed without merging**
