### PR TITLE
fix local SMTP email sending

### PR DESCRIPTION
**Pull request by jshimko**
Fixes the ability to use an SMTP provider on localhost (both UI and methods would throw errors without a username/password provided).  PR can be tested with [Maildev](http://danfarrelly.nyc/MailDev/).

```sh
npm i -g maildev

# Start mail server and inbox UI 
maildev

# SMTP server running at smtp://localhost:1025
# UI running at http://localhost:1080

# grab this branch
reaction init -b jshimko-fix-local-smtp-sending mail-fix
cd mail-fix
reaction
```
- Go to the shop's email settings
- pick `Maildev` from the dropdown
- click save 
- trigger an email send from somewhere in the Reaction UI 
- note the received email in Maildev's inbox UI (http://localhost:1080)

This also adds the ability to choose "custom" from the dropdown and enter a mail server host without user/password.  You obviously shouldn't ever do that in production, but at least now you can do things like run a custom SMTP server on localhost for development (although I highly recommend just using Maildev as the server and use the Maildev preset to connect to it).

### CODE REVIEW

**Comment by aaronjudd** [comment]
Does this replace https://github.com/reactioncommerce/reaction/pull/2645/commits/29196aede286ba4ef8ec04f519083e8846cdc21c or should that get manually added to this?

**Comment by jshimko** [comment]
Well, there's at least a small issue with that update.  It doesn't account for `settings.service` to be equal to `custom` (which would return nothing from `getServiceConfig`).  So the goal was sound, but the implementation needs some additional logic handling.  

That's also data getting passed into a UI component, so that should be happening in the container (where the [providers object already exists](https://github.com/reactioncommerce/reaction/blob/master/imports/plugins/core/email/client/containers/emailSettings.js#L9) anyway)

Give me a couple mins and I'll update my PR.

**Comment by jshimko** [comment]
Actually, nevermind.  I had already done it (with the required logic for the custom setting that I mentioned).

https://github.com/reactioncommerce/reaction/blob/61c61305b5b3ab63031387546a570a6a91631443/imports/plugins/core/email/client/components/emailSettings.js#L31-L33

**Comment by aaronjudd** [comment]
Could you also test for #1442 and #2630?

**Comment by jshimko** [comment]
#1442 was definitely out of scope of this issue, so I'm positive that hasn't changed.  I could fix it, but it's definitely a bit more work and I was just putting out the immediate fire of "can't use a mail server on localhost".  Fixing that issue would require creating pub/sub to push down the parsed values of `MAIL_URL` and/or `Meteor.settings.MAIL_URL` so the UI could display them.  Not anything _too_ crazy, but not 5 mins of work for sure.

#2630 can't possibly still be broken or this PR wouldn't work at all (since it's a branch off of marketplace).  The console errors shown in that issue appear to be something with the components API that must've been fixed by someone.  Wasn't that closed at some point anyway?

**Comment by zenweasel** [comment]
When I switch to maildev I get this:
reaction

and this error in the console:
```
  Error: Invalid login: 500 Error: command not recognized
      at Object.Future.wait (/Users/brenthoover/.meteor/packages/meteor-tool/.1.5.1.krqt03++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:449:15)
      at packages/meteor.js:213:24
      at [object Object].emailVerifySettings (server/methods/email.js:49:14)
      at packages/check.js:129:16
```

**Pull request merged**
