### PR TITLE
add Loggly integration

### PR DESCRIPTION
**Pull request by jshimko**
- add [Loggly](https://www.loggly.com/) integration for Bunyan logger
- refactor logger config to clarify level settings (I feel like `isDebug` implies a boolean, but it can also be used to set the actual log level - which is probably far more often what people use it for rather than setting `true`)

#### New Environment Variables
`REACTION_LOG_LEVEL`
`LOGGLY_TOKEN`
`LOGGLY_SUBDOMAIN`
`LOGGLY_LOG_LEVEL`

Right now, there's no UI for adding Loggly settings.  It's environment variables only because I just wanted to get something working and merged without having to make decisions about where things should go or how they should look in the UI.

To test this PR...

```sh
reaction init -b loggly-integration loggly

cd loggly

LOGGLY_TOKEN="" LOGGLY_SUBDOMAIN="" reaction
```

If both variables are set, logs will be sent to Loggly at DEBUG level by default.  That can be overridden by setting the `LOGGLY_LOG_LEVEL` env var.

Adding a UI for this later should be fairly trivial.  I just wanted to get something available so advanced users can pipe their logs somewhere other than stdout for debugging.

### CODE REVIEW

**Comment by aaronjudd** [comment]
If we're going to deprecate `isDebug` maybe we should consider #1398 at this point.  Just the level formatting, not the updating of all uses (that we can do quickly in 0.18).   We also need to update our docs, examples to reflect the new uses.  I think `isDebug` supporting boolean was in the case where it's actually `Meteor.isDebug`, but I'm not sure, and separating this is for the best I think.

**Comment by zenweasel** [comment]
Approved

**Comment by kieckhafer** [comment]
This seems like it's a good idea and the code looks good, but we are making a lot of changes here, I think we definitely need to update the docs to go along with this before it's pulled in to dev.

**Comment by aaronjudd** [comment]
Be great if we could merge this in #1584

**Comment by jshimko** [comment]
I think it'd be great if we could merge this as-is and do the other logger updates as a separate PR.  I feel like that part is going to be quite a bit of effort and probably could use a bit more group discussion.  Mostly, I think it'd be great to define some standards around what qualifies something as falling into a specific log level.  

Also, there are currently a lot of debug logs that don't output very useful information and it's unclear where they even came from without doing a search through the code.  I'd love to discuss coming up with some standards for the amount of provided detail when it comes to debug logs (kind of related to the child logger idea where context data gets embedded in the logger within the scope it's currently running in - for example, the name of the Meteor method or function that the logger instance was triggered by).  

So... maybe we merge this now and then open an issue to draw up some acceptance criteria around further logging improvements?  

@kieckhafer agreed, I'll take care of updating the docs right now.  There's not really that much changing here though.  It's really just `isDebug` becomes `REACTION_LOG_LEVEL`.  Worst case, anybody using `isDebug` would end up having their log level fall back to the default as if they hadn't set anything.  Definitely not a breaking change and I'd be surprised if many people were even using it anyway.

**Comment by aaronjudd** [comment]
@jshimko sure thing, just attach to docs PR to this issue and we're good to go.

**Comment by jshimko** [comment]
Doc updates
https://github.com/reactioncommerce/reaction-docs/pull/140

**Comment by aaronjudd** [comment]
👍  @jshimko thanks. looks good.

**Pull request merged**
