### PR TITLE
Don't overwrite Shop data with fixtures 

### LINKED ISSUE #2578: Return of the standard values of Shop Localization, Languages and Currencies after every Meteor server restart
### Expected behavior
Do not set the defaults from the file "\private\data\Shops.json" after each server reboot.

### Actual Behavior
Return of the standard values of Shop Localization, Languages and Currencies after every Meteor server restarted.

### Steps to Reproduce the Behavior

1. Start reaction
1. Change any Dashboard values of Shop Localization, Languages or Currencies. After restarting the Meteor server, these values will change to the default values from the file "\private\data\Shops.json"

I think the problem is in the file "\server\startup\load-data.js". Reaction.Import.flush(Shops) - without checking the existence of the store in the database, overwrites the data from the file "\private\data\Shops.json".

This decision is not elegant, but it works:

import { Meteor } from "meteor/meteor";
import { Shops } from "/lib/collections";
import { Logger, Reaction } from "/server/api";
import { Fixture } from "/server/api/core/import";

export default function () {
  /**
   * Hook to setup core additional imports during Reaction init (shops process first)
   */
  Logger.info("Load default data from /private/data/");

####  if (!Reaction.getShopId()) {

    try {
      Logger.debug("Loading Shop Data");
      Reaction.Import.process(Assets.getText("data/Shops.json"), ["name"], Reaction.Import.shop);
      // ensure Shops are loaded first.
      Reaction.Import.flush(Shops);
    } catch (error) {
      Logger.error(error, "Bypassing loading Shop default data");
    }

    // make sure the default shop has been created before going further
    while (!Reaction.getShopId()) {
      Logger.debug("Loading default shop, waiting until it's ready before moving on...");
      Meteor._sleepForMs(1000);
    }

    try {
      Logger.debug("Loading Shipping Data");
      Fixture.process(Assets.getText("data/Shipping.json"), ["name"], Reaction.Import.shipping);
    } catch (error) {
      Logger.error(error, "Bypassing loading Shipping default data.");
    }

    try {
      Logger.debug("Loading Product Data");
      Fixture.process(Assets.getText("data/Products.json"), ["title"], Reaction.Import.product);
    } catch (error) {
      Logger.error(error, "Bypassing loading Products default data.");
    }

    try {
      Logger.debug("Loading Tag Data");
      Fixture.process(Assets.getText("data/Tags.json"), ["name"], Reaction.Import.tag);
    } catch (error) {
      Logger.error(error, "Bypassing loading Tags default data.");
    }
    //
    // these will flush and import with the rest of the imports from core init.
    // but Bulk.find.upsert() = false
    //
    Fixture.flush();

####  } else {

    try {
      Logger.debug("Loading Shipping Data");
      Fixture.process(Assets.getText("data/Shipping.json"), ["name"], Reaction.Import.shipping);
    } catch (error) {
      Logger.error(error, "Bypassing loading Shipping default data.");
    }

    try {
      Logger.debug("Loading Product Data");
      Fixture.process(Assets.getText("data/Products.json"), ["title"], Reaction.Import.product);
    } catch (error) {
      Logger.error(error, "Bypassing loading Products default data.");
    }

    try {
      Logger.debug("Loading Tag Data");
      Fixture.process(Assets.getText("data/Tags.json"), ["name"], Reaction.Import.tag);
    } catch (error) {
      Logger.error(error, "Bypassing loading Tags default data.");
    }
    //
    // these will flush and import with the rest of the imports from core init.
    // but Bulk.find.upsert() = false
    //
    Fixture.flush();

####  }

}

### Versions
Node: 6.11.1
NPM: 3.10.10
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction CLI: 0.11.0
Reaction: 1.4.0
Docker: 17.05.0-ce

### PR DESCRIPTION
**Pull request by zenweasel**
This is not the elegant solution I was hoping for but it works and doesn't break anything else.

Resolve #2578 and adds a `SKIP_IMPORT` environment variable

### CODE REVIEW

**Comment by zenweasel** [comment]
So this has the unfortunate side-effect of some packages not appearing after you reset. 🤔

**Comment by aaronjudd** [comment]
@machikoyasuda @zenweasel needs docs added to configuration.md?

**Comment by zenweasel** [comment]
@aaronjudd Yeah, for sure. Was waiting until we were all cool with how the ENV variable worked.

**Comment by aaronjudd** [comment]
Maybe this should be `SKIP_FIXTURES` instead?
because even though these use Reaction.import they really are the fixtures mode of imports.

**Comment by zenweasel** [comment]
@aaronjudd Yeah, makes sense. Will change

**Pull request merged**
