### PR TITLE
Zoom image in PDP

### PR DESCRIPTION
**Pull request by Akarshit**
## Fix for #3100

This uses the [react-image-magnify](https://github.com/ethanselzer/react-image-magnify) component to render the main image in PDP.

I have tuned some small things like the delay in showing the zoomed image, etc. on a _as I like basis_. Would like to get view of others on this.

### To review
We don't support multiple res. of same image right now. So I am basically zooming the image and showing it to the user. Is this the intended behaviour?

### To test
1. Run `reaction`
2. Upload some image in the `example-product`
3. Hover over the image and see it zoomed.
4. Also try the mobile version which responds to long press instead of hover.
5. Also turn off the edit mode `on` and hover on the image, there should be no zoomed image visible.
5. Log out and log in as a customer, you should be able to see the zoomed image on hover.

### CODE REVIEW

**Comment by rymorgan** [comment]
@zenweasel I'm not seeing this PR in the repo for some reason.

**Comment by zenweasel** [comment]
@rymorgan It's not a branch on our repo (I don't know why @Akarshit is still doing that). Here are command line instructions for pulling his changes locally. The first line creates a new local branch from master and the second line pulls his changes from his remote branch into your local branch you just created.

```
git checkout -b Akarshit-enhan-zoomImage master
git pull https://github.com/Akarshit/reaction.git enhan-zoomImage
```

**Comment by rymorgan** [comment]
@Akarshit I think the straight out of the box example is a better execution than what we have in this PR. We can have the image show up to the right of the image (or left when we for right to left language). We need to preserve the way they are highlighting the area of the image that is being zoomed. 

Example here:
https://ethanselzer.github.io/react-image-magnify/#/

@spencern @zenweasel I think this would be a good case for having a UI preference center where users have a UI to turn zoom on off along with other preferences. My ongoing list: https://docs.google.com/spreadsheets/d/1ABYaTcyPfV3uEstT3jai--QJi0c6e992_V7EHfA49QE/edit#gid=0

**Comment by Akarshit** [comment]
@zenweasel I was just doing that because I didn't want to clutter reaction's branches. Will now push the branch to reaction from now on.

@rymorgan Ok cool I will change it back. Also will have to see about the `rtl` thing.

**Comment by zenweasel** [comment]
@Akarshit Yeah, as long as we can clean up afterwards I would prefer it.

**Comment by Akarshit** [comment]
@rymorgan I have updated the PR, had to remove some opacity from the parents for this to work. Also I have updated the test instructions to also test with edit mode `on`.

**Comment by Akarshit** [comment]
Update: This is working with RTL now. Please review.

**Comment by rymorgan** [comment]
@Akarshit @zenweasel I don't' know how to update this branch because it wasn't done in the usual way. In github desktop, I don't get a sync button. In terminal when I try to pull changes I get this: 

screen shot 2017-11-30 at 3 53 20 pm

**Comment by zenweasel** [comment]
@rymorgan Whenever a community member is not already a contributor they need to create their PR from their own repo as we don't allow them to create branches directly on the Reaction repo. This is actually how most open source projects work most of the time. (@Akarshit now has the rights to do this and is doing this going forward but a lot of people won't).

So when that's the case you need to do these things to get their branch.

**1. Create a local branch off master to store the changes (the branch can be named anything that will make it clear what it is)**
```
git checkout -b akarshit-enhan-zoomImage master
```

**2. Pull the changes from the remote repo into the local branch**
```
git pull https://github.com/<remote_repo>/reaction.git <branch_name>
```
So in this case it would be:

```
git pull https://github.com/Akarshit/reaction.git enhan-zoomImage
```

If you get a message saying "cannot fast-forward" it usually means you need to update the remote branch to align with master which you can usually do by hitting the "Update Branch" button. Right now it looks like @Akarshit needs to resolve some conflicts so I don't know if there is anything you can do about that.

**Comment by rymorgan** [comment]
@zenweasel Great! Thanks.

**Comment by rymorgan** [comment]
@Akarshit You've made some good progress here. The standard desktop view is looking good. 

As I see it what remain to get this over the finish line is:  

Mobile's not working correctly. Looks like this now. 
djhoqenwky

Should look like this (also check out the example on mobile) I'd include that message on first load about the long press too. 
opfoytdmnz

Include this: 
zoom

The for rtl languages it's working but there spacing's not right. The spacing should match the ltr languages. 

rtl
lftr

**Comment by Akarshit** [comment]
@rymorgan Did all the changes you asked. Please check.
Also I would be AFK this week, so feel free to push any further changes(or you can wait for me to come back).

**Comment by rymorgan** [comment]
@Akarshit It's looking good. RTL spacing is correct now. Also, it's working correctly on mobile. 

I have some small styling changes to make it consistent with our Reaction design guidelines. 

- [ ] The long press for mobile should be moved to the bottom.
- [ ] Use source sans pro for the type on "Long-touch to zoom" (looks like it might not be) 
- [ ] "Long-touch to zoom" needs to be sentence casing. 
- [ ] Remove the "+" symbol
 
See my quick mock. 
slice 1

**Comment by Akarshit** [comment]
@rymorgan Pushed with all the changes you requested. Please review.

**Comment by zenweasel** [comment]
@Akarshit Looks like you have some lint issues to take care of

**Comment by rymorgan** [comment]
@Akarshit This looks good! Nice work. One final thing and I'm good. Can you move the "long touch to zoom" to be 15 px from the bottom rather than the around 30px it is now?  I want it to not overlap people's product photos as much as possible.

**Comment by Akarshit** [comment]
@rymorgan Updated.
@zenweasel Fixed the linting issue(somehow my linter was not working)

**Comment by zenweasel** [comment]
@Akarshit Looks like you still have lint issues to fix. Check the Codacy link to see the details.

**Comment by rymorgan** [comment]
This PR is good to for me whenever the lint issues are fixed.

**Comment by zenweasel** [comment]
Testing this on mobile with the simulator it looks like the main image is being obscured and when I long press nothing happens.

**Comment by Akarshit** [comment]
@zenweasel By simulator do you mean the device selector in browser dev tools?

**Comment by zenweasel** [comment]
No, I mean the iPhone device simulator included in XCode. And I have refresh several times in that view.

**Comment by zenweasel** [comment]
Ok, I don't know what was happening, but after making everyone try it it seems to working now on iPhone.

**Pull request merged**
