### PR TITLE
Extra char causing Cart Remove Execution Flow to Break without warning

### PR DESCRIPTION
**Pull request by hrath2015**
Found extra char ~ while debug the remove from Cart flow in below line.
if (!~resetToIndex) return false;

### CODE REVIEW

**Comment by newsiberian** [comment]
Hello, lol, this is not just an extra char. Please, google: "Bitwise Not + indexOf"

**Comment by hrath2015** [comment]
Thanks for pointing it out. Tried in Node env from command line and  it gave me undefined on console.

**Comment by newsiberian** [comment]
Could you explain your use case? Maybe it will be better not to return false. Maybe throw something...

**Comment by hrath2015** [comment]
As of now I am trying simple stuff to work. Remove an item from cart itself  not going through. All looks good in console print. But nothing changes in Mongo.

**Comment by aaronjudd** [comment]
need to test still, but agree with @newsiberian might be better to throw an error, we have a lot of these "silent defaults" when we really should just be throwing an error and working to resolve the error.

**Comment by newsiberian** [comment]
> need to test still, but agree with @newsiberian might be better to throw an error, we have a lot of these "silent defaults" when we really should just be throwing an error and working to resolve the error.

Hi, I don't think so. This PR has no deal with the bug reason. I think `workflow/revertCartWorkflow` are fine. No need to change to change anything it current method logic. I think we should close this PR.

**Pull request closed without merging**
