### PR TITLE
Update email for inviting a user to create a shop

### LINKED ISSUE #2804: Update email copy for inviting a user to create a shop
We need to update the copy for the email that goes out when a marketplace admin invites a new user to create/manage a new shop on their marketplace platform.

This issue can serve as the base for the discussion as to what this email should contain.

Here is the current email:
image

At a minimum, the updated copy should clarify:
- Who/which marketplace is doing the inviting, right now you're being invited by the new shop that you're asked to create. This doesn't make sense.
- What you'll need to do to accept this invitation
- That this is _not_ marketing email and you've been invited directly by the marketplace manager.

We can - and perhaps should - include the new name of the shop in the form when the invite is created rather than appending a "1" or leaving off the shop name?

Other thoughts on this?

### PR DESCRIPTION
**Pull request by impactmass**
Resolves #2804. 
_ Updates email copy for new shop owner and uses the primary shop details (name, address etc) when sending email to new owner (instead of the newly created shop details as before).
_ Also updates the email copy sent to a user when added to a group (see ticket for the copy #2804)

**How To Test:**
- Invite a new owner/merchant under Shop > Marketplace in dashboard
- Confirm updated copy in the email sent to the merchant
- Invite a new user to a group in Accounts > Add Admin User in dashboard in Primary Shop
- Confirm updated copy in the email sent to the account
- Invite a new user to a group like above but in a merchant shop
- Confirm that email copy sent is also updated (and it reflects the right shop name)

### CODE REVIEW

**Comment by kieckhafer** [comment]
This looks good overall, everything works as it should. My one comment is I think we should update the copy to read something like:

{{currentUserName}} has invited you to join *the group* {{groupName}} in *the store* {{shopName}}

And update the subject to read something similar. What we have now doesn't flow very well or explain what `Shop Manager` or `Reaction1` are.

airmail

**Comment by rymorgan** [comment]
Agree with @kieckhafer

**Comment by impactmass** [comment]
Ok. I'll make that update shortly

**Comment by impactmass** [comment]
Updated based on the comment. cc @kieckhafer

**Comment by kieckhafer** [comment]
@impactmass I made one small change that just removes the quotes from surrounding the shop name, but aside from that this is good! Going to merge as soon as the tests pass.

**Pull request merged**
