### PR TITLE
Fixes #1524 - Type Error thrown by empty addressBook

### LINKED ISSUE #1524: Upgrading 0.15 -> 0.17 throws type error
### Actual Behavior

Here's the error

```
Exception in setTimeout callback: TypeError: Cannot read property 'fullName' of undefined
    at Object.transformations.accounts.profile (imports/plugins/included/search-mongo/server/methods/transformations.js:31:45)
    at buildAccountSearch (imports/plugins/included/search-mongo/server/methods/searchcollections.js:212:32)
    at JobQueue.worker (imports/plugins/included/search-mongo/server/jobs/buildSearchCollections.js:145:7)
    at JobQueue._process (packages/vsivsi_job-collection/job/src/job_class.coffee:191:8)
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at packages/meteor/timers.js:6:1
    at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1)
```
### Steps to Reproduce the Behavior

Upgraded existing shop with data to `reaction:master` 0.17

PR incoming.

### PR DESCRIPTION
**Pull request by spencern**
Error was caused by `fieldData.addressBook` existing as an empty array, this checks to make sure that `addressBook[0]` exists before looking for the `fullName` prop.

- [x] Description explains the issue / use-case resolved
- [x] Only contains code directly related to the issue
- [x] Has been linted and follows the style guide

### CODE REVIEW

**Comment by zenweasel** [comment]
Approved

**Comment by spencern** [comment]
Apparently this breaks a test. Checking into that now.

**Comment by spencern** [comment]
Yeah that funky syntax works because arrays in js are actually objects. But... that shouldn't have been committed, and I've reversed it to just fixing the typo `addressBook` instead of `addressbook` because that syntax is a bit unnecessary.

**Comment by aaronjudd** [comment]
👍

**Pull request merged**
