### PR TITLE
Release 1.5.9

### PR DESCRIPTION
**Pull request by spencern**
# v1.5.9

## Fixes
 - Fix uniqueItem._id undefined (#3296)
 - Fix: hide settings panels merchant shops (#3299)
 - (fix): Translation component issue returning undefined instead of defaultValue (#3313)
 - fix Cart.getShippingTotalByShop and use it in Cart.getSubTotal and in… (#3214)
 - fix order values store as string (#3222)
 - Fixed indicating products that are invalid for publication (#3147)
 - Checking if the variant belongs to current product (#3267)
 - Use React components for footer and header (#3257)
 - Ryan color type tweaks (#3281)

## Refactors
 - Convert TaxCloud panel to React (#3121)

## Style
 - Remove extraneous blank line (#3272)

### CODE REVIEW

**Comment by zenweasel** [comment]
Are these new grey lines supposed to be here? Totally not testing this PR or nothing but....
reaction

**Comment by spencern** [comment]
🤔 Hmm.. @rymorgan any thoughts on that? 
@zenweasel do you think they got introduced in this release?

**Comment by zenweasel** [comment]
They were there before but they are darker and thicker now? From `master`. Probably from Ryan's color tweaks? I don't have an opinion, just want to make sure that is what was intended.

reaction

**Comment by zenweasel** [comment]
Word from @rymorgan is that's the intended result. Approving.

**Pull request merged**
