### PR TITLE
Fix Reset password link and overlays broken

### PR DESCRIPTION
**Pull request by impactmass**
WIP on the bug #2605. Currently testing

How to test:
_ Clone, and `reaction`
_ Invite a new user (via the Accounts admin) (make sure email is enabled)
_ Go to the email of the new user and follow the link
_ Confirm that on the link opening, a password reset modal opens
_ Enter password and save, and confirm that there are no errors.

### CODE REVIEW

**Comment by spencern** [comment]
Haven't checked the invite link yet, but the reset password link still doesn't work for me.

image

```
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in. Check the render method of `Forgot`.
    in Forgot (created by Reaction(ForgotPassword))
    in Reaction(ForgotPassword) (created by Reaction(Login))
    in Reaction(Login) (created by Reaction(MainDropdown))
    in div (created by Reaction(MainDropdown))
    in div (created by Reaction(MainDropdown))
    in div (created by Reaction(MainDropdown))
    in div (created by Reaction(MainDropdown))
    in Reaction(MainDropdown) (created by Tracker(Reaction(MainDropdown)))
    in Tracker(Reaction(MainDropdown)) (created by withProps(Tracker(Reaction(MainDropdown))))
    in withProps(Tracker(Reaction(MainDropdown))) (created by Tracker(withProps(Tracker(Reaction(MainDropdown)))))
    in Tracker(withProps(Tracker(Reaction(MainDropdown)))) (created by Reaction(NavBar))
    in div (created by Reaction(NavBar))
    in Reaction(NavBar) (created by Tracker(Reaction(NavBar)))
    in Tracker(Reaction(NavBar)) (created by Reaction(CoreLayout))
    in div (created by Reaction(CoreLayout))
    in Reaction(CoreLayout) (created by Route)
    in Route
    in div (created by App)
    in App (created by Tracker(App))
    in Tracker(App)
    in TranslationProvider (created by Tracker(TranslationProvider))
    in Tracker(TranslationProvider)
    in Router (created by BrowserRouter)
    in BrowserRouter
printWarning @ modules.js:84626
modules.js:84794 
```

**Comment by spencern** [comment]
On the `development` specific fix, when I click through from an invite the overlay appears (Yay!) but then I'm not logged in and a weird blank new user is created.

Video of the issue: http://recordit.co/U3xxi6rRoo

Weird users:
image

**Comment by impactmass** [comment]
I'll check on this asap. I fixed the overlay first..(as it relates most to the other ticket I was working on). 

I'll try and re-create the weird user accounts and log in issue. I (and also @awa) and didn't get that when I tested.

**Comment by impactmass** [comment]
Recorded this just now https://www.dropbox.com/s/ur1et424g4zvx3q/rec.mov?dl=0  (I haven't edited anything yet)... no weird users and login fine.  (I'll still see if I can repro it)
For now: I'm working on Reset link now.

**Comment by spencern** [comment]
@impactmass interesting. I'll reset and try again.

**Comment by spencern** [comment]
@impactmass - I just did a full reset and am not able to reproduce the login issue anymore. 👍

**Comment by impactmass** [comment]
The core fix for reset password link, overlays, and inviting new users looks good to go. 
I added a TODO comment on "cart/merge" as it throws a validation error when a password reset it done (because `currentSessionId` shows up as false). Added the comment since fixing that will go out of the scope of this PR

**Pull request merged**
