### PR TITLE
Provide additional production docker images

### PR DESCRIPTION
**Pull request by tdecaluwe**
This PR refactors the docker setup so that images for the following purposes can be easily created:
* Fast building development image (the original image)
* Production image which includes a mongodb installation. The provided dockerfile yields images around 250mb in size.
* Production image which uses an external mongodb server (to use as a deployment image in #402 for example).

Both new production images are based on debian wheezy. The root `Dockerfile` is a symlink into the `docker` folder which contains all dockerfiles. Other images can be built as follows:

```
docker build -t reactioncommerce/reaction:mongo -f docker/reaction.mongo.docker .
docker build -t reactioncommerce/reaction:minimal -f docker/reaction.minimal.docker .
```

### CODE REVIEW

**Comment by tdecaluwe** [comment]
This PR should be able to build after solving #504. Any feedback, thoughts or suggestions always welcome. I'm currently trying to build a tutum workflow on these images.

**Comment by aaronjudd** [comment]
How are you accounting for the fact that you'll need to run in development mode to create LESS files for these other images? If you build your image in a normal "production" way - those files won't get created and you'll have a docker image that runs reaction - but without styling.

Also, we are using the current images in a tutum workflow, as part of Launchdock2 - a project we'll be sharing more about soon. @jshimko is working through the final details of this, and has also been looking at refactoring the Dockerfile to trim things down a bit.

**Comment by tdecaluwe** [comment]
@aaronjudd I'm currently not. But if you or @jshimko are interested, I'll look into it, and fix up the dockerfiles.

**Comment by tdecaluwe** [comment]
@aaronjudd These dockerfiles are something I'd cooked up to get a staging environment running, I'd be happy to add them, but if you've got better dockerfiles laying around, please use those!

**Comment by tdecaluwe** [comment]
I read too fast, the proposed docker files do take into account the theme building. In fact, I'm using all the infrastructure in `bin/docker` already present (`build-meteor.sh`, `build-themes.sh` and `build-packages.sh`) as to maintain images which should be compatible with the image already present in the repo.

What I wanted to accomplish was this:
* A development image (I kept the one already present for this), which builds fast. This image should have a separate `aufs` layer for the meteor installation so we don't have to download this each time in development env.
* Separate production images which are very small. They build considerably slower, because they don't keep any unnecessary data, like the meteor installation, they just keep the bundle. However deploy time is considerably faster.
* Stateless app code shoudn't be in a volume like in the current image, instead one just redeploys a new image linking to the same production db.

I created a separate image with mongodb ideally suited for testing envs and another without mongodb meant for staging and production envs.

**Pull request merged**
