### PR TITLE
[WIP] Fix email verification url from the Getting Started email

### LINKED ISSUE #2623: [Marketplace] Receive 404 when clicking on link for "Getting Started" email
### Expected behavior
Should be taken to this page
account_verify

### Actual Behavior
Receive "Not Found" page

### Steps to Reproduce the Behavior
1. Register as a user with a valid email
1. Click on the link in the email
1. Observe it takes you to the "Not Found" page

### Versions
```
Node: 7.10.0
NPM: 5.0.3
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction CLI: 0.11.0
Reaction: 1.5.0
Reaction branch: marketplace
Docker: 17.06.0-ce
commit: b6e18a4b5a35b852bd75648ae395a2f4b77eae81
```

### PR DESCRIPTION
**Pull request by jm-wanja**
Resolves #2623 

**How To Test**

1. Register as a new user with a valid email address.
2. Click on the `Get Started` in the email received.
3. Observe that it directs you to the verification page.
screen shot 2017-09-20 at 2 16 32 pm

### CODE REVIEW

**Comment by zenweasel** [comment]
When I copy and paste the link into an incognito browser I get the "permission denied" screen

account_verify

**Comment by jm-wanja** [comment]
The issue where the link sometimes (not every single time) leads to the `permission denied` page has started to become a blocker. I have yet to pinpoint why it behaves the way it does.

**Comment by jm-wanja** [comment]
I'm having issues with consistently reproducing this https://github.com/reactioncommerce/reaction/pull/2905#issuecomment-331014060 and it's basically become a blocker into solving it, any pointers will be appreciated

**Comment by janus-reith** [comment]
Couldn't we separate these issues?
The commit is removing the prefix altogether, is this the way the verification url route is registered now?

Im asking because I think the way prefixes are handled was broken in several places.
Prevously it was the issue that a prefix name was returned for single shops although the routes were registered without one. Now it properly returns just a Slash without a Name, but this also leads to issues as part of the code that use this function insert another slash themselves.

**Comment by spencern** [comment]
Closed in favor of #3046

**Pull request closed without merging**
