### PR TITLE
Send order notification when user adds email

### LINKED ISSUE #431: Email confirmation on guest order update entry
Confirm email account and register a user account for a guest who adds their email to the order confirmation page.

### PR DESCRIPTION
**Pull request by kieckhafer**
Fixes #431

### CODE REVIEW

**Comment by kieckhafer** [comment]
I am aware there is an error reported in the log regarding `Alerts` not being defined. This is fixed in #1585, I just branched this off of `release-0.18.0`, where that fix is not yet pulled in.

**Comment by zenweasel** [comment]
👍  Tested: Verified works

**Comment by zenweasel** [comment]
Actually, the subject of the email I got said "Your order has shipped"

**Comment by kieckhafer** [comment]
The subject line is / should be fixed in #1585. Since it's just going into the release branch, and not into development, I think we should merge if everything else is OK, and once #1585 is merged I will double check to make sure the subject is correct.

**Pull request merged**
