### PR TITLE
[WIP] Fix red dots appearing on products in marketplace

### LINKED ISSUE #2868: Red dots appear on products created in Marketplace shops
### Expected behavior
No red dots should show up on valid products

### Actual Behavior
Red dots appear on some products

reaction

### Steps to Reproduce the Behavior
1. Login as admin
1. Create a second shop
1. Login as that second shop owner
1. Create a product
1. Return to your Main shop
1. Observe that red dots appear on marketplace products

### Versions
```
Node: 7.10.0
NPM: 5.3.0
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction CLI: 0.11.0
Reaction: 1.5.0
Reaction branch: marketplace
Docker: 17.06.2-ce
```

### PR DESCRIPTION
**Pull request by jm-wanja**
Resolves #2868 

The variant validation for the `inventoryQuantity` field was causing this issue, I noted that we were using the `ReactionProduct.checkChildVariants` in the custom validation which was causing the validation to change from false to true depending on whether the variant has child variants instead of `ReactionProduct.checkInventoryVariants` which checks if the quantity field for the inventory has been filled. 

**Note:** Product variants that have the inventory quantity field empty will fail the variant validation in both the second shop and marketplace, resulting to the red dot.

**How To Test**
1. Login as as Admin
2. Create a second shop
3. Login as the second shop owner
4. Create a product
5. Observe that any product that is failing validation in the second shop is also failing the validation in the marketplace.

### CODE REVIEW

**Comment by aaronjudd** [comment]
@jm-wanja @zenweasel is on vacation.. can we have another reviewer to expedite this?

**Comment by zenweasel** [comment]
This introduces a new behavior that I am not sure we want.

flack

**Comment by zenweasel** [comment]
If you leave the quantity blank and click on "Variant Options" nothing happens and you aren't able to add options.

**Comment by zenweasel** [comment]
I am seeing an issue where when I create a product in the marketplace shop which is invalid, go to the Product Grid and then click on the invalid product it locks up the browser and I have to kill the tab.
page_unresponsive_and_flat_product

**Comment by rymorgan** [comment]
Just made this issue, possibly related or redundant. 

https://github.com/reactioncommerce/reaction/issues/3014

**Comment by zenweasel** [comment]
Solution seems to be ephemeral. Closing for now and let's back out the original change and revisit this at a later time.

**Pull request closed without merging**
