### PR TITLE
Added inventoryPolicy check and min removed from Schema

### PR DESCRIPTION
**Pull request by Akarshit**
Fix for #2743 

1. Removed that `min: 0` check from `Product` schema.
2. Added a condition to check for the inventoryPolicy before rejecting a order.

But this would cause the inventoryQuantity to be as negative as the no. of backorders on that variant. Is this the required behaviour?

### CODE REVIEW

**Comment by aaronjudd** [comment]
@Akarshit this looks good, but can you resubmit to marketplace (or we can release if there is a 1.4.3, but I'd rather just bring it into marketplace now as we're doing a fixes to the PDP).  @spencern let's keep an eye and cherry-pick if needed to move this along.

**Comment by Akarshit** [comment]
@spencern Changed base and updated the PR.

**Comment by spencern** [comment]
This PR raises a few issues that are related but not caused by this PR. I'll create separate issues for these, but also list them here.

1. Toggling inventoryPolicy / "Allow Backorder" for a variant does _not_ cascade that choice into it's options
2. Options do not have a switch that will permit toggling the inventory policy. I had to edit the inventoryPolicy for the options in the database directly in order to permit backordering on the default product.

image

**Comment by spencern** [comment]
https://github.com/reactioncommerce/reaction/issues/2911 is the new issue that I created to address the additional issues noticed here.

**Pull request merged**
