### PR TITLE
Remove remnant from older version..

### PR DESCRIPTION
**Pull request by prinzdezibel**
- [ ] Description explains the issue / use-case resolved
- [ ] Only contains code directly related to the issue
- [ ] Has tests.
- [ ] Has docs.
- [ ] Passes all tests
- [ ] Has been linted and follows the style guide

### CODE REVIEW

**Comment by aaronjudd** [comment]
Not accepting this, it's a valid setting and is still in use.

**Comment by prinzdezibel** [comment]
Don't understand how this can be in use. It's not in ReactionCore.Schemas.CorePackageConfig schema and also I can't find references to it in code.

**Comment by aaronjudd** [comment]
actually, you are correct , its `defaultPaymentMethod: shop.defaultPaymentMethod`

**Comment by mikemurray** [comment]
👍 

This is ok to remove as it has defaults in code if not set.

**Pull request merged**
