### PR TITLE
Updated order of imports.

### LINKED ISSUE #1189: Update order of plugin imports
Update the order of plugin imports so that custom is loaded last. 

This is helpful with CSS overrides, and other cascading changes. For example, any CSS in plugins in the `included` directory will override any CSS in the `custom` directory; which is not ideal.

**imports currently currently**
- core
- custom
- included

**imports updated to**
- core
- included
- custom

### PR DESCRIPTION
**Pull request by mikemurray**
Fixes #1189 

Update order of variable declarations to be consistent with order of
imports.

### CODE REVIEW

**Comment by jshimko** [comment]
👍  Approved.

**Comment by jshimko** [comment]
FYI, this is going to create a merge conflict with my PR for the Windows path fix.  We both changed the same file.

**Comment by jshimko** [comment]
Oh by the way, you need to update the order [in the bash script](https://github.com/reactioncommerce/reaction/blob/master/.reaction/docker/scripts/plugin-loader.sh#L20) too.  Just change that array:
```sh
# from this
PLUGIN_SUB_DIRS=("core" "custom" "included")

# to this
PLUGIN_SUB_DIRS=("core" "included" "custom")
```

**Comment by mikemurray** [comment]
got it, thanks

**Comment by jshimko** [comment]
Ok, now 👍 for real.

**Comment by aaronjudd** [comment]
👍

**Pull request merged**
