### PR TITLE
update cfs:gridfs npm dependencies to fix bson error

### PR DESCRIPTION
**Pull request by jshimko**
Since Meteor 1.4, we've been getting the following error on every startup...

```sh
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
(STDERR) js-bson: Failed to load c++ bson extension, using pure JS version
```

It doesn't break anything, but it's a performance issue.  It turns out that it's being caused by the outdated npm dependencies in the deprecated `cfs:gridfs` package, so I copied that package into the local packages folder and updated its dependencies.  Problem solved.

See further discussion at https://github.com/meteor/meteor/issues/7477

### CODE REVIEW

**Comment by jshimko** [comment]
More specifically, I changed this...

```js
Npm.depends({
  "mongodb": "1.4.35",
  "gridfs-stream": "0.5.3"
});
```

to this...

```js
Npm.depends({
  "mongodb": "2.2.9",
  "gridfs-stream": "1.1.1"
});
```

Otherwise, the package is identical.

**Comment by aaronjudd** [comment]
This is part of the work that is defined in the issue #1221 that is scheduled for 0.17.0.

**Comment by jshimko** [comment]
Yeah, I know.  I just though a temporary/simple solution was reasonable since people are going to continue to ask about the error.  

I'm fine with whatever though.

**Comment by aaronjudd** [comment]
That comment was to ensure that this PR was tracked to #1221.

This patch works (tested), and is something that I considered doing for the last release.  I was probably just being stubborn, but re-polluting the packages directory was the primary deterrent, and because I thought the CFS replacement issue is of sufficient criticality that we should keep the errors screaming at us every day as a non-breaking warning. 

The work is done now though, and now that we've connected the dots,etc  I'm 👍

**Comment by jshimko** [comment]
Yeah, using the packages directory felt a little gross to me too, but so did the ugly error.  But then I convinced myself the temporary fix was probably worth the trouble/ugliness since it shouldn't be there for too long.

**Comment by zenweasel** [comment]
No one asked me, but I too agree that it's worth fixing in the short-term so people don't perceive Reaction as "broken". I think GridFS is a big enough pain that we won't forget it.

**Comment by zenweasel** [comment]
Approved

**Pull request merged**
