### PR TITLE
Add offset argument for numerical pagination

### PR DESCRIPTION
**Pull request by cmbirk**
Impact: **minor**  
Type: **feature**

## Issue
Adds `offset` as an argument to the catalogItems query to allow for numerical pagination.

### CODE REVIEW

**Comment by spencern** [comment]
Hey @cmbirk 
Thanks so much for the PR! 
Would you be willing to add some tests that validate the offset pagination works as you'd expect to this PR? 
Here are some files with tests for the existing catalog queries and pagination:
https://github.com/reactioncommerce/reaction/blob/master/tests/catalog/catalogItems.test.js
https://github.com/reactioncommerce/reaction/blob/master/tests/catalog/catalogItemsByTag.test.js
https://github.com/reactioncommerce/reaction/blob/master/tests/tag/tags.test.js

I'd think adding a new file into `/test/catalog` might be the best approach here, but you may be able to add tests to one of the existing catalog test files.

**Comment by spencern** [comment]
Also, before we can merge this, we ask that you sign your commits.

We use the [Developer Certificate of Origin (DCO)](https://developercertificate.org/) in lieu of a Contributor License Agreement for all contributions to Reaction Commerce projects.

If you click the details link in the “checks” section of this PR - you can find a guide for signing your PR. 
image


If you still have questions? You can read more general information about signing your commits here: https://probot.github.io/apps/dco/

Your contribution is appreciated!

**Comment by cmbirk** [comment]
Sure thing! I'll work on those asap. Thanks :)

**Comment by cmbirk** [comment]
Closing this in favor of #5228 which was created so that the history wouldn't have to be rewritten here.

**Pull request closed without merging**
