### PR TITLE
fix package.json to run tests for router

### PR DESCRIPTION
**Pull request by hrath2015**
- [ ] Clearly explain what your PR is trying to accomplish. A link to an issue is best
 Tests were failing. After this it runs fine.
- [ ] Provide us detailed instructions on how we can test your PR
 `npm test` and see 

image

### CODE REVIEW

**Comment by zenweasel** [comment]
@hrath2015 Is this a Window-only thing as I am not seeing an error when running tests.

**Comment by mikemurray** [comment]
@zenweasel yes, windows only

**Comment by hrath2015** [comment]
Below was the error..which indicates it was not able to locate stubs. 
image

**Comment by mikemurray** [comment]
After some VM setup, can confirm its working on Win 10, and still works on OSX. Waiting on tests to pass CI before approving.

**Pull request merged**
