### PR TITLE
[WIP] 2115 Inconsistent Product Image of Cart Item

### PR DESCRIPTION
**Pull request by andela-aatanda**
Resolves [2115](https://github.com/reactioncommerce/reaction/issues/2115)

**Testing**
- Clone branch
- Run on you local machine
- Add an image to an option in the Basic Reaction Product
- Create a new product and upload an image for it.
- Publish your changes and toggle edit mode
- Add both the Basic Reaction Product that has an image and the New Product to cart
- Observe that both products maintain their images when either product is clicked and no errors in console

### CODE REVIEW

**Comment by zenweasel** [comment]
Looking at this code it doesn't look like it will work if you have multiple items in your cart. Are you sure you have thoroughly tested this?

**Comment by andela-aatanda** [comment]
@zenweasel I have tested this a couple of times with up to 3 items in `Cart` and it behaved as expected.

**Comment by andela-aatanda** [comment]
screen shot 2017-04-30 at 11 06 22 am

**Comment by zenweasel** [comment]
So the behavior should be that when an option does not have an image, it should use the image from the variant or the top-level product (whichever comes first). People are not going to assign images to 20+ individual shoe sizes for example, but we should still show the image of the shoe. Or if an image was assigned for a color, we should show that.

another_dumb_product

**Pull request merged**
