### PR TITLE
RemoveFromCart refactor

### LINKED ISSUE #611: Remove cart item is causing the error
Hello,
error1

This happens because `inventory/clearStatus` method running twice: on client (where throws this error) and on server where forks fine. So, why we have this method in `common` folder?

Also, where is two more methods in this file which calls `ReactionInventory.Log` object, which is undefined from client side...

### PR DESCRIPTION
**Pull request by newsiberian**
Hello,
I did not find a reason why `cart/removeFromCart` method is shared, so I moved it to server folder. Also method now receive only `cartItemId` instead of two args - `cartId` and `item` object!! I think this is more secure way.

Also, I don't know do you have a plans to use this method by admin to manipulate user's cart? If yes, it is needed to add few lines of code to implement this functionality. Because of this I leave tests without changes for now...

This is fixed #611.

### CODE REVIEW

**Comment by aaronjudd** [comment]
Approved. This make sense to me. (see #611 comment).

**Comment by aaronjudd** [comment]
My bad for accepting this PR into development, causing a test to fail.
```
I20151230-08:36:16.076(-8)? jasmine-server-integration: 78 tests passed (6s)
W20151230-08:36:16.076(-8)? (STDERR) jasmine-server-integration: 1 tests failed
W20151230-08:36:16.076(-8)? (STDERR) cart methods cart items cart/removeFromCart should remove item from cart
W20151230-08:36:16.076(-8)? (STDERR) Error: Match error: Failed Match.OneOf or Match.Optional validation
W20151230-08:36:16.076(-8)? (STDERR) meteor://💻app/packages/check/match.js:33:1: Error: Match error: Failed Match.OneOf or Match.Optional validation
W20151230-08:36:16.076(-8)? (STDERR)   at check (meteor://💻app/packages/check/match.js:33:1)
W20151230-08:36:16.076(-8)? (STDERR)   at [object Object].Meteor.methods.cart/removeFromCart (meteor://💻app/server/methods/cart.js:259:5)
W20151230-08:36:16.077(-8)? (STDERR)   at maybeAuditArgumentChecks (meteor://💻app/livedata_server.js:1698:12)
W20151230-08:36:16.077(-8)? (STDERR)   at meteor://💻app/livedata_server.js:1611:18
W20151230-08:36:16.077(-8)? (STDERR)   at [object Object]._.extend.withValue (meteor://💻app/packages/meteor/dynamics_nodejs.js:56:1)
W20151230-08:36:16.077(-8)? (STDERR)   at [object Object]._.extend.apply (meteor://💻app/livedata_server.js:1610:45)
W20151230-08:36:16.077(-8)? (STDERR)   at [object Object]._.extend.call (meteor://💻app/livedata_server.js:1553:17)
W20151230-08:36:16.077(-8)? (STDERR)   at meteor://💻app/tests/jasmine/server/integration/cart.js:87:18
```

**Comment by newsiberian** [comment]
I've fixed this test. Should I create new PR for it, or maybe it will be better to add this changes to next big PR?

**Comment by aaronjudd** [comment]
go ahead and create a new PR and I'll add merge fixed test.

**Pull request merged**
