### PR TITLE
Email logs and email job queuing should check permissions

### LINKED ISSUE #3542: Dashboard settings panel opens for user without required permission
### Expected behavior
Users with dashboard access, but no permission for a dashboard setting can access the setting.
Example, a user without "email" permission, should not be able to see the Email settings in the dashboard.

### Actual behavior
A user with dashboard access is able to access the dashboard setting panel for a particular package even without having the needed permission(s). Example, a user without "email" permission, should not be able to see the Email settings in the dashboard.

### Steps to reproduce the behavior
- Create a test group (without "Email" permission). Add a user to that group.
- Login as the user, and call this in your browser console `ReactionCore.showActionView({"template":"emailSettings"})`. This is essentially the same way we open the side panel in the code.
- See that the email sidebar opened. (And you can even trigger a re-send for an email job).

screenshot_2018-01-22_19_25_22

Found while looking into #3091 and #3505. 
I'm thinking this can be solved by making `Reaction.showActionView` permissions-aware.

### Versions
Node: 8.9.1
NPM: 5.5.1
Meteor Node: 8.9.3
Meteor NPM: 5.5.1
Reaction CLI: 0.24.2
Reaction: 1.6.4
Reaction branch: master

### PR DESCRIPTION
**Pull request by prinzdezibel**
Closes #3542

- Prevent Jobs publication to send data to client if user has not email
permission
- Prevent emails from being queued for resending if user has no email permission.

### CODE REVIEW

**Comment by pmn4** [comment]
lgtm

**Comment by impactmass** [comment]
Posted a comment on the main issue #3542 to answer before we review this

**Comment by spencern** [comment]
Set the issue to `blocked` by #3542 per @impactmass comment

**Comment by prinzdezibel** [comment]
@impactmass @spencern : There's no dependency between this PR and  #3542. It shouldn't be labeled as blocked.

**Comment by prinzdezibel** [comment]
@spencern Seems like the ticket number's are transposed: It should be blocked because of #3542, not #3524.

**Pull request merged**
