### PR TITLE
Revert "Consideration for Marketplace Shops on Different URLs"

### PR DESCRIPTION
**Pull request by spencern**
Reports that this PR is causing the client to fail to load.

Reverts reactioncommerce/reaction#3332

### CODE REVIEW

**Comment by dancastellon** [comment]
@spencern This works for me - I'm no longer getting errors about client-side Reaction being undefined. I did some basic acceptance testing - clicking through the grid & tag pages, adding a product to cart, checking out. All works as expected.

**Comment by spencern** [comment]
@dancastellon thanks for the review.

**Comment by aldeed** [comment]
@spencern @dancastellon  Here is a PR that fixes the issues: https://github.com/reactioncommerce/reaction/pull/4471

We won't have to revert if we merge that.

**Comment by spencern** [comment]
Closed in favor of #4471

**Pull request closed without merging**
