### PR TITLE
Fix: Reaction font logo and email template logo

### PR DESCRIPTION
**Pull request by machikoyasuda**
- [x] Fixes: Updates Fontello font's `icon-reaction-logo` character to the updated logo
- [x]  Fixes: The resulting font is displayed in two places: the top of the admin nav bar and the dropdown Account menu
- [x] Fixes: Updates the `shop-logo.png` file used in the example e-mail templates. The resulting image is displayed in all email templates

- **Pre-release action required**: Need to update https://assets.reactioncommerce.com/fonts/fontello/ files with new files 

## results

Result: the old Reaction logo should no longer exist on the internet! 💥 

screen shot 2017-09-19 at 3 06 24 pm

### CODE REVIEW

**Comment by rymorgan** [comment]
old logo

**Comment by machikoyasuda** [comment]
@rymorgan Sorry Ryan I didn't make it clear -- The old logo will still show up until assets.reactioncommerce.com is updated. @jshimko is working on that part. Will let you know when it's able to test fully.

**Comment by machikoyasuda** [comment]
@rymorgan Ready to test now!

**Comment by rymorgan** [comment]
Hmmmm, it might be deeply cached. I know that's how favicons are. But i'm still seeing the old one, even after resetting my install. 

reaction-logo

**Pull request merged**
