### PR TITLE
Use Registered Schemas instead of Schema Source

### PR DESCRIPTION
**Pull request by pmn4**
## Allow for projects to modify Schemas

Creating a new database schema is simple enough, however, in order for the frontend to honor it (through Validation), we need a way for core components to use the updated schemas.
If core components refer to the Schema Registry instead of importing from the Schema definition files, this can be achieved.

Take, for instance, the `VariantFormContainer`. In it, [a `Validation` object is initialized](https://github.com/reactioncommerce/reaction/blob/master/imports/plugins/included/product-variant/containers/variantFormContainer.js#L24) using the `ProductVariant` schema.

If one were to add a field to the schema*, however, that Validation would reject changes to the new properties. (I understand that for this simple example, I could extend the Container and simply overwrite the constructor, but, you know, I'd rather not!).

If we replace:
``` JavaScript
import { ProductVariant } from "/lib/collections/schemas/products";
```
with 
``` JavaScript
import { Schemas } from "@reactioncommerce/reaction-collections";
const ProductVariant = Schemas.ProductVariant;
```
then a new `ProductVariant` schema can replace of the original, and the Container could remain untouched.

let me know what you think!

_(If you are comfortable with these changes, I will write some tests)_

---
 \* - assumption is that Schema changes use the `registerSchema` pattern to replace existing schemas, not monkey-patching the original schema.

### CODE REVIEW

**Comment by zenweasel** [comment]
@pmn4 I like the idea of this approach (essentially creating a global that can be overridden) but at first glance I wonder if all instance of schema use have been updated. I think pretty much every included plugin (at least all the ones that have settings) use a schema. So we would want to make sure that change is made everywhere.

**Comment by spencern** [comment]
This approach sounds reasonable, but I'm not certain it will be necessary after #2917 is finished.

Either way, we should wait to implement this until after @aldeed has finished the conversion to using the npm version of `simpl-schema`

**Comment by pmn4** [comment]
cool. looking forward to it!

**Comment by aldeed** [comment]
Yeah this overlaps the changes I've made, but I can rebase/adjust my branch. I've finished all changes I think, but I'm still investigating and resolving a few bugs that it created. Will hopefully have a PR in the next few days.

**Comment by spencern** [comment]
@pmn4 We're about ready to merge #2917 - once that happens will you verify if it resolves your needs or if we need to update and revisit this PR?

**Comment by aaronjudd** [comment]
@reactioncommerce/community @aldeed Closing this PR, we should re-open, re-review for 1.9 release

**Comment by zenweasel** [comment]
I wonder if this isn't superceeded by: https://github.com/reactioncommerce/reaction/issues/3494. I feel like that ticket covers what this PR is trying to accomplish?

**Comment by aldeed** [comment]
Agree that new schema extension model should address this

**Pull request closed without merging**
