### PR TITLE
Refactor: Remove Braintree plugin

### PR DESCRIPTION
**Pull request by ajporlante**
Impact: breaking
Type: **refactor**

## Issue
This plugin is included by default even though the vast majority of people will not be using it

## Solution
Move this plugin to [community namespace](https://github.com/reaction-contrib/meteor-braintree).

## Breaking changes
To continue to use this plugin after this change you will need to:

1. Clone this repo into `<reaction root>/imports/plugins/custom/`.
2. No additional changes should be required

### App works w/o plugin

1. `rm -rf node_modules`
2. `meteor npm install`
3. Start app
4. Ensure everything works as normal

### Community app works

1. `reaction reset -y`.
2. Start app and ensure Braintree is not available.
3. Clone this into `<reaction-root>/imports/plugins/custom/`.
4. `reaction reset -n`
5. Verify that Braintree works like before

### CODE REVIEW

**Comment by ajporlante** [comment]
Just noting here that I had to push 3 empty commits to trigger CI build because of failing integration tests that should actually pass.

**Comment by zenweasel** [comment]
@ajporlante We've got some conflict here now

**Comment by ajporlante** [comment]
@zenweasel Fixed the conflicts.

**Comment by zenweasel** [comment]
Still approved and ready to be merged pending passing tests

**Pull request merged**
