### PR TITLE
Pin transliteration package to 1.5.2 which doesn’t leak ES6 into bundle

### LINKED ISSUE #2090: Phantomjs / prerender.io render blank page
This is a port of a bug we had at GetOutfitted

### Expected behavior
prerender.io should be able to render and capture pages from the app.

### Actual Behavior
There's an ES6 javascript error 
```
[Error] SyntaxError: Unexpected use of reserved word 'let' in strict mode
(anonymous function) (f4aee29dfb6196571f0fb3982680e06d921b77b3.js , line 18)
```

### Steps to Reproduce the Behavior
Deploy stock reaction and use prerender.io

### PR DESCRIPTION
**Pull request by spencern**
This is an updated port of a fix for an issue we had at GetOutfitted and that I was able to replicate here. Fixes #2090.

The issue is that the `transliteration` npm package @1.5.3 leaks (is that a term?) ES6 code (`const` and `let`) into the bundle. Earlier versions of the transliteration npm package do not exhibit this behavior.

Here's a gif example. (that seems to have degraded since I created it.)
image

This also contains a fix for the issue where product and catalog pages are not getting rendered on prerender properly because they get rendered before the publications are finished. I can submit these as two separate PRs if desired.

### CODE REVIEW

**Comment by zenweasel** [comment]
@spencern Can you provide some "Steps to test" this PR?

**Comment by aaronjudd** [comment]
@spencern if we're downgrading, did we create an issue on the transliteration repo?  (or can you link to the issue?)

**Comment by spencern** [comment]
Good comments. 
Have not created an issue with `transliteration` yet, but I'll do that.

@zenweasel I'll get repro steps ironed out again. The easiest way to repro is to setup a local prerender server that caches a local Reaction instance, but I'll get the actual steps figured out.

**Comment by spencern** [comment]
From our convo today
[ ] Create issue in transliteration repo
[ ] Test to see if transliteration works for tags with v1.5.2

**Comment by spencern** [comment]
Took me too long, but I've finally got a reliable reproduction.

Reproduction steps.
1. Setup local `prerender` server
```
$ git clone https://github.com/prerender/prerender.git
$ cd prerender
$ npm install
$ PORT=1337 node server.js
```
2. Clone development branch of Reaction

3. Edit `/server/startup/prerender.js` file to look like this (Adds lines for using local prerender host)
```
import prerender from "prerender-node";
import { WebApp } from "meteor/webapp";
import { Logger } from "/server/api";

export default function () {
  if (process.env.PRERENDER_TOKEN && process.env.PRERENDER_HOST) {
    prerender.set("prerenderToken", process.env.PRERENDER_TOKEN);
    prerender.set("host", process.env.PRERENDER_HOST);
    prerender.set("protocol", "https");
    WebApp.rawConnectHandlers.use(prerender);
    Logger.info("Prerender Initialization finished.");
  } else { // Use local prerender host
    prerender.set("prerenderServiceUrl", "http://localhost:1337/");
    prerender.set("host", "localhost:3000");
    prerender.set("protocol", "http");
    WebApp.rawConnectHandlers.use(prerender);
    Logger.info("Prerender Localhost Initialized");
  }
}
```
4. run reaction in 'production' mode to build js bundle `$ reaction run --production`

5. Visit `localhost:1337/http://localhost:3000` (not a typo)
6. Visit `localhost:3000?_escaped_fragment_=

This will be a white screen and will not render the html of the page. That is the demonstration of the problem.

7. Checkout my branch `git checkout spencer-fix-prerender`
8. run `meteor npm install` to update npm dependencies (will revert `transliteration` to `1.5.2`)
9. edit `prerender.js` just like in step 3
10. Visit `localhost:1337/http://localhost:3000` (not a typo)
11. Visit `localhost:3000?_escaped_fragment_=

You should now see a prerendered, cached html version of the page.

I tested the transliteration that happens when creating a new tag as well, and it appears to still work.
```
{ "_id" : "APMXxR52RHgsARm5u", "name" : "中英字典", "slug" : "zhong-ying-zi-dian", "isTopLevel" : true, "updatedAt" : ISODate("2017-04-10T23:16:26.919Z"), "createdAt" : ISODate("2017-04-10T23:16:26.925Z"), "isDeleted" : false, "shopId" : "J8Bhq3uTtdgwZx3rz" }
```

**Comment by andyhu** [comment]
Just to let you know `transliteration` module has been upgraded to version `1.6.2` and this issue should be solved. I would appreciate if someone could test against the latest version of `transliteration`. Thanks!

**Comment by spencern** [comment]
Adding myself to this issue to check it out.

**Comment by spencern** [comment]
@andyhu This does _not_ appear to be fixed in `1.6.2`.

Here's an excerpt of the built .js file containing transliteration and the leaked es6 code.

```
transliteration:{"package.json":function(e,n){n.name="transliteration",n.version="1.6.2",n.main="lib/node/index.js"},lib:{node:{"index.js":["./transliterate","./slugify",function(e,n){"use strict";function t(e){return e&&e.__esModule?e:{default:e}}Object.defineProperty(n,"__esModule",{value:!0}),n.slugify=n.transliterate=void 0;var i=e("./transliterate"),a=t(i),o=e("./slugify"),r=t(o);n.transliterate=a.default,n.slugify=r.default}],"transliterate.js":["./utils","../../data/charmap.json",function(e,n){"use strict";function t(e){return e&&e.__esModule?e:{default:e}}Object.defineProperty(n,"__esModule",{value:!0}),n.replaceStr=void 0;var i=e("./utils"),a=e("../../data/charmap.json"),o=t(a);let r={};const u={unknown:"[?]",replace:[],replaceAfter:[],ignore:[],trim:!0};let s={};const l=n.replaceStr=((e,n)=>{let t=e;for(const e of n)e[0]instanceof RegExp?e[0].global||(e[0]=new RegExp(e[0].toString().replace(/^\/|\/$/),`${e[0].flags}g`)):"string"==typeof e[0]&&(e[0]=new RegExp((0,i.escapeRegExp)(e[0]),"g")),e[0]instanceof RegExp&&(t=t.replace(e[0],e[1]));return t}),c=(e,n)=>{const t=n?(0,i.mergeOptions)(u,n):(0,i.mergeOptions)(u,s);let a=String(e),d,p,h,g,f,m;if(t.ignore instanceof Array&&t.ignore.length>0)for(d in t.ignore){h=a.split(t.ignore[d]),g=[];for(p in h)f=t.ignore.slice(0),f.splice(d,1),g.push(c(h[p],(0,i.mergeOptions)(t,{ignore:f,trim:!1})));return g.join(t.ignore[d])}a=l(a,t.replace),a=(0,i.fixChineseSpace)(a);const y=(0,i.ucs2decode)(a),b=[];for(m of y)if(m>65535)b.push(t.unknown);else{const e=m>>8;void 0===r[e]&&(r[e]=o.default[e]||[]),m&=255;const n=r[e][m];void 0===n||null===n?b.push(t.unknown):b.push(r[e][m])}t.trim&&b.length>1&&t.replaceAfter.push([/(^ +?)|( +?$)/g,""]);let v=b.join("");return v=l(v,t.replaceAfter)};c.setCharmap=(e=>{return r=e||r}),c.config=(e=>{return void 0===e?s:s=(0,i.mergeOptions)(u,e)}),n.default=c}],"utils.js":function(e,n){"use strict";Object.defineProperty(n,"__esModule",{value:!0});const t=n.ucs2decode=(e=>{const n=[];let t=0;for(;t<e.length;){const i=e.charCodeAt(t++);if(i>=55296&&i<=56319&&t<e.length){const a=e.charCodeAt(t++);56320==(64512&a)?n.push(((1023&i)<<10)+(1023&a)+65536):(n.push(i),t--)}else n.push(i)}return n}),i=n.fixChineseSpace=(e=>e.replace(/([^\u4e00-\u9fa5\W])([\u4e00-\u9fa5])/g,"$1 $2")),a=n.escapeRegExp=(e=>{let n=e;return null!==n&&void 0!==n||(n=""),n.replace(/[\-\[\]\/\{\}\(\)\*\+\?\.\\\^\$\|]/g,"\\$&")}),o=n.mergeOptions=((e,n)=>{const t={},i=n||{};for(const n in e)if(t[n]=void 0===i[n]?e[n]:i[n],t[n]instanceof Array&&(t[n]=t[n].slice(0)),"replace"===n&&"object"==typeof t[n]&&!(t[n]instanceof Array)){const e=[];for(const n in t.replace)e.push([n,t.replace[n]]);t.replace=e}return t}),r=n.parseCmdEqualOption=(e=>{let n=e||{};const t="__REPLACE_TOKEN__";let i="__REPLACE_TOKEN__",a;for(;n.indexOf(i)>-1;)i+=i;return n.match(/[^\\]\\\\=/)?n=n.replace(/([^\\])\\\\=/g,"$1\\="):n.match(/[^\\]\\=/)&&(n=n.replace(/([^\\])\\=/g,`$1${i}`)),a=n.split("=").map(e=>e.replace(new RegExp(i,"g"),"=")),2!==a.length&&(a=!1),a})},"slugify.js":["./transliterate","./utils",function(e,n){"use strict";function t(e){return e&&e.__esModule?e:{default:e}}Object.defineProperty(n,"__esModule",{value:!0});var i=e("./transliterate"),a=t(i),o=e("./utils");const r={lowercase:!0,separator:"-",replace:[],replaceAfter:[],ignore:[]};let u={};const s=(e,n)=>{const t=n?(0,o.mergeOptions)(r,n):(0,o.mergeOptions)(r,u),i=(0,o.escapeRegExp)(t.separator);t.replaceAfter.push([/[^a-zA-Z0-9]+/g,t.separator],[new RegExp(`^(${i})+|(${i})+$`,"g"),""]);const s={replaceAfter:t.replaceAfter,replace:t.replace,ignore:t.ignore};let l=(0,a.default)(e,s);return t.lowercase&&(l=l.toLowerCase()),l};s.config=(e=>{return void 0===e?u:u=(0,o.mergeOptions)(r,e)}),n.default=s}]},browser:{"transliteration.min.js":function(e,n,t){!function n(t,i,a){function o(u,s){if(!i[u]){if(!t[u]){var l="function"==typeof e&&e;if(!s&&l)return l(u,!0);if(r)return r(u,!0)
```

Just search for `const ` and you'll see it.

**Comment by andyhu** [comment]
@spencern Probably you should test against /lib/browser/transliteration.js, ES6 code has been transpiled in that file

**Pull request merged**
