### PR TITLE
collapse expanded tag list in edit mode

### PR DESCRIPTION
**Pull request by nialexsan**
allows to collapse expanded tag list in edit mode
straightforward solution

### CODE REVIEW

**Comment by aaronjudd** [comment]
@nialexsan thanks for this PR. We're about to release 0.14.0, we'll review this after we're done with the release.

**Comment by aaronjudd** [comment]
@nialexsan if you can fix this linting error https://codeclimate.com/github/reactioncommerce/reaction/pull/1164  we can review this PR today.

**Comment by zenweasel** [comment]
@nialexsan I pulled this PR down to test but I guess I can't quite figure out what change I am supposed to be seeing. I'm not seeing what's different about editing tags. Can you give me a little more detail? Thanks.

**Comment by nialexsan** [comment]
@zenweasel in _imports/plugins/core/ui-tagnav/client/components/tagNav/tagNav.js:274_ there is an **if** statement, which resets the **selectedTag** value to **null** if gets the same object. This allows to close navbar's dropdown **tagtree** in edit mode by clicking the down arrow second time.
Hope my description is clear.

**Comment by zenweasel** [comment]
@nialexsan Sorry to be so stupid but I am still not getting it. Could you do a quick screenshot of the UI element you are talking about?

**Comment by nialexsan** [comment]
No problem, here you are
reaction

**Comment by zenweasel** [comment]
Approved. Works great.

**Comment by nialexsan** [comment]
One more thing, I completely forgot about another change made in this pull request! 
cancel button handling in 
_imports/plugins/core/layout/client/templates/layout/alerts/reactionAlerts.js_

disablepackage

**Comment by aaronjudd** [comment]
👍

**Pull request merged**
