### PR TITLE
Release 2.0.0 rc.5

### LINKED ISSUE #4574: GraphQL: Implement availablePaymentMethods query
Implement availablePaymentMethods query

### LINKED ISSUE #4718: Create enablePaymentMethodForShop mutation
## Work
Create a mutation that allows an admin to enable/disable a payment method for a shop. Create it in the "payments" core plugin.

### GraphQL schema
```graphql
"Input for the `enablePaymentMethodForShop` mutation"
input EnablePaymentMethodForShopInput {
  "An optional string identifying the mutation call, which will be returned in the response payload"
  clientMutationId: String

  "True to enable it or false to disable it"
  isEnabled: Boolean!

  "The name of the payment method to enable or disable"
  paymentMethodName: String!

  "The ID of the shop for which this payment method should be enabled or disabled"
  shopId: ID!
}

type EnablePaymentMethodForShopPayload {
  "The same string you sent with the mutation params, for matching mutation calls with their responses"
  clientMutationId: String

  "The full list of payment methods for the shop"
  paymentMethods: [PaymentMethod]!
}

extend type Mutation {
  enablePaymentMethodForShop(input: EnablePaymentMethodForShopInput!): EnablePaymentMethodForShopPayload!
}
```

### PR DESCRIPTION
**Pull request by spencern**
# v2.0.0-rc.5
This is our fifth **release candidate** for v2.0.0 of Reaction. Please check it out and let us know what works and what doesn't for you.

## Mongo replica set issue
Many people were having issues with the Mongo replica-set image starting before the Mongo database was ready. This could cause the replica-set to fail and the application to hang during startup in a development environment. This is fixed in #4748 by waiting for mongo to be reachable within the reaction container before connecting to it, and creating the DB if needed, initiating the replica set if needed, and waiting for the replica set to be OK. This fix should solve the docker-compose startup race conditions we've been seeing. (#4748)

## GraphQL
We've added two new GraphQL queries for payment methods. A query `paymentMethods` which will list all registered payment methods and is restricted to operators and `availablePaymentMethods` which will list all payment methods which have been enabled. These new queries were added in #4709. We've also added a GraphQL mutation that permits an operator to enable or disable a payment method for a shop in #4739

We've updated the CartItems and OrderItems GraphQL queries to include a `productTags` resolver which will return the tags for the CartItem or OrderItem. The new resolvers and updated schemas were added in #4715 and #4732

There is a new GraphQL mutation for generating sitemaps `generateSitemaps` this replaces the `sitemaps/generate` meteor method. method. (#4708)

## Classic Storefront UI Updates
We've replaced the customer facing Product Grid in the Classic Storefront UI with our [CatalogGrid](https://designsystem.reactioncommerce.com/#!/CatalogGrid) component from the Reaction Design System. This was accomplished in #4649

There's a new "Include in sitemap?" checkbox in the Product Settings when using the operator interface to edit product information. This was added to make it possible to exclude published products from the sitemap. (#4708)

## Additional Plugin Capabilities
A plugin can now include a `catalog` object in `registerPackage`, with `customPublishedProductFields` and `customPublishedProductVariantFields` that are set to arrays of property names. These will be appended to the core list of fields for which published status should be tracked. This is used to build the hashes that are used to display an indicator when changes need to be published. (#4738)

A plugin can now use the `functionsByType` pattern to register one or more functions of type "publishProductToCatalog", which are called with `(catalogProduct, { context, product, shop, variants })` and expected to mutate `catalogProduct` if necessary. (#4738)

## nvmrc
Even though most of the development work happens in Docker, getting the right version of node available directly in the host OS is convenient for setting up eslint integration with your editor. We've added an `.nvmrc` file for this as [we've recommended](https://docs.reactioncommerce.com/docs/recommended-tools#general) `nvm` for installing and managing NodeJS in our docs for some time now.

## Public API Changes
We've changed the GraphQL schema for `PaymentMethod@name` from `PaymentMethodName` to `String`. `PaymentMethodName` was a subset of string and this should not cause any issues.

## Breaking Changes
WE've replaced the `generateSitemaps` Meteor method with a GraphQL mutation. See #4708 for details.

Because we've replaced the customer facing Product Grid UI in the Classic Storefront UI, if you had any plugins which relied on specific selectors or the structure of the existing UI, those may need to be updated.

## Features
 - feat: payment methods (#4709) .. Resolves #4574
 - feat: enable payment method for shop (#4739) .. Resolves #4718
 - feat: use component library's CatalogGrid - 2.0 (#4649)
 - feat: add product tags to cart items (#4715)
 - feat: Add product tags to order item (#4732)
 - feat: option to choose whether a product should appear in the sitemap (#4708)
 - feat: add a way to extend catalog product publication (#4738)

## Fixes
 - fix: Auth Consent scopes issue (#4733)
 - fix: 4722 compareAtPrice - convert from Float to Money (#4731)
 - fix(startup): init mongo replica set after waiting for connection (#4748)

## Chores
 - chore: add .nvmrc configuration file (#4744)

## Docs
 - docs: Link readers to Reaction Platform install instructions (#4724)
 - docs: fix jsdoc copypasta on waitForReplica checkWaitRetry (#4723)

### CODE REVIEW

**Comment by spencern** [comment]
@jeffcorpuz I'll be updating the release notes here in a bit and then I think we can freeze rc.5 and release once you've approved.

**Comment by spencern** [comment]
@jeffcorpuz Release notes are updated. Should be good to go.

**Comment by spencern** [comment]
@jeffcorpuz Not sure what's going on with the Social Media Icons and the currencies. Will you file an issue for each of those? Do the currencies stay in that order after a refresh or just immediately after enabling?

**Comment by jeffcorpuz** [comment]
@spencern will do, added them as an issue. 
The currencies stay in that order after immediately enabling it and a refresh.

Social Media UI - https://github.com/reactioncommerce/reaction/issues/4756
Currencies Order - https://github.com/reactioncommerce/reaction/issues/4757

**Pull request merged**
