### PR TITLE
chore(Auth): update auth URLs for hydra 1.0.0

### PR DESCRIPTION
**Pull request by yashutanna**
Resolves: https://github.com/reactioncommerce/reaction-feature-requests/issues/112#issue-484468960
Impact: **minor**  
Type: **chore**

## Issue
This PR updates the auth URLs that were changed as part of the hydra project moving away from the 1.0.0-beta to the stable release

## Solution
change GET and PUT urls for login flow under the hydra plugin to conform to the expected url as specified [here](https://github.com/ory/hydra/blob/master/CHANGELOG.md#v100-2019-06-24)

## Breaking changes
this solution will only work if the reaction-hydra project has an update to use the stable version of hydra as opposed to the currently used 1.0.0-beta

## Testing
1. run `make`
2. navigate to the `docker-compose.yaml` of the reaction-hydra project
3. update image of hydra to `oryd/hydra:1.0.0`
4. run through authentication steps as usual

### CODE REVIEW

**Comment by aldeed** [comment]
@yashutanna We will look into merging this and updating Hydra requirement for the upcoming 3.0.0 release.

**Comment by yashutanna** [comment]
cool! do we have an ETA on that?

there is also a related PR [here](https://github.com/reactioncommerce/reaction-hydra/pull/28#issue-323708005)

**Comment by aldeed** [comment]
@yashutanna 3.0.0 RC 1 in a week or two I think.

**Comment by yashutanna** [comment]
@aldeed Ill try to make sure the PR stays aligned to master

**Comment by aldeed** [comment]
I have manually made these changes in the new identity app for 3.0

**Pull request closed without merging**
