### PR TITLE
Fix inventory tests

### PR DESCRIPTION
**Pull request by zenweasel**
When the cart fixture creates a cart it has several items each of which has a random quantity on it, usually in the 50-100 range. When you call `copyCartToOrder` each item gets broken out into an individual item. If you have larger quantities this takes a long time (too long for the test at least).

This change just reduces the cart down to a quantity of 1 which makes the test take less than 2 seconds.

This is probably a performance issue we should track. Also it would appear that collection-hooks are blocking?

### CODE REVIEW

**Comment by aaronjudd** [comment]
Still getting ```160805-07:54:17.253(-7)?   164 passing (19s)
I20160805-07:54:17.254(-7)?   7 pending
I20160805-07:54:17.254(-7)?   1 failing
I20160805-07:54:17.254(-7)?
I20160805-07:54:17.256(-7)?   1) Inventory Hooks should move allocated inventory to 'shipped' when an order is shipped:
I20160805-07:54:17.256(-7)?
I20160805-07:54:17.257(-7)?       AssertionError: expected 'new' to equal 'shipped'
I20160805-07:54:17.257(-7)?       + expected - actual
I20160805-07:54:17.257(-7)?
I20160805-07:54:17.257(-7)?       -new
I20160805-07:54:17.258(-7)?       +shipped```

**Comment by aaronjudd** [comment]
And again, it passed the second time I ran `reaction test`

**Comment by zenweasel** [comment]
I literally ran this 10 times in a row on my machine before submitting the PR and is passed every time.

**Comment by zenweasel** [comment]
@aaronjudd or anybody who has a moment, could you please run tests on this branch and double-check. Tests always pass for me locally and in CI.

**Comment by aaronjudd** [comment]
Same error as I originally reported, in retesting....

Second attempt succeeded, 3rd attempt failed..

```
I20160807-18:21:27.646(-7)?   ․․․․
I20160807-18:21:27.646(-7)?
I20160807-18:21:27.647(-7)?   164 passing (20s)
I20160807-18:21:27.647(-7)?   7 pending
I20160807-18:21:27.647(-7)?   1 failing
I20160807-18:21:27.647(-7)?
I20160807-18:21:27.650(-7)?   1) Inventory Hooks should move allocated inventory to 'shipped' when an order is shipped:
I20160807-18:21:27.650(-7)?
I20160807-18:21:27.650(-7)?       AssertionError: expected 'new' to equal 'shipped'
I20160807-18:21:27.650(-7)?       + expected - actual
I20160807-18:21:27.650(-7)?
I20160807-18:21:27.650(-7)?       -new
I20160807-18:21:27.651(-7)?       +shipped
I20160807-18:21:27.651(-7)?
I20160807-18:21:27.651(-7)?       at Assertion.assertEqual (packages/practicalmeteor_chai.js:1418:12)
I20160807-18:21:27.651(-7)?       at Assertion.ctx.(anonymous function) [as equal] (packages/practicalmeteor_chai.js:4058:25)
I20160807-18:21:27.651(-7)?       at Test.<anonymous> (imports/plugins/included/inventory/server/hooks/inventory-hooks.app-test.js:141:53)
I20160807-18:21:27.651(-7)?       at run (packages/practicalmeteor:mocha-core/server.js:34:29)
I20160807-18:21:27.652(-7)?       at Context.wrappedFunction (packages/practicalmeteor:mocha-core/server.js:63:33)
I20160807-18:21:27.652(-7)?       at run (packages/practicalmeteor:mocha-core/server.js:52:15)
I20160807-18:21:27.652(-7)?
```

**Comment by aaronjudd** [comment]
I so want to report good news :-( 

```
=> App running at: http://localhost:3000/
I20160807-21:09:56.530(-7)? Exception in delivering result of invoking 'orders/shipmentShipped': AssertionError: expected 'new' to equal 'shipped'
I20160807-21:09:56.530(-7)?     at Assertion.assertEqual (packages/practicalmeteor_chai.js:1418:12)
I20160807-21:09:56.531(-7)?     at Assertion.ctx.(anonymous function) [as equal] (packages/practicalmeteor_chai.js:4058:25)
I20160807-21:09:56.531(-7)?     at imports/plugins/included/inventory/server/hooks/inventory-hooks.app-test.js:142:55
I20160807-21:09:56.531(-7)?     at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1)


I20160807-21:10:07.576(-7)?   164 passing (21s)
I20160807-21:10:07.576(-7)?   7 pending
I20160807-21:10:07.577(-7)?   1 failing
I20160807-21:10:07.577(-7)?
I20160807-21:10:07.579(-7)?   1) Inventory Hooks should move allocated inventory to 'shipped' when an order is shipped:
I20160807-21:10:07.580(-7)?      Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
```

**Comment by zenweasel** [comment]
Ok, sorry but please pull and try again.

**Comment by aaronjudd** [comment]
```
I20160807-23:24:18.211(-7)?   164 passing (19s)
I20160807-23:24:18.211(-7)?   7 pending
I20160807-23:24:18.211(-7)?   1 failing
I20160807-23:24:18.211(-7)?
I20160807-23:24:18.214(-7)?   1) Submit payment should call Example API with card and payment data:
I20160807-23:24:18.214(-7)?      Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
I20160807-23:24:18.214(-7)?       at run (packages/practicalmeteor:mocha-core/server.js:52:15)
I20160807-23:24:18.214(-7)?       at Context.wrappedFunction (packages/practicalmeteor:mocha-core/server.js:63:33)
I20160807-23:24:18.215(-7)?       at run (packages/practicalmeteor:mocha-core/server.js:52:15)
```

**Comment by zenweasel** [comment]
The current version of the code has a longer timeout than the error shows: https://github.com/reactioncommerce/reaction/blob/b5b1b4e62cd1b0227b5ca65001bbc18c118d72a9/imports/plugins/included/example-paymentmethod/server/methods/example-payment-methods.app-test.js#L75-L75

Are you sure that's up to date?

**Comment by jshimko** [comment]
I don't ever get those failures.  Starting from scratch with these steps works every time...

```sh
reaction init -b brent-fix-issue-1003 issue1003
cd issue1003
reaction test
```

```sh
167 passing (46s)
7 pending
```

**Comment by aaronjudd** [comment]
```
cd /tmp
reaction init -b brent-fix-inventory-tests pr1254
cd pr1254
reaction test (passed)
reaction test (failed)
reaction test (failed)
cd ../
rm -rf pr1254
reaction init -b brent-fix-inventory-tests pr1254-2
cd pr1254-2
reaction test (failed)
reaction test (failed)
```

All tests that failed reported:

```
I20160810-12:12:02.084(-7)?   166 passing (22s)
I20160810-12:12:02.084(-7)?   7 pending
I20160810-12:12:02.085(-7)?   1 failing
I20160810-12:12:02.085(-7)?
I20160810-12:12:02.087(-7)?   1) Inventory Hooks should move allocated inventory to 'shipped' when an order is shipped:
I20160810-12:12:02.087(-7)?      Error: timeout of 5000ms exceeded. Ensure the done() callback is being called in this test.
```

**Comment by zenweasel** [comment]
So I don't know what else I can do with this. Since I can't replicate the issue I can't really fix it. I tried again for hours yesterday to replicate this and still could not.

**Comment by aaronjudd** [comment]
well, we're having a really hard time debugging or replicating what I'm seeing, so @zenweasel accepting and going with 
> I don’t think the fixes are worse than what’s in development already

**Comment by aaronjudd** [comment]
@jshimko up to you to approve and merge now.

**Comment by jshimko** [comment]
👍

**Pull request merged**
