### PR TITLE
Pass isConfirm when calling callback

### PR DESCRIPTION
**Pull request by zenweasel**
The problem was that refunds were not working for any payment method. This was because the confirmation alert was always returning `undefined`. @mikemurray informed me that a new version of Alerts had been rolled out and he had to patch this version to use callbacks.

I discovered that when calling the callback, `isConfirm` was not being passed in, which was why it was never `true`.

To Verify that this PR works:
Place an order.
Approve and Capture.
Issue a Refund and verify that it works.

### CODE REVIEW

**Comment by kieckhafer** [comment]
👍

**Comment by aaronjudd** [comment]
Tested with PaypalExpress, refunds are not being processed.

**Comment by aaronjudd** [comment]
Also this PR has the reverted layout in it.

**Comment by kieckhafer** [comment]
-1' d my +1. Misunderstood what payment platforms should and should not be working.

**Comment by aaronjudd** [comment]
It's my opinion that if refunds aren't working for a particular payment method, then we need to make that obvious in some way. Otherwise, my expectation is that refunds work for all payment methods.

**Comment by zenweasel** [comment]
@aaronjudd That's fair but I am not sure how that relates to this PR

**Comment by aaronjudd** [comment]
My comments don't generally need to relate to the specific PR.  However, that comment is to head off the comment that was sure to follow that some payment method doesn't actually support refunds yet.

**Comment by zenweasel** [comment]
@aaronjudd How does this PR have the reverted layout in it?

**Comment by aaronjudd** [comment]
Interesting, I actually rechecked that several times, but now it doesnt.  (Honestly). I'll re-review, I know this sounds hokey - but GH was being bad.

**Comment by aaronjudd** [comment]
👍  for the fixed popup sending working with refunds.  However the only service that I didn't have errors with was Stripe.

**Pull request merged**
