### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by faddat**
It works now :)!

### CODE REVIEW

**Comment by faddat** [comment]
would be good to make sure to use the environment variables to set your username & password,   usage example:

docker build -t reaction .
docker run reaction -e METEOR_EMAIL="youradmin@yourdomain.com" \
-e METEOR_USER="admin" \
-e METEOR_AUTH="password" \
--name reaction \
-t

**Comment by faddat** [comment]
will be uploading a second dockerfile later that has mongodb on the outside and a docker-compose.yml and a rancher-compose.yml that go along with it.

**Comment by aaronjudd** [comment]
Merged. Tested local with kitematic, worked for me. nice cleanup.

**Comment by aaronjudd** [comment]
well here's the bad news. this dockerfile isn't ready for our use because
- needs to expose env variables for scripting configuration of new reaction instances
- doesn't expose local mongo - (can't connect using localhost)
- doesn't build missing less themes (this goes away in meteor 1.2)

**Pull request merged**
