### PR TITLE
[Marketplace] Inviting someone to create a new shop or affiliate shop should automatically grant that user appropriate permissions when registered

### LINKED ISSUE #2186: [Marketplace] Inviting someone to create a new shop or affiliate shop should automatically grant that user appropriate permissions when registered
**Update - June 29**
This issue is about _inviting_ a user to create a _new shop_.
On the UI side, we should probably add a checkbox or similar for `[ ] New Shop` when inviting a new user.

If checked, the invite would then create a new shop - `shops/createShop`, and assign the newly created user as an "owner" of the new shop.

This issue is _related_ but not the same as #2187 which is focused on adding administrative users to your existing shop.

**Original Issue**
When an invite is created for someone to create a new Shop or Affiliate shop on a marketplace the invited user should automatically be granted appropriate group permissions once they have finished registering. This should take place such that when the user has created an account they can immediately start acting on their new shop.

Ideally this could be fulfilled with a token so that they can register with any method and not exclusively with the email address to which the invite as sent and still have their account granted appropriate permissions.

### PR DESCRIPTION
**Pull request by impactmass**
Resolves #2186 

How to Test:

* Pull and run this branch. Log in as Marketplace Owner.
* Setup your email config (if you don't have it)
* Go to Shop Settings in the dashboard. 
* Open the Invite Owner Form under the marketplace plugin section
* Fill the form (Use a valid email so you can follow the link that gets sent to register)
* Follow link in email and on completing the "reset password" form, check that the new account have access to dashboard actions for the new shop.

### CODE REVIEW

**Comment by spencern** [comment]
This is done more-or-less, but currently UI testing is blocked by #2605

**Comment by impactmass** [comment]
With the PR fix I opened for the passwordReset bug, (when merged) the block mentioned above will be removed. But there's another issue I just found. The SortableTable received some updates (I believe via this PR #2597), and that's throwing no data error with Accounts table. I'm taking a look into that too.

**Comment by spencern** [comment]
In light of the above comment, I'm re-adding [WIP] to this issue.

**Comment by spencern** [comment]
@impactmass any updates on this issue?

**Comment by impactmass** [comment]
@spencern I just removed the WIP few minutes ago. The marketplace got some new merges. i updated it with the new updates from Marketplace into it right now. I'm testing it out again while waiting for CI.

**Comment by impactmass** [comment]
@spencern you can test it out now

**Comment by spencern** [comment]
Seems that i18n isn't working in some places
image

gonna see if I can fix this quickly

**Comment by spencern** [comment]
Loads with primary shop as "active" after sign-in. I'll see if I can update that as well.

**Comment by impactmass** [comment]
The i18n issue is inconsistent. It shows up sometimes. Sometimes it doesn't. I tried digging in a little too, but no luck

**Comment by spencern** [comment]
Seems like something is wrong with the cart too

image

On a refresh, twice I've seen the cart icon spin forever

**Comment by zenweasel** [comment]
I think the `i18n` issue is in `development` as well: https://github.com/reactioncommerce/reaction/issues/2593

**Comment by spencern** [comment]
I didn't have a chance to work on the cart creation issue tonight but will jump on it first thing in the am.

**Comment by impactmass** [comment]
Thanks @spencern. I'll also dig into it, maybe I'll find a solution before you're back. (since it's best to get this merged as soon as possible, as other things depend on it)

**Comment by impactmass** [comment]
thanks @aaronjudd. Re the cart issue, my last commit fixed it (hence it wasn't happening for you). 
I just need to code review this with @spencern now

**Pull request merged**
