### PR TITLE
fix: Get product image uploads working again

### LINKED ISSUE #6298: Upload images - Runtime error
## Issue Description
When I try to create products, or upload any image I  receive an exception 

https://gist.github.com/dzirg44/d16f5cc84087cae8c2a47b7568531db4

## Steps to Reproduce

1. update  Development platform to the latest version
2. enter to the Admin ui
3. create product
4. upload image

## Possible Solution
https://github.com/reactioncommerce/reaction-file-collections/blob/master/packages/file-collections/src/common/FileCollection.js

### Versions
latest docker image versions or use development platform.

### PR DESCRIPTION
**Pull request by focusaurus**
- Fixes #6298 mostly by updating to dependencies with the fixes
  - @reactioncommerce/file-collections@0.9.3
  - @reactioncommerce/file-collections-sa-gridfs@0.1.4
  - @reactioncommerce/api-plugin-files@1.0.12
- Also switch to the node v14.15.0 docker-base images
  - Unclear if this is strickly required but yet again
    the sharp package native add-on compiling was failing with
    C dependency errors

Resolves #6298 
Impact: **minor**
Type: **bugfix**

## Issue

Uploading product images from within reaction-admin was failing consistently with a chain of errors originating deep within our file upload stack (file-collections, the upload server, and supporting code). See #6298 for more details but ultimately there was a nodejs stream object representing the write to gridfs, and code was calling `stream.destroy()`. The normal behavior for that is to emit an `"error"` event with no arguments. I believe that bit of code is functioning as designed. In the reaction code, we bound event listeners to this event but failed to handle the case when this event had to passed arguments.

## Solution

The fixes amounted to detecting these spurious error events and ignoring them, allowing things to proceed successfully.

## Breaking changes

None expected.

## Testing

1. Run reaction from this branch in dev mode
  - The release for this doesn't have a prod mode docker image yet, so we can only test the updated deps in dev mode
2. In reaction-admin, create a product and add images. It should work.

I've tested top-level product images and variants and they work.

### CODE REVIEW

**Comment by focusaurus** [comment]
Ah, I now see that DCO wants mailchimp email addresses. OK fixed that.

**Comment by focusaurus** [comment]
@mikemurray Do you know if this is CircleCI being slow?

```
 FAIL  tests/integration/api/queries/ping/ping.test.js
  ● Test suite failed to run

    MongoServerSelectionError: Server selection timed out after 30000 ms

      at Timeout._onTimeout (node_modules/mongodb/lib/core/sdam/topology.js:438:30)
```

**Comment by kieckhafer** [comment]
I am now able to upload an initial image with this PR, however, I am still running into an error when trying to duplicate a product that has an image on it. It seems related, but this is a good first step: https://github.com/reactioncommerce/reaction/issues/6310

**Comment by willopez** [comment]
Yup, seems like it. Ran test locally and they all completed successfully. Also tested uploading images and works! Great job!

**Review by willopez — DISMISSED** [review]
LGTM

**Comment by focusaurus** [comment]
I added another commit that hopefully will fix #6310 too. Tomorrow will look into CI timing out with mongo errors.

**Comment by willopez** [comment]
@focusaurus I have verified that duplicating variants with images works as expected.

**Comment by focusaurus** [comment]
CI is fixed with a new release of api-core.

**Review by willopez — APPROVED** [review]
LGTM

**Review by kieckhafer — APPROVED** [review]
👍  looks good, #6310 is fixed as well, nice work!

**Pull request merged**
