### PR TITLE
Add .reaction/ci/config.yml

### PR DESCRIPTION
**Pull request by aaronjudd**
- for Reaction Platform CI configuration

### CODE REVIEW

**Comment by aaronjudd** [comment]
@jshimko any revisions?

**Comment by jshimko** [comment]
No, this is good for now.  We're looking into implementing the branch based deployments, but I think that's going to need a few more days to get working right and I don't want to hold this up.

**Comment by spencern** [comment]
should we merge this into the `marketplace` or `release-1.5.0` branch as well?

**Comment by aaronjudd** [comment]
@spencern 👍  we should `git cherry-pick 52f71dc` into `release-1.5.0`

**Pull request merged**
