### PR TITLE
Products flattened data structure

### PR DESCRIPTION
**Pull request by newsiberian**
Hello, @tdecaluwe and I are introducing new way to work with products. This work is the result of the following [conversation](https://github.com/reactioncommerce/reaction/issues/150). The very beginning changelog could be found here: reactioncommerce/reaction-catalog#1.

So, the flattened multi schema – a way to keep documents with different schemas inside one collection. Combining with [ancestors data structure](https://docs.mongodb.org/manual/tutorial/model-tree-structures-with-ancestors-array/), we expect a speed boost from this approach. And, in my personal opinion, this is greatly simplified the logic of the products system.

There are a lot of changes that were done, so we need to test this PR carefully and a lot. To make flattened multi-schema works we [contributed changes](https://github.com/aldeed/meteor-collection2/pull/289) into `collection2` packages, but these changes so far hasn't approved and applied by **aldeed**. So, I hope, you help me to polish `collection2` changes to make it more appealing.

Perhaps the most daring change relates to Product publication. Currently we have all our products variants inside products docs. By getting products we have all in one. With flattened schema this is unbelievable. Instead of getting 10 product docs + 10 * 3-5-10 variants doc we fetch only 10 products docs. All data we need for `productGrid` we get via denormalization. Images we get via manipulations with `media.metadata.productId`. Also I like that we do computation only one time on write operation instead of every time on read operations. I've tested with 300 products in development branch vs this PR, and from the first glance this PR works a little bit better but still Blaze is the weak place.

Also, as a result of [this conversation](https://github.com/reactioncommerce/reaction/issues/719), the following logic was implemented for now:
> The original behavior was that if you had child variants, the top level variant would display the sum of all the child variants.

Here is a approximate changelog:

#### ancestors: Array
new field which contains ancestors of item. Currently it could be one or two `_ids`

#### parentId
**Removed**

#### cloneId
**Removed**

#### index: Number
Previously was a String. Since implementing of flattened model this property is used for keeping array index. This is needed for moving variants through list (i.e. drug'n'drop).

#### minOrderQuantity: Number
Minimum order quantity. It is used inside cart `quantityProcessing` function. This change somehow covers #225.

#### shopId: String
We need it.

#### ancestors: Array
For a product – ancestors array is always clean for now.

#### cloneId
**Removed**

#### variants
**Removed**

#### price: String
Keep in mind – this is a string. It is needed for denormalizing variants prices to display it in `productGrid`.

#### isLowQuantity: Boolean
Indicates when at least one of variants `inventoryQuantity` are lower then their `lowInventoryWarningThreshold`.

#### isSoldOut: Boolean
Indicates when all variants' `inventoryQuantity` is zero

#### isBackorder: Boolean
Indicates when the seller has allowed the sale of product which is not in stock

#### shopIdAutoValue
Method was modified. Now it ignores update operations.

## Methods

Removed a lot of lines with `this.unblock()` after I read what it does)) Please, read [this part of guide](http://guide.meteor.com/methods.html#methods-vs-rest), and [few](https://kadira.io/academy/meteor-performance-101/content/managing-waittime) [articles](https://meteorhacks.com/understanding-meteor-wait-time-and-this-unblock.html#why-thisunblock-does-not-always-work) from Kadira. I think this should be a fine tunning tool with understanding that putting it here really do not have any side effects. It is really dangerous to put it in almost every method, like I did before)

### Products

Almost all methods were rewritten. Some were removed.

##### products/cloneVariant
now accept only two arguments: `productId(String), variantId(String)`

#### products/createVariant
if we are inserting a child variant, we ran an additional function `flushQuantity()` which clean parent quantity and inventory records.

#### products/updateVariant
This method now is used only in one place – top-level variant autoform. It calls `denormalize` function to keep product denormalized fields up to date.

#### products/updateVariants
**Method removed** It is not needed anymore. It was used to manage UI sorting stuff. Now `products/updateVariantsPosition` do this. It updates only `index` field.

#### products/deleteVariant
Also fires `denormalize` function

#### products/cloneProduct
Now this method is really working as expected. It supports top-level variants and options media cloning.

#### products/updateProductField
Now work with all type of items. It also fires `denormalize` function.

#### products/updateVariantsPosition
**New Method** It updates top level variant position index (while UI sorting).

#### cart/copyCartToOrder
Now fires `orders/inventoryAdjust` method.

#### inventory/register
`batchInsert` package was removed. Method now used native `bulkOp`

#### inventory/backorder
Now use `bulkOp`

## Collections
`ReactionCore.Helpers.cartTransform` was refactored. All computations were moved to `getSummary` function.

## Hooks
* `ReactionCore.Collections.Products.before.update` renamed into `ReactionCore.Collections.Products.after.remove`
* added `ReactionCore.Collections.Products.after.insert` which previously was `modifier.$push` of `after.update`

## Functions
Template products helpers got a lot of changes. Besides, some of them we now using on server side,  so the idea is to move part of this methods to `/common` folder to global variable (`ReactionCore`) and after 1.3 make them export/imported.

#### getProductPriceRange
no need to describe

#### getVariantPriceRange
the same

#### getVariantQuantity
**New method** It calculates a sum of descendants `inventoryQuantity`.

#### getVariants
**New method** Get all parent variants.

#### getTopVariants
**New method** Get only product top level variants

#### denormalize
Function denormalized variants fields to product.

#### isSoldOut
We are stop accepting new orders if product marked as `isSoldOut`.

#### isLowQuantity
If at least one of the variants is less than the threshold, then function returns `true`.

#### isBackorder
Indicates, is product variants is still available to be ordered after summary variants quantity became zero.

#### flushQuantity
if variant `inventoryQuantity` not zero, function update it to zero. This needed in case when the option with it's own `inventoryQuantity` is created inside top-level variant. In that case top-level variant should display sum of his options `inventoryQuantity` fields.

## How to run
You need four packages to run this.
[collection2](https://github.com/newsiberian/meteor-collection2) branch `master`
[collection2-core](https://github.com/newsiberian/meteor-collection2-core) branch `flattened`
[reaction-factories](https://github.com/newsiberian/reaction-factories) branch `flattened`
[reaction-catalog](https://github.com/reactioncommerce/reaction-catalog) branch `master`

I would like to attract attention of @spencern because he use Reaction in production, and there are a lot of changes here.

### CODE REVIEW

**Comment by aaronjudd** [comment]
I'd like to think about merging all this in v0.13 but we need a really detailed testing plan for this. We need to think about ways of merging this working is going to take some time.

**Comment by newsiberian** [comment]
Totally agree, also I think, we should wait to what **aldeed** do with `collection2` changes.

**Comment by newsiberian** [comment]
- product helper `globals.js` renamed to `global.js`, because we already have a file with such name
and it is ultra difficult to debug files with the same path and name;
- fixed `enable` button in dashboard package;
- in PDP from now `title` will be show to users, not `optionTitle`;
- **Temporary added `collection2` forks to packges** to make it easy access to people;
- `reaction-catalog` also **moved to packages folder**;

**Comment by spencern** [comment]
I'm not sure how I missed this until today, but after a quick overview, it seems like this simplifies a lot of the complexity surrounding products, variants, and inventory management. I'll start watching this issue more closely, and echo the sentiment that great test coverage will be essential before a merge. 

Is the `collection2` merge just waiting on tests as well or are there other issues there?

**Comment by aaronjudd** [comment]
@spencern I mentioned to @aldeed, hopefully he'll get time to review the PR that @newsiberian has pending this week. I think that's our primary blocker right now.

**Comment by zenweasel** [comment]
I've started adding "acceptance tests" to the reaction-doc repo. If the idea of writing automated tests seems daunting we could start by writing a few simple manual tests that would just mimic how you are testing this as you develop. Then these tests can be part of the acceptance suite that we do before a release. Just a suggestion.

**Comment by zenweasel** [comment]
We reviewed this PR in the weekly meeting and it's ready to be merge pending:

1. Merge to `collections2` repo (see note above)
2. Test plan
3. Resolution of conflict.

I am willing to work on a test plan with somebody if they want some help.

**Comment by aaronjudd** [comment]
Merge to collections2 repo has been added now.

**Comment by newsiberian** [comment]
> Test plan

added.

**Pull request merged**
