### PR TITLE
Fix for eslint-import-resolver-meteor should go to dev-dependencies 

### LINKED ISSUE #4041: eslint-import-resolver-meteor should go to dev-dependencies
## Prerequisites
* [x] Are you running the latest version?
* [x] Are you able to consistently reproduce the issue?
* [x] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description
In release-1.10.0, the package `eslint-import-resolver-meteor`is listed in "dependencies", but presumably it should be in "devDependencies"

## Steps to Reproduce
https://github.com/reactioncommerce/reaction/blob/release-1.10.0/package.json

### PR DESCRIPTION
**Pull request by prinzdezibel**
Resolves #4041  
Impact: **minor**  
Type: **bugfix**

## Issue
In release-1.10.0, the package eslint-import-resolver-meteoris listed in "dependencies", but presumably it should be in "devDependencies"

See:  https://www.npmjs.com/package/eslint-import-resolver-meteor

## Breaking changes
none

### CODE REVIEW

**Comment by spencern** [comment]
@prinzdezibel 
When we update package.json, we need to make sure that `meteor npm install` is run after so our `package-lock.json` file gets updated. 

I'll update this one.

**Comment by prinzdezibel** [comment]
@spencern thank you! I forgot that.

**Comment by spencern** [comment]
@prinzdezibel Looks like there are some issues that this is introducing when attempting to update the `package-lock.json` file. Specifically, it seems to be loading an outdated beta version of Babel 7. I don't have time to check into this right now, so this may slip to 1.12 or a patch version of 1.11

**Comment by prinzdezibel** [comment]
@zenweasel  May I assign this one to you? I didn't find time to look into this one again. Thanks.

**Comment by zenweasel** [comment]
Replaced by #4180

**Pull request closed without merging**
