### PR TITLE
Fix for error: moment is not a function.

### LINKED ISSUE #3778: Error on adding address, moment is not a function.
Unexpected error in add.js prevents new address/checkout.

### Expected behavior
To be able to add an address.

### Actual behavior

You cannot.

basic_reaction_product_and_slack_-_reaction_commerce_and_reactioncommerce_reaction__reaction_is_a_customizable__real-time_reactive__javascript_commerce_platform_

```
  An error occurred adding the address TypeError: moment is not a function
      at cartToSalesOrder (imports/plugins/included/taxes-avalara/server/methods/taxCalc.js:392:20)
      at Object.taxCalc.estimateCart (imports/plugins/included/taxes-avalara/server/methods/taxCalc.js:471:42)
      at MethodInvocation.MethodHooks.after.options (imports/plugins/included/taxes-avalara/server/hooks/hooks.js:28:13)
      at _each (server/api/
```

### Steps to reproduce the behavior

Attempt to checkout.  In my case, Avalara, Shippo as well.

### Versions

Node: 8.9.3
NPM: 5.6.0
Meteor Node: 8.9.4
Meteor NPM: 5.6.0
Reaction CLI: 0.27.0
Reaction: 1.8.0
Reaction branch: release-1.8.0
Docker: 17.12.0-ce

### PR DESCRIPTION
**Pull request by prinzdezibel**
Resolves #3778 ,   #3780
Impact: critical
Type: bugfix

## Issue
When doing checkout with avalara enabled an error happens when entering the address.

## Solution

Moment.js exposes its API on module level, not via default object.

The fix was applied to all files where it was imported wrong.

So instead of
```
  const moment = import("moment").default
```
the correct way  would be
```
  const moment = import("moment")
```

## Breaking changes
none expected

## Testing
1. As an admin enable Avalara in the backend
2. As a user, add an item to basket and check out
3. You should be able to enter the address successfully without error

### CODE REVIEW

**Comment by spencern** [comment]
This resolved #3778 for me, but I haven't tested any of the other sections.

**Comment by kieckhafer** [comment]
I am seeing this error when trying to checkout with Braintree:

```
ERROR Reaction: Maximum call stack size exceeded
  RangeError: Maximum call stack size exceeded
      at Array.forEach (<anonymous>)
      at Object.EJSON.clone.v [as clone] (packages/ejson/ejson.js:594:18)
      at Object.keys.forEach.key (packages/ejson/ejson.js:595:22)
      at Array.forEach (<anonymous>)
      at Object.EJSON.clone.v [as clone] (packages/ejson/ejson.js:594:18)
      at Object.keys.forEach.key (packages/ejson/ejson.js:595:22)
      at Array.forEach (<anonymous>)
      at Object.EJSON.clone.v [as clone] (packages/ejson/ejson.js:594:18)
      at Object.keys.forEach.key (packages/ejson/ejson.js:595:22)
      at Array.forEach (<anonymous>)
      at Object.EJSON.clone.v [as clone] (packages/ejson/ejson.js:594:18)
      at Object.keys.forEach.key (packages/ejson/ejson.js:595:22)
      at Array.forEach (<anonymous>)
      at Object.EJSON.clone.v [as clone] (packages/ejson/ejson.js:594:18)
      at Object.keys.forEach.key (packages/ejson/ejson.js:595:22)
      at Array.forEach (<anonymous>)
      at Object.EJSON.clone.v [as clone] (packages/ejson/ejson.js:594:18)
      at Object.keys.forEach.key (packages/ejson/ejson.js:595:22)
      at Array.forEach (<anonymous>)
      at Object.EJSON.clone.v [as clone] (packages/ejson/ejson.js:594:18)
      at Object.keys.forEach.key (packages/ejson/ejson.js:595:22)
      at Array.forEach (<anonymous>)
      at Object.EJSON.clone.v [as clone] (packages/ejson/ejson.js:594:18)
      at Object.keys.forEach.key (packages/ejson/ejson.js:595:22)
      at Array.forEach (<anonymous>)
      at Object.EJSON.clone.v [as clone] (packages/ejson/ejson.js:594:18)
      at Object.keys.forEach.key (packages/ejson/ejson.js:595:22)
      at Array.forEach (<anonymous>)
      at Object.EJSON.clone.v [as clone] (packages/ejson/ejson.js:594:18)
      at Object.keys.forEach.key (packages/ejson/ejson.js:595:22)
      at Array.forEach (<anonymous>)
      at Object.EJSON.clone.v [as clone] (packages/ejson/ejson.js:594:18)
      at Object.keys.forEach.key (packages/ejson/ejson.js:595:22)
      at Array.forEach (<anonymous>)
      at Object.EJSON.clone.v [as clone] (packages/ejson/ejson.js:594:18)
      at Object.keys.forEach.key (packages/ejson/ejson.js:595:22)
      at Array.forEach (<anonymous>)
      at Object.EJSON.clone.v [as clone] (packages/ejson/ejson.js:594:18)
      at Object.keys.forEach.key (packages/ejson/ejson.js:595:22)
      at Array.forEach (<anonymous>)
```

I am not seeing this error on the `release-1.8.0` branch.

**Comment by prinzdezibel** [comment]
@kieckhafer I can reproduce this error in release-1.8.0 branch as well. I don't think it has to do with this PR.

**Comment by prinzdezibel** [comment]
@kieckhafer Filed a separate ticket for the above ticket: https://github.com/reactioncommerce/reaction/issues/3786

**Comment by zenweasel** [comment]
@prinzdezibel I can reproduce this error on this branch but not on `release-1.8.0`

**Comment by prinzdezibel** [comment]
Merged release-1.8.0 in again. Please try again.

**Comment by spencern** [comment]
@zenweasel @prinzdezibel I'd like to get this PR merged as it solves several open tickets, let's get some solid reproduction steps for this issue if it's consistently happening on this branch so we can resolve it.

**Comment by kieckhafer** [comment]
I am no longer seeing the `call stack` error after the latest merge.

**Comment by zenweasel** [comment]
@kieckhafer Thanks!

**Pull request merged**
