### PR TITLE
Marketplace merge development

### PR DESCRIPTION
**Pull request by spencern**
Merges latest development into Reaction

### CODE REVIEW

**Comment by zenweasel** [comment]
I suspect problems with the shop switcher, etc. are already known so I am ignoring.

**Comment by spencern** [comment]
What problems did you have with the shop switcher?

**Comment by zenweasel** [comment]
When I select "blank site" from the switcher I got a bunch of errors

**Comment by spencern** [comment]
oh, hmm. I actually haven't done much with the default second site, so I can check on that, but I don't think it's been introduced in this merge, so approval seems okay still.

**Comment by spencern** [comment]
CircleCI is finished and passed, not sure why it's saying queued still. Merging.

**Pull request merged**
