### PR TITLE
Show products that fail validation when publishing.

### PR DESCRIPTION
**Pull request by jm-wanja**
Resolves issue #2690 

Previously we could identify which products are missing the label when publishing, the red button shows which products are missing the label.

**How to Test**

1. Login as Admin
2. Create a product but leave "Label" blank
3. Navigate to the product grid
4. Hit "Publish All"
5. Observe that the products don't publish, and there is a red button as an indicator of which product it is that needs changes. 
6. When the problem product is opened, observe that the `edit variant` panel is also opened and the label field flashes red to notify that the label is missing.

### CODE REVIEW

**Comment by zenweasel** [comment]
@jm-wanja This PR could use a better name?

**Comment by zenweasel** [comment]
So this works fine for just checking that the label exists but we want to flag any product that fails Simple Schema validation as I mentioned. So you will want to loop around where you are just checking the label length and call `isValid()` on the product and flag any product for which that is false. You can see the documentation for that here: https://github.com/aldeed/meteor-simple-schema#validating-data

**Comment by jm-wanja** [comment]
@zenweasel I have made the requested changes. This now flags the products missing the variant label by calling `isvalid()`.

**Comment by zenweasel** [comment]
So testing this it works fine. I wish it would take you to exactly what was broken (e.g. open the variant details panel when that's where the problem is) but that's probably beyond the scope of this ticket.

If we can just rename the variables/functions so they properly reflect what they are doing now then we should be able to merge.

**Comment by rymorgan** [comment]
@jm-wanja @zenweasel I absolutely agree/think is critical that it should open panel/card and highlight the field specific label that is missing. This has become a pretty major UX issue.

**Comment by jm-wanja** [comment]
@rymorgan @zenweasel in the case of multiple products missing the variant label field how can we handle opening the variant form on each product?

**Comment by zenweasel** [comment]
@jm-wanja I think he means when you click on the product, that the PDP show what fields are invalid

**Comment by rymorgan** [comment]
@zenweasel Yes! I do mean that. It can be a different PR if need be, but I think that would greatly help with something that's confusing to a lot of our users.

**Comment by jm-wanja** [comment]
@rymorgan Is an inline alert needed or is opening the panel with the fields that is invalid and highlighting it enough? @zenweasel

**Comment by zenweasel** [comment]
@jm-wanja I think opening the correct panel and showing the validation would be enough for now.

**Comment by zenweasel** [comment]
Just remember that it's not just missing label that could cause the validation error. We need to handle any sort of validation error.

**Comment by jm-wanja** [comment]
Alright, so currently this PR opens the edit variant panel when there is a validation error from a product variant. Also it flashes red on the field that is causing the error. This only works for fields on the product variant that are causing the validation error. @zenweasel @rymorgan

**Comment by rymorgan** [comment]
@jm-wanja The validation on PDP isn't working for me. I made a different issue for the PDP label part. 

The missing label indicator on the grid seems to be working. So it might make sense to address the other issue in a different PR. @zenweasel that make sense?

**Comment by rymorgan** [comment]
Ok, I take the previous comment back. I see that it does work. But it only works in the specific instance that: 
You create a product
Navigate to the grid
Publish product from the grid
Click back through product and you get the error 

So it's solving only one small fraction of the underlying issue. But again, I think we can address that in another issue.

**Comment by zenweasel** [comment]
So I think if this PR:

1. Shows the red dot on products that fail schema validation in the product grid

I feel like it meets the criteria for the issue it's trying to solve. Handing how validation should be displayed in the PDP is super important but there are multiple open issues for that already.

In retrospect I should have removed the word "label" from the issue description to make it clearer that this should be all schema validation and not just missing labels.

**Comment by zenweasel** [comment]
The Sold Out indicator overlaps with the status but @rymorgan has already noted that here: https://github.com/reactioncommerce/reaction/issues/2801
reaction

**Comment by zenweasel** [comment]
I would like to do more with improving this UI and experience but it's beyond the scope here. After discussion with @rymorgan we decided to open a separate issue as this requires planning and resources. https://github.com/reactioncommerce/reaction/issues/2865

This works as expected for the original intent.

**Pull request merged**
