### PR TITLE
Correct typo in schema. Says Shop but I think it means User

### PR DESCRIPTION
**Pull request by zenweasel**

### CODE REVIEW

**Comment by aaronjudd** [comment]
actually the label only shows up when errors are in the console, and because almost every collection has "shopId", I made the labels read  `label: "Accounts ShopId"`so that when you see the errors you know which collection is failing (because otherwise the errors don't tell you enough detail).  Looks like the label was on the wrong property (ie userId vs shopId).

**Comment by zenweasel** [comment]
Oh, ok. I will correct the correction.

**Comment by aaronjudd** [comment]
@zenweasel you can just commit update to this PR..

**Comment by aaronjudd** [comment]
Maybe we should close this one?  I can update quicker than trying to fix this merge.

**Comment by zenweasel** [comment]
Fine by me.

**Pull request closed without merging**
