### PR TITLE
(refactor) use Events.Hooks instead of meteor collection hooks for cart events that trigger discount calculations

### PR DESCRIPTION
**Pull request by willopez**
Resolves: [3635](https://github.com/reactioncommerce/reaction/issues/3635)
Impact: Minor
Type: Refactor

## Issue
The cart uses hooks from `meteor-collection-hooks` package, this package will be removed.

## Solution
Convert cart collection hooks to use Reaction's [Hooks.Events](https://blog.reactioncommerce.com/reaction-architecture-events/). 

## Breaking changes
none

## Testing Instructions
Discounts
- Set a discount code and discount amount, a value of 10 would translate to 10% off
- Add a product to the cart
- checkout and apply the discount code
- Finish checkout and verify order confirmation email shows the discount.

Adding items to cart
- Add an item to the cart
- Verify the corresponding inventory document has its workflow field set to `reserved`

Removing item from cart
- Add item to cart 
- Remove item from cart
- Verify the corresponding inventory document has its workflow field set to `new`

### CODE REVIEW

**Comment by willopez** [comment]
@mikemurray issues fixed.

**Comment by willopez** [comment]
@mikemurray I believe I got all the bugs squashed 🐛

**Comment by impactmass** [comment]
@mikemurray maybe the restocking issue might be the same reported in #3678?

**Comment by mikemurray** [comment]
@willopez @impactmass yes this seems to be the same issue I'm seeing. I will continue to test the discounts and note that ticket in the final review.

@willopez no action required at the moment.

**Pull request merged**
