### PR TITLE
Update Apollo-related packages

### LINKED ISSUE #4976: Apollo's core-js dependency breaks Reaction on start-up
## Prerequisites
* [x] Are you running the latest version?
* [x] Are you able to consistently reproduce the issue?
* [x] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description
When starting `reaction` from scratch (with empty volumes), `apollo-server` version `2.3.1` will fetch the latest beta of `core-js` which is missing `core-js/proposals/array-flat-and-flat-map`.

On start-up, you'll get the following error message:

```
Error: Cannot find module 'core-js/proposals/array-flat-and-flat-map'
```

More information on [this `apollo-tooling` issue](https://github.com/apollographql/apollo-tooling/issues/962).

## Steps to Reproduce
Please provide starting context, i.e. logged in as a user, configure a particular payment method.
1. From your `reaction-platform` directory, do a `make clean`
2. `make init`
3. See the error pop up in the logs for `reaction_reaction_1`

## Possible Solution
Update `apollo-server` and related packages to their latest versions.

### Versions
```
Node: 8.15.0
NPM: 6.4.1
Meteor Node: 8.11.4
Meteor NPM: 6.4.1
Reaction CLI: 0.29.0
Reaction: 2.0.0-rc.9
Reaction branch: outgrow-apollo-update
Docker: 18.09.1
```

### PR DESCRIPTION
**Pull request by loan-laux**
Resolves #4976  
Impact: **major**  
Type: **chore**

## Issue
When starting `reaction` from scratch (with empty volumes), `apollo-server` version `2.3.1` will fetch the latest beta of `core-js` which is missing `core-js/proposals/array-flat-and-flat-map`.

On start-up, you'll get the following error message:

```
Error: Cannot find module 'core-js/proposals/array-flat-and-flat-map'
```
More information on [this `apollo-tooling` issue](https://github.com/apollographql/apollo-tooling/issues/962).

## Solution
The right version of `core-js` was pinned in the latest version of Apollo. Updating `apollo-server` and related packages to their latest versions should fix the issue.

## Breaking changes
None AFAIK.

## Testing
1. `cd` to your `reaction-platform` directory
2. `make clean && make init`
3. `docker logs -f reaction_reaction_1`
4. See that `reaction` starts up fine

### CODE REVIEW

**Comment by loan-laux** [comment]
Looks like build failed because of a Snyk authentication issue?

**Comment by loan-laux** [comment]
Force-push mentioned above was to make DCO happy. :)

**Comment by aldeed** [comment]
@loan-laux This is good but can you merge latest `develop` branch in? That should fix all of the conflicts and checks.

**Comment by loan-laux** [comment]
@aldeed I just tried again on a fresh install, and it seems like this has been taken care of recently. We can skip that PR. 👍

**Pull request closed without merging**
