### PR TITLE
Added UI Slider onSlide event

### PR DESCRIPTION
**Pull request by lcampanis**
Added onSlide event for the newly contributed component

### CODE REVIEW

**Comment by mikemurray** [comment]
Could you also add some docs on the onSlide event to our docs? https://github.com/reactioncommerce/reaction-docs/blob/release-0.19.0/developer/components/slider.md

We have a 0.19.0 branch there you can make a quick PR to.

**Comment by lcampanis** [comment]
@mikemurray you got me there.. Docs are ready now, could I have access to push please. Thanks!

**Comment by mikemurray** [comment]
Access granted!

**Comment by lcampanis** [comment]
All updated https://github.com/reactioncommerce/reaction-docs/pull/154 Thanks!

**Pull request merged**
