### PR TITLE
Fix issue #3179: React.PropTypes is deprecated 

### PR DESCRIPTION
**Pull request by josx**
Fix issue #3179 

All RC code havent to use React.PropTypes becase are deprecated, If not Will no work on React >= 16
Check https://reactjs.org/blog/2017/04/07/react-v15.5.0.html#migrating-from-react.proptypes

### CODE REVIEW

**Comment by spencern** [comment]
@mikemurray any reason we shouldn't merge this?

**Comment by zenweasel** [comment]
There was a reason I didn't change this when I converted these over. May have something to do with translations? Let's just make sure and test before we merge.

**Comment by zenweasel** [comment]
Gave this a quick once-over and not seeing any problems so 😅

**Comment by spencern** [comment]
@mikemurray can you give this a review soon?

**Pull request merged**
