### PR TITLE
Expandable cards

### LINKED ISSUE #1455: [PDP] Revisions UX updates
Implement remaining UX update for https://github.com/reactioncommerce/reaction/pull/1356
- [x] move revisions dashboard card into Catalog card  (and i18n update) **PR** #1544
- [x] updated "Loading" spinner (should be universal) **PR** #1471
- [x] UX move delete button to same row (shouldn't need row to be active to delete)
- [x] UX to collapse accordions, focus edit target and open **PR** #1569
- [x]  Reimplement a confirmation UX when updating inputs (formerly turned green and fade on success) **PR** #1558
- [x] Ensure all inputs have placeholders **PR** #1472, #1542

### PR DESCRIPTION
**Pull request by mikemurray**
Resolves #1455 

PDP admin panel now has expandable cards with selecting fields to edit
from PDP page.

### CODE REVIEW

**Comment by zenweasel** [comment]
When testing this, on first start after reset I get this error:
```
TypeError: Cannot read property 'getElementsByTagName' of null(…)
```
and the page stays stuck here:
example-product

**Comment by zenweasel** [comment]
Removed previous comment because error is occurring on the main `release-0.18.0` branch as well.

**Comment by kieckhafer** [comment]
Having an issue where anytime I start to type in any field, ALL of the expanded cards immediately collapse. The data looks to still be there when I reopen them.

collapsing panel mov

**Comment by kieckhafer** [comment]
:+1: looks good to me

**Pull request merged**
