### PR TITLE
Fix #3652 Publish shops of user

### LINKED ISSUE #3652: Error in browser console when opening a Shop Manager invitation
### Expected behavior
No errors in console

### Actual behavior
Receive a chain of errors all similar to this:
```

meteor.js?hash=cbcc712d51de4298c275e8dcf25c66c29914f19a:992 TypeError: Cannot read property 'name' of undefined
    at TagNav.renderShopSelect (tagNav.js:67)
    at TagNav.render (tagNav.js:108)
    at modules.js?hash=e9468052767b9b2f8210b4edd369da11ea62eda7:141572
    at measureLifeCyclePerf (modules.js?
```

### Steps to reproduce the behavior
1. Login as admin and enable Marketplace
1. Invite a user
1. Using Incognito to open the link in the invitation
1. Observe errors in browser console

### Versions
```
Node: 8.9.1
NPM: 5.5.1
Meteor Node: 8.9.3
Meteor NPM: 5.5.1
Reaction CLI: 0.26.4
Reaction: 1.7.0
Reaction branch: master
Docker: 17.12.0-ce
```

### PR DESCRIPTION
**Pull request by Akarshit**
Closes #3652

### To test
1. Run `reaction`.
1. Login as admin and enable Marketplace.
2. Invite a marketplace admin.
1. Using Incognito to open the link in the invitation.
1. Observe no error in browser console and the shop name will be available in the navigation bar.

### CODE REVIEW

**Comment by jshimko** [comment]
This change works fine for me, but I also don't see any errors when doing the same reproduction steps on the master branch.  We sure this was the issue?

**Comment by zenweasel** [comment]
@jshimko I can replicate this error 100% of the time. Are you leaving the shop "inactive"?

**Comment by jshimko** [comment]
I did the exact steps in the first comment of this PR several times on both this branch and master.  Am I missing a step that was implied?  Was I supposed to create another shop?  Sounds like it from your last comment, but that wasn't mentioned in the reproduction steps, so I didn't do it.

**Comment by jshimko** [comment]
Nevermind.  It was not obvious to me that there's actually a collapsed form under here.

reaction_and_reaction

I was using the regular admin invite.

**Comment by zenweasel** [comment]
Yeah, the reproduction steps should have stated "Invite a marketplace admin" to be more clear.

**Comment by Akarshit** [comment]
@zenweasel Updated.

**Comment by Akarshit** [comment]
Wait I think I broke something, looking into it.

**Comment by Akarshit** [comment]
This code in this PR was already merged as a part of #3725.

**Pull request closed without merging**
