### PR TITLE
[WIP] Add Blocks API docs

### PR DESCRIPTION
**Pull request by mikemurray**
Impact: **minor**
Type: **docs**

## Issue

Bring docs closer to home

## Solution

Put docs right inside the package.

## Breaking changes

None.

## Testing
1. Read the docs here: https://github.com/reactioncommerce/reaction/tree/docs-mikemurray-blocks-api/imports/plugins/core/components

### CODE REVIEW

**Comment by mikemurray** [comment]
@aldeed This PR is to get the ball rolling, and was part of the discussion from the last engineering meeting. I want this to be a place to experiment with the folder structure and stuff so others can see a practical example while the DR is finalized.

What I have now is based on the DR as best I could interpret it. I looked through the DR and didn't see anything mentioning a version folder structure so I didn't do that. Maybe I'm overlooking something in the document.

**Comment by aldeed** [comment]
OK, yes I don't see versioning mentioned either. I remember discussing it, but maybe the branching/tagging is enough for versioning in the repos and the version folders will only some into play with the script that copies all of these docs into a single docs site. @kieckhafer @zenweasel anything to add here?

**Comment by zenweasel** [comment]
Yes, our original intent was to have version as a directory structure layer. I still think that makes sense and makes the raw docs more browsable. Is there any reason **not** to do that?

**Comment by aldeed** [comment]
I think we'd mainly just need to figure out what versioning docs looks like. For example, does releasing each new version mean we have to copy all docs into a new version folder? This is where I started thinking copying the way docusaurus does version folders made sense, because then at least we'd just defer to them on these decisions.

**Comment by mikemurray** [comment]
Another issue is how will each plugin be versioned. If plugins can be versioned independently of the core reaction app, then it would be difficult to align all the docs for all the repos into a single docusaurus instance.

I almost feel like each plugin, especially if they're split from the main repo, should maintain its own docusaurus folder structure, as well as build its own docs into a website that's published. Then the main docs site can link to individual plugin docs.

We could then use the main docs repo for guides for developers/operators since they could span multiple plugins.

**Comment by aldeed** [comment]
@mikemurray I agree that may be best if we can write some tools to make it all easy, preferably automatic on CI.

**Comment by machikoyasuda** [comment]
closing for now - we're not doing this yet/too early!

**Pull request closed without merging**
