### PR TITLE
chore: Skip failing integration tests

### PR DESCRIPTION
**Pull request by focusaurus**
Impact: **minor**  
Type: **chore**

## Issue

Integration tests are failing with a mongo issue.

## Solution

Skip the tests until @aldeed has a chance to investigate. I'll file a separate issue to track the broken tests.

### CODE REVIEW

**Comment by aldeed** [comment]
I already updated the `npm test` command in rc5 so you'll also have to put integration tests back there. At this point, if you rebase this on rc6 branch and fix conflicts, that should do it.

**Comment by focusaurus** [comment]
OK I think this should be good to merge. Now we get through all the tests cleanly just the integration ones get skipped via jest.

**Comment by spencern** [comment]
Looks good to me. Do we have a CI step we can re-enable now that they are skipped?

**Comment by focusaurus** [comment]
I think it's the same`npm test` step, just now the integration tests are part of that, but skipped.

**Comment by aldeed** [comment]
Integration tests have never run on CI because of a different issue. Both @jeffcorpuz and I tried getting them to work on CI but gave up. At some point we may have to re-evaluate the way the in-memory MongoDB is used.

**Pull request merged**
