### PR TITLE
React Router

### PR DESCRIPTION
**Pull request by mikemurray**
#2099 

This PR attempts to replace flow router with react router with little to no breaking changes, while adding some enhancements to layout configuration.

### Testing

**Try everything that's route related, and make sure it works as intended.** It's not 100% identical to how flow router worked in terms of feel, but should not notice a huge difference or any at all. 

Like it was mentioned above, this should not be a breaking change for those that used the registry to define routes.

**Thanks to look out for:**

- Hooks onEnter, onExit
- print layout
- Unauthorized page
- not founds are working
- sign in / sign out
- checkout
- paypal pay flow
- any thing that used url routing,
- body class names
- analytics events
- links that cause a full location change vs push state. ( links need to be handled with `Router.go()`, or react routers `<Link />` component, vs relying on their href; otherwise, you wont get a smooth transition. )
- admin layout is now separated from coreLayout. The content view has been updated to better reflect that a customer will actually see. For example, the header (main nav bar) is no longer sticky in admin mode. It scrolls with the page, just like it does for customers)

### CODE REVIEW

**Comment by zenweasel** [comment]
If I place an order and approve and capture it and hit "Print Invoice" I get an invoice with no values:

dashboard_pdf_orders

**Comment by zenweasel** [comment]
While trying to create a product, I get this weird thing where when I click on "Quantity" it keeps going back to the Title field making it hard/impossible to set the Quantity.

cant_set_quantity

**Comment by zenweasel** [comment]
I don't know how relevant, but I kept seeing this "X hidden by Filter" in the console go from 0 to about 1000 in a few minutes. Turning off the filter shows a bunch of these messages.

```
2modules.js?hash=346bb4b…:182548 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive.
meteor.js?hash=27829e9…:390 [Violation] 'message' handler took 1215ms
```

**Comment by zenweasel** [comment]
Cart Icon doesn't show quantity in cart when item is added.

dumb_product

**Comment by zenweasel** [comment]
As an admin, no matter how wide I make my browser, the horizontal scroll bar never disappears

basic_reaction_product_and_reaction_and_reactioncommerce_reaction_-_gitter

**Comment by zenweasel** [comment]
If I drop the `example-plugin` into the custom plug directory. I get this error on startup and the app never loads:

```
Exception from Tracker recompute function:
meteor.js?hash=27829e9…:930 TypeError: Cannot read property 'structure' of undefined
    at ReactionLayout (router.js:314)
    at Function.Router.initPackageRoutes (router.js:464)
    at initBrowserRouter (browserRouter.js:144)
    at startup.js:13
    at Tracker.Computation._compute (tracker.js?hash=9f8a0ce…:339)
    at Tracker.Computation._recompute (tracker.js?hash=9f8a0ce…:358)
    at Object.Tracker._runFlush (tracker.js?hash=9f8a0ce…:523)
    at onGlobalMessage (meteor.js?hash=27829e9…:401)
```

**Comment by zenweasel** [comment]
If I register as a non-admin user, I get the 403 error whenever I view the PDP.

example-product

**Comment by zenweasel** [comment]
Trying to checkout with Paypal Express I get this error when I click on the "Pay with Express"

**Client:**
```
Exception from Tracker recompute function:
meteor.js?hash=27829e9…:930 TypeError: Cannot read property 'merchantId' of undefined
    at expressCheckoutSettingsValid (checkoutButton.js:49)
    at Blaze.View.<anonymous> (checkoutButton.js:84)
    at blaze.js?hash=f33d3df…:1934
    at Function.Template._withTemplateInstanceFunc (blaze.js?hash=f33d3df…:3744)
    at blaze.js?hash=f33d3df…:1932
    at Object.Blaze._withCurrentView (blaze.js?hash=f33d3df…:2271)
    at viewAutorun (blaze.js?hash=f33d3df…:1931)
    at Tracker.Computation._compute (tracker.js?hash=9f8a0ce…:339)
    at Tracker.Computation._recompute (tracker.js?hash=9f8a0ce…:358)
    at Object.Tracker._runFlush (tracker.js?hash=9f8a0ce…:523)
```
**_Server_**

```
Exception while invoking method 'getExpressCheckoutSettings' TypeError: this.getShopName is not a function
    at getShopPrefix (lib/api/helpers.js:46:1)
    at Object.getAbsoluteUrl (lib/api/helpers.js:56:1)
    at Object.Express.expressCheckoutAccountOptions (imports/plugins/included/payments-paypal/lib/api/express.js:44:28)
    at [object Object].methods.getExpressCheckoutSettings (imports/plugins/included/payments-paypal/server/methods/express.js:128:5)
    at packages/check.js:130:16
    at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
    at Object.exports.Match._failIfArgumentsAreNotAllChecked (packages/check.js:129:41)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1734:18)
    at packages/ddp-server/livedata_server.js:719:19
    at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
    at packages/ddp-server/livedata_server.js:717:40
    at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
    at packages/ddp-server/livedata_server.js:715:46
    at [object Object]._.extend.protocol_handlers.method (packages/ddp-server/livedata_server.js:689:23)
    at packages/ddp-server/livedata_server.js:559:43
```

**Comment by kieckhafer** [comment]
I'm not seeing a summary in the Orders panel, and getting this error:

```
TypeError: Cannot read property '0' of undefined
    at composer (orderSummaryContainer.js:129)
    at compose.js:23
    at Tracker.Computation._compute (tracker.js?hash=9f8a0ce…:339)
    at Tracker.Computation._recompute (tracker.js?hash=9f8a0ce…:358)
    at Object.Tracker._runFlush (tracker.js?hash=9f8a0ce…:523)
    at onGlobalMessage (meteor.js?hash=27829e9…:401)
```

line 129 of `orderSummarContainer.js`
```
      const userProfile = Accounts.findOne(userId);
      if (!userProfile) {
        return profile;
      }
      profile = userProfile.profile.addressBook[0];
    }
```
reaction

**Comment by kieckhafer** [comment]
When logged in as an Admin, and I'm scrolled down the page so I cannot see the navbar, and I add something to my cart, the cart drawer slider does not display  absolutely on the page, instead it's displayed with the nav, and I have to scroll up to see it.

Also, when not logged in / not an admin, the page jumps to the top when I add an item to the cart (kind of annoying).
slider2 mov
cart-slicer mov

**Comment by kieckhafer** [comment]
Shippo error...

```
Exception in callback of async function: TypeError: Cannot read property 'shopId' of undefined
    at imports/plugins/included/shippo/server/methods/shippo.js:69:5
    at Array.map (native)
    at ratesParser (imports/plugins/included/shippo/server/methods/shippo.js:50:5)
    at [object Object].methods.shippo/getShippingRatesForCart (imports/plugins/included/shippo/server/methods/shippo.js:380:16)
    at packages/check.js:130:16
    at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
    at Object.exports.Match._failIfArgumentsAreNotAllChecked (packages/check.js:129:41)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1734:18)
    at packages/ddp-server/livedata_server.js:1666:15
    at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
    at packages/ddp-server/livedata_server.js:1664:30
    at [object Object]._.extend.applyAsync (packages/ddp-server/livedata_server.js:1663:12)
    at [object Object]._.extend.apply (packages/ddp-server/livedata_server.js:1611:26)
    at [object Object]._.extend.call (packages/ddp-server/livedata_server.js:1593:17)
    at getShippingRates (imports/plugins/included/shippo/server/hooks/rates.js:58:4)
    at server/api/hooks.js:60:1
    at Array.reduce (native)
    at Object.Hooks.Events.run (server/api/hooks.js:60:1)
    at [object Object].methods.shipping/getShippingRates (server/methods/core/shipping.js:81:18)
    at packages/check.js:130:16
    at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
    at Object.exports.Match._failIfArgumentsAreNotAllChecked (packages/check.js:129:41)
 => awaited here:
    at Promise.await (/Users/ek/.meteor/packages/promise/.0.8.8.1iimx3o++os+web.browser+web.cordova/npm/node_modules/meteor-promise/promise_server.js:39:12)
    at [object Object]._.extend.apply (packages/ddp-server/livedata_server.js:1624:22)
    at [object Object]._.extend.call (packages/ddp-server/livedata_server.js:1593:17)
    at getShippingRates (imports/plugins/included/shippo/server/hooks/rates.js:58:4)
    at server/api/hooks.js:60:1
    at Array.reduce (native)
    at Object.Hooks.Events.run (server/api/hooks.js:60:1)
    at [object Object].methods.shipping/getShippingRates (server/methods/core/shipping.js:81:18)
    at packages/check.js:130:16
    at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
    at Object.exports.Match._failIfArgumentsAreNotAllChecked (packages/check.js:129:41)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1734:18)
    at packages/ddp-server/livedata_server.js:1666:15
    at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
    at packages/ddp-server/livedata_server.js:1664:30
    at [object Object]._.extend.applyAsync (packages/ddp-server/livedata_server.js:1663:12)
    at [object Object]._.extend.apply (packages/ddp-server/livedata_server.js:1611:26)
    at [object Object]._.extend.call (packages/ddp-server/livedata_server.js:1593:17)
    at [object Object].methods.shipping/updateShipmentQuotes (server/methods/core/shipping.js:30:7)
    at packages/check.js:130:16
    at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
    at Object.exports.Match._failIfArgumentsAreNotAllChecked (packages/check.js:129:41)
 => awaited here:
    at Promise.await (/Users/ek/.meteor/packages/promise/.0.8.8.1iimx3o++os+web.browser+web.cordova/npm/node_modules/meteor-promise/promise_server.js:39:12)
    at [object Object]._.extend.apply (packages/ddp-server/livedata_server.js:1624:22)
    at [object Object]._.extend.call (packages/ddp-server/livedata_server.js:1593:17)
    at [object Object].methods.shipping/updateShipmentQuotes (server/methods/core/shipping.js:30:7)
    at packages/check.js:130:16
    at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
    at Object.exports.Match._failIfArgumentsAreNotAllChecked (packages/check.js:129:41)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1734:18)
    at packages/ddp-server/livedata_server.js:1666:15
    at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
    at packages/ddp-server/livedata_server.js:1664:30
    at [object Object]._.extend.applyAsync (packages/ddp-server/livedata_server.js:1663:12)
    at [object Object]._.extend.apply (packages/ddp-server/livedata_server.js:1611:26)
    at [object Object]._.extend.call (packages/ddp-server/livedata_server.js:1593:17)
    at server/methods/core/cart.js:397:16
    at wrappedCallbackForParsingMongoValidationErrors (packages/aldeed_collection2-core.js:511:15)
    at packages/mongo/collection.js:643:5
    at args.(anonymous function) (packages/matb33_collection-hooks.js:500:23)
    at runWithEnvironment (packages/meteor.js:1176:24)
    at packages/meteor.js:1189:14
    at packages/mongo/mongo_driver.js:320:7
    at packages/mongo/mongo_driver.js:572:15
 => awaited here:
    at Promise.await (/Users/ek/.meteor/packages/promise/.0.8.8.1iimx3o++os+web.browser+web.cordova/npm/node_modules/meteor-promise/promise_server.js:39:12)
    at [object Object]._.extend.apply (packages/ddp-server/livedata_server.js:1624:22)
    at [object Object]._.extend.call (packages/ddp-server/livedata_server.js:1593:17)
    at server/methods/core/cart.js:397:16
    at wrappedCallbackForParsingMongoValidationErrors (packages/aldeed_collection2-core.js:511:15)
    at packages/mongo/collection.js:643:5
    at args.(anonymous function) (packages/matb33_collection-hooks.js:500:23)
    at runWithEnvironment (packages/meteor.js:1176:24)
    at packages/meteor.js:1189:14
    at packages/mongo/mongo_driver.js:320:7
    at packages/mongo/mongo_driver.js:572:15
    at runWithEnvironment (packages/meteor.js:1176:24)
```

**Comment by mikemurray** [comment]
- [X] Fixed blank PDF (print) view
- [X] Child variant field focus

**Comment by aaronjudd** [comment]
Tags / nav not filtering product results. Reproduced with one product, one new tag, various publishing states..

test_and_1__aaronjudd_aarons-macbook-pro____projects_reaction__zsh_

**Comment by mikemurray** [comment]
- Cart Icon doesn't show quantity in cart when item is added.
- As an admin, no matter how wide I make my browser, the horizontal scroll bar never disappears
( Both seem related to the scrollbars always being visible. looking into a quick fix for this branch. More could be done in the future in a theme branch

- Created a guest account, add to card, and check out. Didn't see that permissions issue. May have fixed it, or not reproducing properly

---

- [X] Fixed issue with `example-plugin`

There is a bug in the example plugin with the `productsLanding.js` when signed in as admin. Bug happens even on master branch. https://github.com/reactioncommerce/reaction-example-plugin/issues/10

Also coreAdminLayout was a child layout of coreLayout in the Blaze days. Now coreAdminLayout has been moved out to a higher level, so I need to write docs and update the example plugin. *( When the example plugin is installed you'll notice two toolbars. )*

**Comment by mikemurray** [comment]
@kieckhafer The representation of the app is now more accurate to what a guest would see; so, the checkout slide out is working as it should. Yes, it's broken feeling, this is what a guest would see.

That said. I made it `position: fixed` as a quick solution. Any more should be a separate ticket in the navbar milestone https://github.com/reactioncommerce/reaction/milestone/54

**Comment by mikemurray** [comment]
@kieckhafer set up shippo on both `master` and this branch/pr and I see no error.

**Comment by mikemurray** [comment]
@aaronjudd The tags things seems to happen even in `master`. If you play around with the tags, adding / removing and publishing using `test` tag, it will eventually work itself out.

I've created an issue here: https://github.com/reactioncommerce/reaction/issues/2213

**Comment by aaronjudd** [comment]
I was able to checkout out as a newly registered user, however, was not able to view the order completed page after using a paypal express payment method.

reaction-paypal_paypaldone_and_cart_checkout

**Comment by aaronjudd** [comment]
@mikemurray I think @zenweasel mentioned that the orders completed page was taking a long time to load. I just want to confirm that it was long enough that I took a screenshot and was ready to report that it wasn't working (and only working for admin user).

**Comment by zenweasel** [comment]
If I change the URL/permalink and hit publish I get a 404 error

**Comment by zenweasel** [comment]
Other than the issue of changing the permalink and getting the 404, I am not seeing any problems. All the issues I previously reported appear to be fixed.

**Comment by aaronjudd** [comment]
@mikemurray Great work on this! Merging now! Hang on....

**Pull request merged**
