### PR TITLE
Spencer update dependencies

### PR DESCRIPTION
**Pull request by spencern**
Impact: **critical**  
Type: **bugfix**

Updates any packages that have dependencies with vulnerabilities noted by snyk

**prerender-node**
Updates and pins prerender-node from 2.7.4 to 3.1.1
The breaking changes in 3.1.1 are the removal of support for Node 0.10 and 0.12
As we don't support these versions either, this should not cause any problems.

**react**
Updates to the lastest React 16.4.1 from 16.2.0

**react-dom**
Updates to the latest react-dom 16.4.1 from 16.2.0

**react-dates**
Update and pin react dates from 16.3.6 to 17.1.0

**prop-types**
Update and pin prop-types from 15.6.0 to 15.6.2

**velocity-react**
Update and pin velocity-react from 1.3.3 to 1.4.1

**react-addons**
Removes unused react-addons dependencies
- react-addons-pure-render-mixin
- react-addons-shallow-compare

These are unused directly in the application.

**package-lock.json**
I attempted to break these changes up into multiple commits, but after a few attempts just pushed it as a blob.
Update package-lock.json file
Major updates
- @babel scoped dependencies
- @reactioncommerce/components dependencies
- react based dependencies
  - react
  - react-dates / airbnb
  - react-dom

Eliminates dependencies on several out-of-date packages with vulnerabilities
- base64url@2.0.0
- lodash@4.0.0
- stringstream@0.0.5
- ua-parser-js@0.7.17

Reduces exposure to
- tunnel-agent@4.0.3
- hoek@4.2.0

**.snyk ignore rules**

Removes the following .snyk ignore rules
- npm:hoek:20180212
- npm:lodash:20180130
- npm:tunnel-agent:20170305
- npm:ua-parser-js:20180227
- npm:stringstream:20180511
- npm:deep-extend:20180409
- npm:base64url:20180511

@kieckhafer and @willopez I added both of you because this is a fairly large PR.
I have tested the application and as many specific packages that I can (react-dates, velocity, react)
@aldeed Would like you to take a look at the package.json and approve the pinned versions

### CODE REVIEW

**Comment by spencern** [comment]
The eslint failure is introduced by a version bump of `jsx-a11y` which "fixes" a rule. I've updated our eslint config in this PR https://github.com/reactioncommerce/reaction-eslint-config/pull/4 to address this.

**Comment by kieckhafer** [comment]
Don't think this is related to this PR, but seeing this error when Shipping an order in the admin UI:

```
Uncaught (in promise) TypeError: Cannot read property 'getShopId' of undefined
    at getShopLang (helpers.js:115)
    at lazyLoadSlugify (utils.js:8)
    at Object.getSlug (utils.js:40)
    at Object.getShopPrefix (main.js:656)
    at Object.click [data-event-action=shipmentShipped] (shippingTracking.js:65)
    at blaze.js?hash=a1ff2d6d5ecd59ee11e2ba260b8650a9d1140f59:3775
    at Function.Template._withTemplateInstanceFunc (blaze.js?hash=a1ff2d6d5ecd59ee11e2ba260b8650a9d1140f59:3744)
    at Blaze.View.<anonymous> (blaze.js?hash=a1ff2d6d5ecd59ee11e2ba260b8650a9d1140f59:3774)
    at blaze.js?hash=a1ff2d6d5ecd59ee11e2ba260b8650a9d1140f59:2617
    at Object.Blaze._withCurrentView (blaze.js?hash=a1ff2d6d5ecd59ee11e2ba260b8650a9d1140f59:2271)
```

**Comment by kieckhafer** [comment]
Seeing this on startup, but looks like it's already commented in another ticket: 

```
[product._id is not allowed by the schema]
  Error: [product._id is not allowed by the schema]
      at Function.SimpleSchema.defineValidationErrorTransform.error [as validationErrorTransform] (imports/plugins/core/core/server/startup/index.js:20:20)
      at /opt/reaction/src/node_modules/simpl-schema/dist/SimpleSchema.js:757:30
      at Array.forEach (<anonymous>)
      at SimpleSchema.validate (/opt/reaction/src/node_modules/simpl-schema/dist/SimpleSchema.js:730:15)
      at Promise.asyncApply (imports/plugins/core/catalog/server/no-meteor/utils/publishProductToCatalog.js:36:21)
      at /home/node/.meteor/packages/promise/.0.11.1.1vczms8.mxi5++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
```

**Comment by aldeed** [comment]
@kieckhafer The currency selector hasn't been working for some time afaik. Possibly we should remove it?

Also, I believe the `Cannot read property 'getShopId' of undefined` error is pre-existing and I fixed it in https://github.com/reactioncommerce/reaction/pull/4412/commits/8cf072ec2d19ce2ffdca97cd423e27f5168bd6a2, which is part of https://github.com/reactioncommerce/reaction/pull/4412

**Comment by spencern** [comment]
@kieckhafer if you confirm @aldeed's suspicions that these issues are pre-existing then I'll merge. Otherwise I'll investigate to see what changes would have caused those failures

**Comment by kieckhafer** [comment]
Can confirm they are pre-existing

**Comment by willopez** [comment]
can also confirm those are pre-existing issues. And the currency selector works for me, see image below.
currency

**Pull request merged**
