### PR TITLE
Publications review

### LINKED ISSUE #664: User is not notified they are logged out in other tabs when logging out of one tab
Hello,

we have an issue with unexpected behavior on user logout when using several tabs [here](https://github.com/reactioncommerce/reaction/issues/656), but the most strange thing that the admin user have different behavior in the same situation.

When you attempt to logout by admin with several browser tabs, only active tab interact with server as expected. Other tabs not have such interaction. After you successfully logout, you could still see admin account inside non-active tabs by doing `Accounts.user()` or `ReactionCore.Collections.Cart.findOne()`.

### PR DESCRIPTION
**Pull request by newsiberian**
The main goal of this PR was to find the reason of #656 and #664.

I've added some inline-css for avatars in the hope that Mike will find the best place for these rules.

This PR fix #664 which originally was about "Admin account and several browser tabs".

#656 is not fixed here.

Also I turned off logout from other devices [here](https://github.com/reactioncommerce/reaction/blob/development/packages/reaction-accounts/client/templates/dropdown/dropdown.js#L22). Is this acceptable?

### CODE REVIEW

**Comment by newsiberian** [comment]
Looks like CI needed `reaction-factories` update

**Comment by zenweasel** [comment]
Verified fixes https://github.com/reactioncommerce/reaction/issues/664

**Comment by zenweasel** [comment]
When I login as admin now I am getting a default avatar rather than the Admin avatar. Is that the expected behavior?

reaction___basic_reaction_product

**Comment by aaronjudd** [comment]
There's a lot of comments left behind here that could be cleaned up. This PR really addresses two different things,  would be helpful if this was broken up. :+1:

**Pull request merged**
