### PR TITLE
[WIP] Make some search results clickable

### LINKED ISSUE #2625: [Marketplace] Clicking on result in Account/Order search does nothing
### Expected behavior
Clicking on result should take you to the "Manage Account" screen, or Order management screen

### Actual Behavior
Nothing happens

### Steps to Reproduce the Behavior
1. Login as admin
1. Search for an account or order
1. Click on result
1. Observe nothing happens

### Versions
```
Node: 7.10.0
NPM: 5.0.3
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction CLI: 0.11.0
Reaction: 1.5.0
Reaction branch: marketplace
Docker: 17.06.0-ce
commit: b6e18a4b5a35b852bd75648ae395a2f4b77eae81
```

### PR DESCRIPTION
**Pull request by foladipo**
Resolves #2625.

This PR fixes the bug reported in #2625. In that bug, clicking on search results for accounts or orders did nothing, as opposed to clicking on the search result for products, which brought up that product's detail page. This PR now shows a dashboard/details page for any accounts/orders search result when it is clicked.

## Test instructions

* Login as admin.

* Perform a search.

* Open the `ACCOUNTS` tab of the search results. Click any of the search results, and you'll notice that it now shows the accounts dashboard.

* Open the `ORDERS` tab of the search results. Click any of the search results, and you'll notice that it now shows the orders dashboard.

### CODE REVIEW

**Comment by foladipo** [comment]
# Note

There's a UX issue that crops up after this solution though. When you click an `Accounts` search result, it takes you to the accounts dashboard, which currently contains *user groups* only, and the various users that belong to those groups. So, if you are going to see the user you searched for, that user will jumbled together with many other users, which kind of defeats the reason for searching for a *specific* user in the first place. What's more, if the user you searched for doesn't belong to any group, then you won't see that user among all the users on the accounts dashboard.

Two ideas about how we can solve this problem are:
1. Add a section to the accounts dashboard that can highlight a chosen user.
1. Create a new page where the profile of a particular can be viewed.

Cc @zenweasel @impactmass

**Comment by impactmass** [comment]
Thanks @foladipo, good points/observations. Let's check with Ryan (as discussed elsewhere) to get UI/UX view of things.

**Comment by aaronjudd** [comment]
@impactmass @rymorgan is this under active development?  @foladipo can you resolve conflicts and bring this up to current so we can review again, otherwise let's close this and revisit (if it's really still a WIP).

**Comment by rymorgan** [comment]
@aaronjudd I don't know if this is being worked on. If this ticket is for non-admin users, then we can send them to the user page. This will make sense in the future when we update the user profile page and also have a custom view when an admin is looking at a customer (aka a user with no permissions). 

If the user is admin we need to add a card to edit that specific users' group and reset a password.

**Comment by foladipo** [comment]
@rymorgan Yes, this ticket is for admin users.

@aaronjudd I have resolved the merge conflicts and brought this up to date. However, I'm going to close this for now, pending when Ryan creates the design for the card for showing a single user.

**Pull request closed without merging**
