### PR TITLE
Fix for "Error when enabling Shopify inventory hooks"

### LINKED ISSUE #3974: Error when enabling Shopify inventory hooks
## Issue Description
Receive "Error setting up Shopify Sync" in browser and error in server console when enabling shopify inventory sync

## Steps to Reproduce
1. Login as admin
1. Go to "Connectors" panel
1. Select "Update Inventory when new Shopify order is placed"
1. Click on "Setup Sync"
1. Observe errors in server and browser

```
  server-error Shopify API Error creating new webhook: Response code 422 (Unprocessable Entity) { HTTPError: Response code 422 (Unprocessable Entity)
      at stream.catch.then.data (/Users/brenthoover/Projects/js/reaction/node_modules/got/index.js:341:13)
      at /Users/brenthoover/.meteor/packages/promise/.0.10.1.trxnxh.msck++os+web.browser+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
   => awaited here:
      at Function.Promise.await (/Users/brenthoover/.meteor/packages/promise/.0.10.1.trxnxh.msck++os+web.browser+web.cordova/npm/node_modules/meteor-promise/promise_server.js:56:12)
      at Promise.asyncApply (imports/plugins/included/connectors-shopify/server/methods/webhooks/webhooks.js:55:13)
```

### Versions
```
Node: 8.9.4
NPM: 5.6.0
Meteor Node: 8.9.4
Meteor NPM: 5.6.0
Reaction CLI: 0.28.0
Reaction: 1.9.0
Reaction branch: release-1.9.0
Docker: 17.12.0-ce

```

### PR DESCRIPTION
**Pull request by prinzdezibel**
Resolves #3974  
Impact: **minor**  
Type: **bugfix**

## Issue
Receive "Error setting up Shopify Sync" in browser and error in server console when enabling shopify inventory sync

## Solution
- Before creating the webhook the API is queried for the webhook URI
that's going to be installed. If it's already installed, we skip the
webhook creation.

## Breaking changes
none

## Testing
1. As an admin, go to the shopify connector and setup the order creating webhook "Update Inventory on Shopify Order"
2. Don't use localhost as webhook callback domain, but any other valid URL
3. Setup Sync
4. Go to Robo-Mongo and delete the newly created webhook in the array db.getCollection('Packages').find({name: "reaction-connectors-shopify"})
5. Go to the dashboard and try to install the sync hook again with the same domain URL.
6. Observe that this action should work without error
7. Go to RoboMongo and see that the webhook is updated again in database: `webhooks array`

### CODE REVIEW

**Comment by zenweasel** [comment]
Looks like you have failing tests here? Tests are failing for me locally as well.

**Comment by prinzdezibel** [comment]
I don't get those errors locally. Are we talking about the meteor integration tests?
> SERVER_TEST_REPORTER="dot" meteor test --once --full-app --headless --driver-package dispatch:mocha

**Comment by prinzdezibel** [comment]
Looks better this time.

**Comment by prinzdezibel** [comment]
@Akarshit Perhaps you find time to check this one too.

**Comment by prinzdezibel** [comment]
ready to merge

**Pull request merged**
