### PR TITLE
Fix Sidebar Context

### PR DESCRIPTION
**Pull request by impactmass**
Resolves [#1838](https://github.com/reactioncommerce/reaction/issues/1838)

Issue: ActionView (Sidebar) current display needs to change based on context in main view.

This update makes:
- Sidebar show shipping settings when on step 2/3 (billing and shipping) of checkout process
- Sidebar show payment settings when on step 4/5 (payment) of checkout process
- Sidebar closes if opened when on profile edit page (/account/profile)
All these while logged in as admin

### CODE REVIEW

**Comment by zenweasel** [comment]
@impactmass You requested a review but the PR is still tagged with WIP. Is this ready to be reviewed/merged?

**Comment by impactmass** [comment]
Thanks @zenweasel, I'll correct that.

Thanks for the feedback @kieckhafer. I'll test out again as you described and make sure it works as expected.

**Comment by impactmass** [comment]
Hi @kieckhafer (I've been on a tax ticket so I just came back to this.)

I tested this multiple times again, and repeated the steps you took, but this worked as I set it to (described above). I also got @joykare to test it out for me on her end, and it worked as I mentioned.

Can you check out the branch again?

**Comment by kieckhafer** [comment]
I'm not seeing this error anymore...

**Pull request merged**
