### PR TITLE
This PR complements the PR for reaction-cli:

### PR DESCRIPTION
**Pull request by prinzdezibel**
Add a new build step : "Asset provisioning"

https://github.com/reactioncommerce/reaction-cli/pull/51

### CODE REVIEW

**Comment by spencern** [comment]
@prinzdezibel @jshimko @zenweasel  What's the story with this PR - can we close it or merge it? It's been open and unattended for a long time.

**Comment by jshimko** [comment]
@prinzdezibel We need to also add `/private/plugins/*` and `/public/plugins/*` to the Reaction .gitignore as part of this.  Plugin assets will be committed in the plugins themselves, so we don't want to have them committed twice.  
The [PR this has been waiting on in the CLI](https://github.com/reactioncommerce/reaction-cli/pull/51) is now merged and released (`reaction-cli@0.26.0`), so this should probably happen soon.

**Comment by prinzdezibel** [comment]
@jshimko should be ok now. thanks for reviewing it.

**Comment by zenweasel** [comment]
@jshimko Can you re-review and approve it ok?

**Comment by aaronjudd** [comment]
@jshimko what is the status here? can you please update and respond?

**Comment by jshimko** [comment]
@prinzdezibel this all looks good to me.  One last thing we should add though is the same README from `private/plugins/README.md` in `public/plugins/README.md`.  Otherwise, I think we're good to go here.

**Pull request merged**
