### PR TITLE
Instagram Login/Registration

### LINKED ISSUE #2559: Add Instagram Login / registration as an option
We'd like to add the option to login / register for Reaction with Instagram. There are existing packages that should be looked into:

https://atmospherejs.com/packages/instagram

We'll also need to add a field into the admin which allows the shop owner / admin to add their Instagram developer api key / access token, similar to what we have for Facebook, Twitter, etc.

reaction

When choosing permissions, we'd like to be able to access as much Instagram information as possible, but most importantly the users Profile Photo (https://www.instagram.com/developer/endpoints/users/) and Photo Feed (https://www.instagram.com/developer/endpoints/media/).

### PR DESCRIPTION
**Pull request by awadesmoline**
This resolves #2559

### Steps to test
1. Register an app with Instagram at http://instagram.com/developer/clients/register
1. Fill out the given form but make sure that redirect url as shown as follows-
OAuth redirect_uri: `<your-server-domain>:<port>/_oauth/instagram` For example `http://localhost:3000/_oauth/instagram`
1. After registration, copy the `clientId` and `client secret`.
1. Signin to Reaction as admin
1. On the dashboard, under Login Services, toggle on Instagram Sign In
1. On a new browser, click on the authentication dropdown in nav and signin with instagram.

### CODE REVIEW

**Comment by kieckhafer** [comment]
reaction

Format icon spacing

**Comment by kieckhafer** [comment]
reaction

Translation / i18n needed for `social.instagram`

**Comment by kieckhafer** [comment]
reaction

Broker profile image, most likely related to Browser-Policy

**Comment by kieckhafer** [comment]
account_profile

We get the users name from the Instagram API, can we use that to update the profile name so it shows their name instead of "Guest"?

**Comment by awadesmoline** [comment]
@kieckhafer profile name now shows user's name from Instagram API.

**Comment by zenweasel** [comment]
I'm using the App info that @kieckhafer posted in Slack and I get this error when I attempt to login:
````
{"error_type": "OAuthForbiddenException", "code": 403, "error_message": "You are not a sandbox user of this client"}
```

I tried creating another Instagram app but the instructions are not very complete

**Comment by kieckhafer** [comment]
Looks like I need to add you to my App if you want to use the test creds I posted in the dev channel. Slack me your IG username and I'll add you if you want to use that App.

**Pull request merged**
