### PR TITLE
Fixed indicating products that are invalid for publication

### LINKED ISSUE #2690: Publish all without label doesn't let know which product is missing label
### Expected behavior
If there are problems with a product during publish all, an informative error message would be displayed that indicates what needs to be done

### Actual Behavior
error is produced, but there's no immediate indication of where user attention is required

### Steps to Reproduce the Behavior
1. Login as Admin
1. Create a product but leave "Label" blank
1. Navigate to the product grid
1. Hit "Publish All"
1. Observe that the products don't publish, but there is no indicator what the problem is or which product is problematic.

### Versions
Node: 6.11.2
NPM: 3.10.10
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction CLI: 0.11.0
Reaction: 1.4.1
Reaction branch: master

### PR DESCRIPTION
**Pull request by aanchirinah**
Partly resolves #2690 ,

This PR adds a red badge at the top of products that have failed validation before being published. I added a `checkValidation` function in `gridItemControlContainer.js`  that uses _Simple Schema_ validation method to check validity of a product including it's variants before publishing it. And also added a condition to also add the appropriate badge for when a product is invalid in `gridItemControl.js` component.

#### **HOW TO TEST**
Some context before proceeding to test, so initially it was quite confusing for a user to differentiate between products that require to be published and those that required all fields to be completed as it indicated a green info badge on the affected products in the product grid. To understand what is trying to be fixed here, the test below is going to include how to create these 2 instances of products.

**How to test for the green badge**
```
- Login as Admin
- Create a product fill out all the fields required
- Navigate to the product grid
- Observe that the product you just created has a green badge at the top right corner.
```
**How to test for the red badge**
```
- Login as Admin
- Create a product but leave "Label" blank
- Navigate to the product grid
- Observe that the product you just created has a red badge at the top right corner.
```

### CODE REVIEW

**Comment by zenweasel** [comment]
@aanchirinah What's the status on this?

**Comment by codejockie** [comment]
I have tested this out and everything is working fine.

**Comment by aanchirinah** [comment]
@zenweasel , I was still testing it out but everything works as it should now

**Comment by zenweasel** [comment]
@aanchirinah So there appears to be quite a few problems here. The most obvious one being that when I add a product in a merchant shop, an error is thrown in the primary shop

```
TypeError: Cannot read property 'isValid' of undefined
    at GridItemControlsContainer._this.checkValidation (gridItemControlsContainer.js:49)
    at GridItemControlsContainer.componentWillMount (gridItemControlsContainer.js:32)
    at modules.js?hash=7ee907e6d17784321fe48b45f09bcaa0f5d0b366:108247
    at measureLifeCyclePerf (modules.js?hash=7ee907e6d17784321fe48b45f09bcaa0f5d0b366:107975)
    at ReactCompositeComponentWrapper.performInitialMount (modules.js?hash=7ee907e6d17784321fe48b45f09bcaa0f5d0b366:108246)
    at ReactCompositeComponentWrapper.mountComponent (modules.js?hash=7ee907e6d17784321fe48b45f09bcaa0f5d0b366:108157)
    at Object.mountComponent (modules.js?hash=7ee907e6d17784321fe48b45f09bcaa0f5d0b366:100918)
    at ReactCompositeComponentWrapper.performInitialMount (modules.js?hash=7ee907e6d17784321fe48b45f09bcaa0f5d0b366:108270)
    at ReactCompositeComponentWrapper.mountComponent (modules.js?hash=7ee907e6d17784321fe48b45f09bcaa0f5d0b366:108157)
    at Object.mountComponent (modules.js?hash=7ee907e6d17784321fe48b45f09bcaa0f5d0b366:100918)
```

### Steps to reproduce
1. Create a marketplace shop
1. Create an invalid product in your marketplace shop
1. Navigate back to the primary shop
1. Observe an error is thrown in the console.

**Comment by aanchirinah** [comment]
@zenweasel , I just pulled recent `1.5.6` and tested the PR severely once again with 2 marketplace shops but didn't experience any of the bugs you were facing can you please pull the branch again and try again.

**Comment by zenweasel** [comment]
reaction1_and_reaction1_and_reaction_docs_-_merchant_shop_setup

When I correct the problems with a product in the marketplace shop, the red dot does not appear to get removed in the primary shop.

### Steps to replicate
1. Invite a shop
1. Create an invalid product in that shop (leave out the label)
1. Observe that the "red dot" correctly appears in the marketplace shop and the primary shop
1. Correct the product in the marketplace shop and publish
1. Observe that the red dot does disappear in the marketplace shop but **does not** in the primary shop

You also have a lint error that needs to be resolved.

```
/Users/brenthoover/Projects/js/reaction/imports/plugins/included/product-variant/containers/gridItemControlsContainer.js
  46:52  error  Trailing spaces not allowed  no-trailing-spaces
```

**Comment by aanchirinah** [comment]
@zenweasel , I have fixed your requested changes

**Comment by zenweasel** [comment]
Tested. Verified working.

**Pull request merged**
