### PR TITLE
fix order values store as string

### PR DESCRIPTION
**Pull request by iakhator**
Resolve issue #3215 

Fix Order values storing as `String` in the database even when the schema is set as a `Number`.

#### Fix
- In the Cart Schema there is a `billing` property which has a validation of blackbox set as true is remove.
- In the PaymentMethod Schema  the createAt property with validation of denyUpdate set to true is also remove.

#### Test.
- Place an order
- Open Robomongo or it's alternative
- Go to billing/invoice and observe the values are stored as Double
screen shot 2017-11-02 at 4 00 05 pm

### CODE REVIEW

**Comment by zenweasel** [comment]
It seems like removing the `denyOnUpdate` is going to mean that every time you update the record the `createdAt` record will be set which is not what we want. Can you verify this will not happen?

**Comment by iakhator** [comment]
okay, I will check it out

**Comment by iakhator** [comment]
I figured out that `denyUpdate` is set in the paymentMethod schema which only needs a created date. Because payment is made once after checking out. removing the `denyUpdate` for the paymentMethod schema does not update.

**Comment by zenweasel** [comment]
@iakhator You have some tests failing. Lots of them.

**Comment by iakhator** [comment]
Right. I will attend to the failing test.

**Comment by iakhator** [comment]
Resolved.

**Pull request merged**
