### PR TITLE
tests: Add integration tests for surcharge

### PR DESCRIPTION
**Pull request by trojanh**
Resolves https://github.com/reactioncommerce/reaction/issues/5937 & #5923 
Impact: **minor**  
Type: **test|chore**

## Issue
Add integration tests for createSurcharge, updateSurcharge and deleteSurcharge mutations

### CODE REVIEW

**Comment by mikemurray** [comment]
@trojanh Would you mind adding taking #5923 and doing the `updateSurcharge` tests?

**Comment by trojanh** [comment]
Sorry @mikemurray I had just checked the open PRs before starting this and later found that you already had similar issues assigned to yourself. I didn't mean to do overlapping work. If you haven't started working on the updateSurcharge test i dont mind completing it with this.

**Comment by mikemurray** [comment]
@trojanh It's ok, I assigned myself to it but didn't start working on it since other things popped up in priority.

**Comment by trojanh** [comment]
@mikemurray feel free to review this now whenever you can.

**Pull request merged**
