### PR TITLE
Remove jquery-ui

### LINKED ISSUE #1215: Upgrade to jquery-ui@1.12.0
Upgrade to jquery-ui@1.12.0 to resolve security warnings.

This will also require some updates to ui implementation as the npm package structure has changed. 

In scope would be refactoring and importing only the actual UI methods required.

Pay particular attention to easing errors in the console when testing checkout, order fulfillment.

See: https://snyk.io/test/github/reactioncommerce/reaction/963dbe9bcd462282382ca6e1ee243cf63035b4e7?fromStatus=true

### PR DESCRIPTION
**Pull request by mikemurray**
Resolves #1215 

Removed jquery-ui.
Replaced instances of jquery-ui sortable with sortable.js
Replaced instances of jquery-ui autocomplete with autosuggestion react component.

Fixed bug where duplicate tag error message would show on blur of tag input, even if the input did not change.

Added git ignore for config file

- [x] Description explains the issue / use-case resolved
- [ ] Only contains code directly related to the issue
- [ ] Has tests.
- [ ] Has docs.
- [ ] Passes all tests
- [x] Has been linted and follows the style guide

### CODE REVIEW

**Comment by aaronjudd** [comment]
No easing...  checkout slide out is stuck open.
reaction

**Comment by aaronjudd** [comment]
Tag Edit autocomplete in navbar not functional.
reaction

Seems ok in the PDP tags though.

**Comment by mikemurray** [comment]
Both issues should be addressed.

**Comment by aaronjudd** [comment]
Easing cart panel slide out looks good now. 
```
Exception in template helper: TypeError: Cannot read property 'isEditing' of undefined
    at Object.isEditing (http://localhost:3000/app/app.js?hash=a96e9d34083c4c48ae2162e656e74f4bee4aada8:25182:38)
Exception in template helper: TypeError: Cannot read property 'relatedTagIds' of undefined
    at Object.subTags (http://localhost:3000/app/app.js?hash=a96e9d34083c4c48ae2162e656e74f4bee4aada8:27726:30)
    at Object.tagListProps (http://localhost:3000/app/app.js?hash=a96e9d34083c4c48ae2162e656e74f4bee4aada8:26872:26)

```

**Comment by mikemurray** [comment]
This is happening in development. Going to make a another ticket as this is not related to the jQuery UI removal.

**Comment by aaronjudd** [comment]
👍

**Comment by kieckhafer** [comment]
👍  looks good

**Pull request merged**
