### PR TITLE
New product title field for Cart and Order documents

### PR DESCRIPTION
**Pull request by newsiberian**
This PR related with [this thread](http://discourse.reactioncommerce.com/t/cart-order-should-contain-product-titles/65/1).
extended_title_1
extended_title_2
extended_title_3

- [ ] Description explains the issue / use-case resolved
- [x] Only contains code directly related to the issue
- [ ] Has tests.
- [ ] Has docs.
- [ ] Passes all tests
- [x] Has been linted and follows the style guide

### CODE REVIEW

**Comment by aaronjudd** [comment]
basic_reaction_product

**Comment by aaronjudd** [comment]
Tests fail current for this, and you have to reset product data with the new schema first. 

I'm assuming tests are failing because they don't have the added Title data 

```
W20160502-15:33:56.742(-7)? (STDERR) cart methods cart/unsetAddresses should update cart via `type` argument
W20160502-15:33:56.742(-7)? (STDERR) Error: Title is required
W20160502-15:33:56.742(-7)? (STDERR) packages/aldeed_collection2-core.js:466:15: Error: Title is required
W20160502-15:33:56.742(-7)? (STDERR)   at getErrorObject (packages/aldeed_collection2-core.js:466:15)
W20160502-15:33:56.742(-7)? (STDERR)   at [object Object].doValidate (packages/aldeed_collection2-core.js:449:13)
W20160502-15:33:56.742(-7)? (STDERR)   at [object Object].Mongo.Collection. (anonymous function) [as insert] (packages/aldeed_collection2-core.js:202:25)
W20160502-15:33:56.742(-7)? (STDERR)   at Function.Factory._create (/private/var/folders/z5/lhsfpjqs47qc5lbybyzqj6p80000gn/T/meteor-test-runen7xys/.meteor/local/build/programs/server/packages/dburles_factory.js:168:29)
W20160502-15:33:56.743(-7)? (STDERR)   at Function.Factory.create (/private/var/folders/z5/lhsfpjqs47qc5lbybyzqj6p80000gn/T/meteor-test-runen7xys/.meteor/local/build/programs/server/packages/dburles_factory.js:177:24)
W20160502-15:33:56.743(-7)? (STDERR)   at /private/var/folders/z5/lhsfpjqs47qc5lbybyzqj6p80000gn/T/meteor-test-runen7xys/.meteor/local/build/programs/server/packages/local-test_reactioncommerce_core.js:662:26
```

**Comment by aaronjudd** [comment]
also 
```Exception in callback of async function: Error: Match error: Match error: title is not allowed by the schema in field [0]
    at check (packages/check.js:138:15)
    at [object Object].inventoryAddReserve (packages/reactioncommerce:reaction-inventory/common/methods.js:202:5)
    at packages/check.js:211:16```

**Comment by newsiberian** [comment]
> In theory, I'm ok with this update.. but want to explain how we got here...

Hello, I got it. The logic you describe assumes that `label` should contain something like `${product.title} ${variant.optionTitle}`.

**Comment by newsiberian** [comment]
I've added [changes to factories](https://github.com/reactioncommerce/reaction-factories/pull/8). For me now all related tests passed. I see one failed test `core methods shop/locateAddress should provide default empty address`, but I don't think it is related with this PR.

**Comment by aaronjudd** [comment]
Still blocked see: https://github.com/reactioncommerce/reaction-factories/pull/8#issuecomment-216606983

**Comment by newsiberian** [comment]
Hello, now tests should work.

**Comment by zenweasel** [comment]
Verified all tests pass

**Pull request merged**
