### PR TITLE
[reaction-catalog] Implementing Validation Methods

### PR DESCRIPTION
**Pull request by newsiberian**
Hello, introducing my little experiment with validation methods. Originally I had an idea to move `uploadMedia` functionality to these methods, but transferring `Blob` object to the server side is so complicated thing..., so I decide to leave it and move other stuff.

### CODE REVIEW

**Comment by zenweasel** [comment]
Shouldn't this PR include tests for these new methods?

**Comment by aaronjudd** [comment]
:+1:

**Comment by newsiberian** [comment]
Looks like there is `meteor` way to pass `blob` to server :smile: http://docs.meteor.com/#/full/ejson_new_binary

**Comment by aaronjudd** [comment]
@newsiberian we use CFS to store blobs. (images)... in the db..  I'd take a look at that code

**Comment by newsiberian** [comment]
yes, but the thing is -- this is work for us because we insert this blobs directly from client side [here](https://github.com/reactioncommerce/reaction/blob/development/packages/reaction-product-variant/client/templates/products/productDetail/images/productImageGallery.js#L46). It would be cool to move this logic to server side (for that we need to convert blobs), but I don't think this is so necessary...

**Pull request merged**
