### PR TITLE
Fix for pdp variant price range

### PR DESCRIPTION
**Pull request by newsiberian**
It were displayed not top variant's child variants price range but product price range.

- [ ] Description explains the issue / use-case resolved
- [x] Only contains code directly related to the issue
- [ ] Has tests.
- [ ] Has docs.
- [ ] Passes all tests
- [x] Has been linted and follows the style guide

### CODE REVIEW

**Comment by zenweasel** [comment]
Approved

**Comment by mikemurray** [comment]
:+1:

**Comment by aaronjudd** [comment]
I'm not sure this is the right behaviour.  Products range should be a range that is inclusive of all variants and options.  A variant price range should only displayed when you select the variant, or in the variant "inventory bar". The variant range is inclusive of all options.

**Comment by newsiberian** [comment]
Hello, @aaronjudd, in PDP we always have selected variant. Try to switch between default product first and second top variants and you'll noticed that first top variant price are always be a product price.

I'm not sure it is better to show all variants prices at once...

**Comment by zenweasel** [comment]
@newsiberian That's not what I am seeing here. The product price always is reflecting all variants not just the first

**Comment by newsiberian** [comment]
pdp_price_bug

**Comment by aaronjudd** [comment]
@newsiberian your first picture shows the problem.  the first item IS selected, and should be showing 12.99 - 19.99 because it is selected. When you first view a product you do not have any variant or options selected by default, and it show the whole range.

**Comment by newsiberian** [comment]
Hello, we always have selected variant. If it were not so, then you shouldn't see any images because our products can't have images for some time. When you fist enter to PDP you always have first variant selected, at least this is the current behavior.

**Pull request merged**
