### PR TITLE
Added Norwegian translations

### PR DESCRIPTION
**Pull request by thedole**
I just added a translation file for the Norwegian language and poked around to find out how to actually make it work. I think possibly the documentation for translations might need some poking too.

### CODE REVIEW

**Comment by zenweasel** [comment]
@thedole What suggestions do you have for the translation docs?

**Comment by thedole** [comment]
Was that failing test my doing?

**Comment by thedole** [comment]
@zenweasel I Will see if I can write something up tomorrow, it's 2:30am here, I'm heading for the sheets.

**Comment by zenweasel** [comment]
Approved: Pulled branch and tested. Looks good!

**Pull request merged**
