### PR TITLE
Product/Tag Date Filtering

### LINKED ISSUE #6527: Data Filtering/Search
Establishing a system-wide pattern for doing searching and filtering, eventually with the ability to save filters. Mostly focused on Products/Orders/Customers

### PR DESCRIPTION
**Pull request by dcrdev**
Impact: **minor**
Type: **feature**

## Issue

This PR adds basic date filtering to products and tags via several different operands eg. after, before, between.

At the moment this is light touch, only servicing products and tags and could be improved upon by constraining these date filter types with graphql interfaces, however I wasn't sure whether that's an existing pattern, nor where they would live.

I wasn't aware of #6527 when I began this, so this wasn't specifically drafted with that in mind, but rather precipitated by our own internal requirements.

### CODE REVIEW

**Comment by brent-hoover** [comment]
@dcrdev Not sure why jobs aren't running on this but linting is failing:
```
/home/brent/Projects/merchstack/merchstack-reaction-fork/packages/api-plugin-products/src/index.js
  39:37  error  Unexpected trailing comma  comma-dangle

/home/brent/Projects/merchstack/merchstack-reaction-fork/packages/api-plugin-products/src/utils/applyProductFilters.js
    4:3   error  Properties shouldn't be quoted as all quotes are redundant     quote-props
    8:3   error  Properties shouldn't be quoted as all quotes are redundant     quote-props
   15:3   error  Properties shouldn't be quoted as all quotes are redundant     quote-props
   19:3   error  Properties shouldn't be quoted as all quotes are redundant     quote-props
   23:3   error  Properties shouldn't be quoted as all quotes are redundant     quote-props
   27:3   error  Properties shouldn't be quoted as all quotes are redundant     quote-props
  113:11  error  'createdAtSelectors' is never reassigned. Use 'const' instead  prefer-const
  122:49  error  Unexpected trailing comma                                      comma-dangle
  129:48  error  Unexpected trailing comma                                      comma-dangle
  149:11  error  'updatedAtSelectors' is never reassigned. Use 'const' instead  prefer-const
  158:49  error  Unexpected trailing comma                                      comma-dangle
  165:48  error  Unexpected trailing comma                                      comma-dangle

/home/brent/Projects/merchstack/merchstack-reaction-fork/packages/api-plugin-tags/src/queries/tags.js
  46:9   error  'createdAtPredicates' is never reassigned. Use 'const' instead  prefer-const
  55:32  error  Unexpected trailing comma                                       comma-dangle
  62:31  error  Unexpected trailing comma                                       comma-dangle
  82:9   error  'updatedAtPredicates' is never reassigned. Use 'const' instead  prefer-const
  91:32  error  Unexpected trailing comma                                       comma-dangle
  98:31  error  Unexpected trailing comma                                       comma-dangle
```

**Comment by dcrdev** [comment]
> @dcrdev Not sure why jobs aren't running on this but linting is failing:

Should be fixed now

**Review by brent-hoover — APPROVED** [review]
Code looks fine but I need to figure out why the checks aren't running to tests can pass

**Comment by brent-hoover** [comment]
@dcrdev Not sure what's happening with the jobs running but can you cherry-pick this on to a branch as a contributor rather than a fork?

**Comment by dcrdev** [comment]
Closed in favor of #6549

**Pull request closed without merging**
