### PR TITLE
Remove unused Blaze templates.

### PR DESCRIPTION
**Pull request by prinzdezibel**
The following two Blaze templates are no longer needed.

      1) layoutHeader
         This template was used for most cases (coreLayout). But since
         coreLayout.js does include the new Components.NavBar React
         component, it's obsolete
      2) checkoutHeader
         This was a customized version of the header for the checkout
         workflow. Nowadays the checkout workflow also uses the standard
         NavBar component. Therefore it's obsolete, too.

### CODE REVIEW

**Comment by mikemurray** [comment]
@prinzdezibel which I think you may have fixed in: https://github.com/reactioncommerce/reaction/pull/3257/files#diff-9ebade6744b20e86dd07f325d59075d0R22 

It seems like coreLayout should be pulling a template for the header from the layout.

**Comment by prinzdezibel** [comment]
@mikemurray I think this is already broken in master. Should I fix it as part of this ticket or do you think it makes sense to have a new issue for that?

**Comment by prinzdezibel** [comment]
@zenweasel Hi Brent, @mikemurray made the suggestion to fix this behaviour (the checkout navbar should be a dedicated one without tag bar) right away as part of this ticket. If you agree, I could do it tomorrow. Alternatively, we could create a new issue, because it's broken in master anyway. Please decide and let me know. thanks.

**Comment by zenweasel** [comment]
@prinzdezibel Yes, If we can fix this quickly in this PR let's do it. But if it turns into more than a couple hours of extra work let's break it off into another issues, especially if it's something already broke in `master`.

**Comment by prinzdezibel** [comment]
I've searched the code base for an visual component (React or Blaze) that represents what formerly was known as `checkoutHeader`. But I can't find anything. Probably it would make sense to just add options to the existing NavBar and strip it down when using in checkout context. But I don't know how this is supposed to look. @rymorgan: Is it just what the regular navigation bar (called NavBar) does, except for the tag-bar not visible.

**Comment by prinzdezibel** [comment]
@zenweasel Maybe it makes more sense to have this in a separate ticket, because I can't it fix straight away without further help.

**Comment by rymorgan** [comment]
Having the full navigation bar show up at the checkout is definitely a regression and an important one to fix. I'm not sure where or how the navigation started appearing here. The only thing that should show once someone is in the checkout is the logo area in the upper left. 

checkout

**Comment by prinzdezibel** [comment]
@mikemurray  @zenweasel  : This PR is obsolete and is superseded by this PR:
https://github.com/reactioncommerce/reaction/pull/3257

I've implemented @rymorgan 's design into the other PR


I'm going to close this one.

**Pull request closed without merging**
