### PR TITLE
(refactor): 3551 replace vsivsi:job-collection for npm module @reactioncommerce/job-queue

### LINKED ISSUE #3551: Copy vsivsi:job-collection package API into the app
Goal: Decrease Meteor pkg deps

Work:

1. Copy the vsivsi:job-collection Meteor package code (https://github.com/vsivsi/meteor-job-collection) into an app plugin
1. Remove the package
1. Ensure that background jobs still run correctly

### PR DESCRIPTION
**Pull request by mikemurray**
Resolves #3551
Impact: **breaking**
Type: **refactor**
 
## Issue
 
Deprecate the usage of the atmosphere package [visivisi:meteor-job-collection](https://github.com/vsivsi/meteor-job-collection) and move to an `npm` package https://github.com/reactioncommerce/reaction-job-queue.

This is to further reduce Reaction's dependency on atmosphere packages, and `vsivsi:job-collection` has been deprecated since `01-01-2018`.

## Solution
 
1. Convert from CoffeeScript to es2015 using http://decaffeinate-project.org/
1. Run through the files and fix linting issues, formatting
1. Fix warnings from the conversion provided by decaffeinate
1. Import where needed
1. Include any required `npm` packages like `later.js`
1. Convert all tests. 1 test file exists in the `@reactioncommerce/job-queue` package while the Meteor specific tests exist in the main app.
 
## Breaking changes
 
- `visivisi:meteor-job-collection` removed. Noe uses npm package https://github.com/reactioncommerce/reaction-job-queue
- New import path for both Job abd Job Collection. `import { Job, JobCollection } from "/imports/plugins/core/job-collection/server/jobCollection.js"`
- `mrt:later` removed due to removal of `visivisi:meteor-job-collection`
- Uses an npm package https://github.com/reactioncommerce/reaction-job-queue
- `Job` and `JobCollection` are now required to be instantiated with `new`. `new Job()` `new JobCollection()`
 
## Testing
 
**Test 1**
1. Run tests using `reaction test`, make sure they pass
1. Verify that email is properly configured
1. Add items to cart and checkout
1. Receive email

**Test 2**
1. Break email config so email is not configured
1. Add items to cart and checkout
1. Should not receive email
1. Go back to email settings and fix email config
1. Resend email by using the refresh button, next to the failed email
1. Receive email

### CODE REVIEW

**Comment by mikemurray** [comment]
Status update

The app is running again, and tests are passing locally. It is still TBD if the jobs are running as they once were, so more testing will need to be done.

Looking into also converting the job-collection tests to make sure the jobs run as the original author intended.

**Comment by mikemurray** [comment]
@spencern @aaronjudd I'm unable to view the details of the snyk test. It gives me `The organisation does not exist, or you do not have permissions to access it.`

**Comment by aaronjudd** [comment]
@mikemurray did you accept the invitation to the project sent earlier today?

**Comment by mikemurray** [comment]
@aaronjudd that did it 👍

**Comment by nnnnat** [comment]
When I was testing this PR I did see this issue in the email logs.
screen shot 2018-02-16 at 10 09 41 am

I tested it on `release-1.8.0` and didn't see the issue so I guessing it was resolved with this [PR](https://github.com/reactioncommerce/reaction/issues/3756)

**Comment by spencern** [comment]
@nnnnat good catch, that's the same issue that @aaronjudd found yesterday and was resolved in https://github.com/reactioncommerce/reaction/pull/3759

**Comment by mikemurray** [comment]
@nnnnat conflicts resolved.

**Pull request merged**
