### PR TITLE
Adding react-addons-shallow-compare dependency

### PR DESCRIPTION
**Pull request by josx**
Fix https://github.com/reactioncommerce/reaction/issues/2820

### CODE REVIEW

**Comment by zenweasel** [comment]
@josx When I do `meteor npm install` on my local installation I get this package automatically because it is a dependency of `react-avatar`. Can you confirm you are having this problem on a clean install?

**Comment by josx** [comment]
yes, i followed the documentation to start a clean installation, and i got that error.

I have done the following:
```
npm install -g reaction-cli
reaction init
cd reaction
reaction
```

**Comment by zenweasel** [comment]
@josx Yeah, testing with a fresh install I am seeing the same issue. I wonder if we need to bump up `react-avatar` or something though? I hesitate to hardcode a dependency in like that.

**Comment by jshimko** [comment]
The output of `reaction init` spits this out deep in the middle of the npm install...

```
npm WARN react-avatar@2.4.0 requires a peer of react-addons-shallow-compare@^0.14.0 || ^15.0.0 || ^16.0.0 but none was installed.
```

This is because it is only [declared as a peer dependency](https://github.com/Sitebase/react-avatar/blob/master/package.json#L32).  It's [also in the devDependencies](https://github.com/Sitebase/react-avatar/blob/master/package.json#L64) but those don't get installed when you install a package in your app.  

So any time this hasn't been a problem in the past was likely because something else _did_ have it as a hard dependency.  So maybe that has changed in whatever package installed it for us.  Either way, that is a legit dependency for us now, so I guess we need to move forward with this.  On the upside, a peer dependency allows us to pick any version satisfied by `^0.14.0 || ^15.0.0 || ^16.0.0` (which is way better than being stuck with whatever the 3rd party package uses.

**Comment by josx** [comment]
This is a hotfix (right now, you cant install the app smoothly).

[react-addons-shallow-compare](https://www.npmjs.com/package/react-addons-shallow-compare) is legacy react code, so any library using must be replaced with [React.PureComponent](https://facebook.github.io/react/docs/react-api.html#react.purecomponent)

**Comment by jshimko** [comment]
Lovely.  So that means the real fix is a PR to someone else's package.

**Comment by josx** [comment]
Yes i think that.

Also I have checked [readme on react-avatar](https://github.com/Sitebase/react-avatar)  and you need to install react-addons-shallow-compare aside

**Comment by josx** [comment]
BTW I have oponed an issue on react-avatar about this  https://github.com/Sitebase/react-avatar/issues/66

**Comment by mikemurray** [comment]
At the very least, this issue seems to have been fixed in a PR to the marketplace branch. https://github.com/reactioncommerce/reaction/pull/2841

**Comment by josx** [comment]
Ok, so if that code will be on master soon, we can close this PR

**Comment by josx** [comment]
Anyways you have to know that you cant install the app from current master branch

**Pull request merged**
