### PR TITLE
Fix 4343 Cannot set replyTo or other field options when using Reaction.Email.send

### LINKED ISSUE #4343: Cannot set replyTo or other field options when using Reaction.Email.send
## Prerequisites
* [X ] Are you running the latest version?
* [X ] Are you able to consistently reproduce the issue?
* [X ] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description
I am trying to modify a function responsible for sending emails to user by adding **replyTo** option.
After adding the **replyTo** option,the email is received by the user (so function keeps working), no errors appear in console but the **replyTo** option is not included in the fields the user sees in his email software. 

## Steps to Reproduce
1. Go for example to function **sendWelcomeEmail** on *server/methods/accounts/accounts.js*
2. Add a **ReplyTo** option like this:
```
Reaction.Email.send({
    to: userEmail,
    from: "someone@yyy.com",
    replyTo: "someoneElse@xxx.com", // ------- added here -------
    subject: SSR.render(subject, dataForEmail),
    html: SSR.render(tpl, dataForEmail)
  });
```
3. Register again as a new user and see if the email you receive includes the replyTo option

## Possible Solution
Modify nodemailer wrapper to include other options that could be set, for example :  *replyTo*, *references* etc

### Versions
Reaction: 1.12.1

### PR DESCRIPTION
**Pull request by GeorgeLinardis**
Resolves #4343 Cannot set replyTo or other field options when using Reaction.Email.send
Impact: **minor**  
Type: **refactor**

## Issue
I am trying to modify a function responsible for sending emails to user by adding replyTo option.
After adding the replyTo option,the email is received by the user (so function keeps working), no errors appear in console but the replyTo option is not included in the fields the user sees in his email software.

## Solution
Solution is pretty straight forward as you will see.I've added *optionalEmailFields*  which will be destructured and thus added, if user decides that he wants more email options than the from, to, subject, html which are already set by default.

## Testing
1. Open a method used for sending emails for example *sendWelcomeEmail* method  on  server/methods/accounts/accounts.js
2. Add another nodemailer field like *replyTo* option in the Reaction.Email.send function like this:
 ```
Reaction.Email.send({
    to: userEmail,
    from: "someone@yyy.com",
    replyTo: "someoneElse@xxx.com", // ------- added here -------
    subject: SSR.render(subject, dataForEmail),
    html: SSR.render(tpl, dataForEmail)
  });
```
3. Register as a new user and you will see that in the email you'll receive you will have a distinct *reply to* field .

credit @artlimes

### CODE REVIEW

**Comment by zenweasel** [comment]
@GeorgeLinardis I'd like to get this in the next release but looks like we have a conflict to resolve

**Comment by GeorgeLinardis** [comment]
@zenweasel I fixed the conflict, I believe we are ok now.

**Comment by zenweasel** [comment]
Executed this code:
```
Reaction.Email.send({to: "brent@hoover.net", from: "someone@yyy.com", replyTo: "someoneElse@xxx.com", subject: "hello", html: "hello html"});
```
Got this email:
```
Content-Type: text/html
From: someone@yyy.com
To: brent@hoover.net
Reply-To: someoneElse@xxx.com
Subject: hello
Message-ID: <d158c985-7aaf-1561-0eb2-c72abe8c1aae@yyy.com>
Content-Transfer-Encoding: 7bit
Date: Wed, 25 Jul 2018 02:07:49 +0000
MIME-Version: 1.0

hello html
```

**Comment by zenweasel** [comment]
@GeorgeLinardis Had to merge in `release-1.14.0` to get the branch working (due to bugs upstream) but your code seems to be fine

**Pull request merged**
