### PR TITLE
Consistent language in cart or orders

### LINKED ISSUE #2798: Use consistent language for items in cart/order" across the app.
This issue surfaced in #2645 but is older than that.

The language we should be using to talk about the number of items in a cart or an order is 
"Items in cart" or "Items in order"

Anywhere we use the term "Quantity Total" or other terms than the "Items in ..." need to be updated across the app.

This means we need to update at least the following locations:
* Order Completed Page
* Process Order Action View

**Incorrect**
image

image

**Correct**
image

### PR DESCRIPTION
**Pull request by codejockie**
Resolves #2798 

## How to Test
1. Place an order
2. On the order completed page, under the "Your cart" section, you should now see "Items in order" instead of the former "Quantity Total" as shown in the image below:
screen shot 2017-10-25 at 12 45 45

3. Login as admin
4. Approve the order
5. On the Process Order Action View, you should now see "Items in order" instead of the former "Quantity Total" as shown below:
screen shot 2017-10-25 at 12 46 14

### CODE REVIEW

**Comment by machikoyasuda** [comment]
Thank you for using sentence case <3

**Comment by zenweasel** [comment]
@rymorgan These changes seem fine but does somebody need to verify that we got all of them?

**Comment by rymorgan** [comment]
@zenweasel What's the best way of doing that? Can't we search the code to find where we are using this language (Quantity Total)? I can comb through the app and try to find all the places but that seems like I'll probably miss something.

**Comment by aaronjudd** [comment]
@rymorgan all labels are in i18n (en.json) files...

**Comment by rymorgan** [comment]
@codejockie did you double check the i18n (en.json) files for any more instances of 'Quantity total'? Please, do that and let me know all/any places that it's been changed so I can QA.

**Comment by codejockie** [comment]
@rymorgan okay, will do that and get back to you.

**Comment by codejockie** [comment]
@rymorgan I did a search for "Quantity Total" in this this PR, and I came across none as I have replaced the instances where they once existed with the right words

**Comment by rymorgan** [comment]
@codejockie Great, sounds good. Should be good to go then.

**Comment by zenweasel** [comment]
@codejockie You have a conflict you need to resolve, but otherwise good to go.

**Comment by codejockie** [comment]
@zenweasel conflict resolved.

**Comment by spencern** [comment]
After removing unused prop in f959388 this now passes eslint.

**Pull request merged**
