### PR TITLE
Updated dependencies

### PR DESCRIPTION
**Pull request by aaronjudd**
- Nexmo, i18next, meteor-node-stubs, postcss
- moves babel config into package.json

### CODE REVIEW

**Comment by aaronjudd** [comment]
@michael-alade @zenweasel SMS notifications need a little extra testing, updated dependencies.

**Comment by michael-alade** [comment]
@aaronjudd I'll look into it.

**Comment by aaronjudd** [comment]
@michael-alade @spencern @zenweasel review requested asap.

**Comment by zenweasel** [comment]
@michael-alade What was the result of your testing?

**Comment by zenweasel** [comment]
Tested. Twillio is not working for me but it's also not working on `development`

I get a "message: The 'To' number 63921cxxxxx4 is not a valid phone number. Even though I can send texts to that number via their dashboard.

Don't have a Nexmo account, hopefully @michael-alade can test.

**Comment by zenweasel** [comment]
Just noticed that I am seeing this message when starting Meteor on this branch
```
Warning: unable to resolve "module-resolver" in plugins of /Users/brenthoover/Projects/js/reaction/package.json
```

**Comment by aaronjudd** [comment]
@zenweasel I wonder if you saw that while switching branches, versus a full reset and testing of this branch..  this PR moves the .babelrc configuration directly into package.json, so I'd guess that if you did switch branches to test there'd be issues.  Is that an error do restart or something that you saw while testing...? (how to replicate?, I'm not seeing it..)

**Comment by zenweasel** [comment]
@aaronjudd Yes, it's very possible it was from switching branches. Is there  something I need to `reset`? Also it didn't seem to affect anything

**Comment by aaronjudd** [comment]
well, nothing particular you have to do, but I'd think that you would probably at least have to stop/start Meteor in order for the babel configuration to take place.

**Comment by zenweasel** [comment]
Trying it again now and making sure I do a full reset

**Comment by zenweasel** [comment]
Does not appear after full reset and restart

**Comment by michael-alade** [comment]
I am currently testing one more time.

**Comment by aaronjudd** [comment]
@michael-alade please create an issue(s) with steps to reproduce, and an approach for writing tests for anything you discover with the sms package.

**Pull request merged**
