### PR TITLE
Update circle ci meteor version to 1.2.1.

### PR DESCRIPTION
**Pull request by tdecaluwe**
Enables the CI build to complete.

### CODE REVIEW

**Comment by tdecaluwe** [comment]
I hoped this'd work, but it doesn't (yet)... I guess you're still waiting for velocity support?

**Comment by aaronjudd** [comment]
actually this should have worked, the CI is breaking because I introduced a incompatible build version (apparently) yesterday. I'll rerun the CI test with my next updates.

**Comment by tdecaluwe** [comment]
Apparently the releases `METEOR@1.2.1` and `velocity:METEOR@1.2.1` are not the same. The latter does not exist yet. The tests do run with the normal meteor 1.2.1 release. To fix the build however, `reaction-accounts` needs to be patched: reactioncommerce/reaction-accounts#5.

**Comment by tdecaluwe** [comment]
I updated the PR to reflect velocity's official support for meteor 1.2.1 (see meteor-velocity/velocity@fed5599). Tests are running at least.

**Pull request merged**
