### PR TITLE
Fix: Changing the permalink before publishing a product results in "not found"

### LINKED ISSUE #3858: Changing the permalink before publishing a product results in "not found" page
## Prerequisites
* [x] Are you running the latest version?
* [x] Are you able to consistently reproduce the issue?
* [x] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description
Changing the permalink, but not publishing it (not yet), will result in "Not found" template shown if one navigates from product grid to PDP.

## Steps to Reproduce
Please provide starting context, i.e. logged in as a user, configure a particular payment method.
1. As a admin, create a new product
2. Change the handle (permalink)
3. Do not publish
4. navigate to product grid
5. navigate into PDP again
6. See the "Not found" template.

### Versions
Node: 8.2.1
NPM: 5.3.0
Meteor Node: 8.9.4
Meteor NPM: 5.6.0
Reaction CLI: 0.26.4
Reaction: 1.8.1
Reaction branch: master
Docker: 17.03.1-ce

### PR DESCRIPTION
**Pull request by prinzdezibel**
## Issue
Closes #3858

If the permalink of a product is changed, but not published yet, the permalink is assembled with the new (yet unpublished) handle, which leads to the PDP rendering a "Not found" template.
See this animated gif:
unpulished_notfound

## What it does:
- Prevent unpublished handle changes to be used when assembling a link
URL to PDP.

## What is does not:
- Ensure that the "not found" template is rendered in certain situations
(which I don't know what these are exactly) AFTER publishing a product. This is a separate issue: #2249

## Solution
If a product has unpublished changes, they published state is in
products.__published. Use that for building the perma-link from
products.__published.handle.

Impact: major  
Type: bugfix

## Breaking changes
not known

## Testing
1. As a admin, create a new product
2. Change the handle (permalink)
3. Do not publish
4. navigate to product grid
5. navigate into PDP again
6. The product detail page should be shown correctly

### CODE REVIEW

**Comment by aaronjudd** [comment]
@spencern any update on the review for this? 
@prinzdezibel is this related to #3755? 
Does one supercede/block the other?

**Comment by prinzdezibel** [comment]
@aaronjudd  No, these are not dependant. But this very PR does fix a problem where the "Not found" template was shown before publishing (not exactly what the issue is reporting, because this deals with showing the "not found" template erratically after publishing).

TLDR; This PR can be approved independently from #3755, but when applied together with #3755, I haven't seen the "not found" template any longer, not even erratically.

**Comment by prinzdezibel** [comment]
@jshimko maybe we can get this over the finish line. Although I've not been able to reproduce the original issue reliably, so not sure ..

**Comment by prinzdezibel** [comment]
@jshimko This is a quick one-liner, let's move that through. thanks.

**Pull request merged**
