### PR TITLE
Fix for console errors on server

### LINKED ISSUE #3024: Receive error in server console after placing an order for a single shop in multi-shop mode
### Expected behavior
No errors

### Actual Behavior
Receive this error in console:
```
Exception while invoking method 'orders/refunds/list' TypeError: Cannot read property 'paymentMethod' of undefined
    at [object Object].ordersRefundsList (server/methods/core/orders.js:953:27)
    at packages/check.js:128:16
    at [object Object].EVp.withValue (packages/meteor.js:1134:15)
    at Object.exports.Match._failIfArgumentsAreNotAllChecked (packages/check.js:127:41)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1765:18)
    at packages/ddp-server/livedata_server.js:719:19
    at [object Object].EVp.withValue (packages/meteor.js:1134:15)
    at packages/ddp-server/livedata_server.js:717:46
    at [object Object].EVp.withValue (packages/meteor.js:1134:15)
    at packages/ddp-server/livedata_server.js:715:46
    at [object Object]._.extend.protocol_handlers.method (packages/ddp-server/livedata_server.js:689:23)
    at packages/ddp-server/livedata_server.js:559:43
```

This seems to be because this function is returning the paymentMethod for the wrong shop (only the current shop)
https://github.com/reactioncommerce/reaction/blob/0059da1f76b8c51930eedc94a4fd4e9b0c1806ce/server/methods/core/orders.js#L18

### Steps to Reproduce the Behavior
1. Create a marketplace shop and create a product for that shop
1. Place only that product in the cart and checkout
1. Observe the error

### Versions
```
Node: 7.10.0
NPM: 5.3.0
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction CLI: 0.13.1
Reaction: 1.5.0
Reaction branch: brent-fix-issue-2836
Docker: 17.09.0-ce
```

### PR DESCRIPTION
**Pull request by zenweasel**
Resolves #3024 

### To Test

1. Create a second shop and create a product in it
2. Go to the main shop and place an order with only that product in it
3. Observe there are no errors in the console
4. In order confirmation email, observe that the information there is correct

#### Additional testing
5. Add item from main shop and newly created item in step 1 above to cart and checkout
6. Go through with steps 3 and 4 above

### CODE REVIEW

**Comment by kieha** [comment]
@spencern @zenweasel question on this: is the shipping applies per shop or is it only once? I.e. with 2 items from different shops, will the shipping charge be applied per shop or just once for the two items?

**Comment by kieha** [comment]
@zenweasel if you could also review this, would be super. Couldn't add you as a reviewer to your own PR.

**Comment by zenweasel** [comment]
@kieha It's ready to go or?

**Comment by kieha** [comment]
@zenweasel yup.

**Comment by zenweasel** [comment]
@kieha @spencern I made a couple of little changes but this seems to be working for me

**Pull request merged**
