### PR TITLE
release 3.8.0

### PR DESCRIPTION
**Pull request by kieckhafer**
# v3.8.0

Reaction v3.8.0 adds minor features and performance enhancements, and contains no breaking changes since v3.7.1

### Add package link and unlink scripts for easier testing of plugins

`bin/package-link` and `bin/package-unlink` allow you to test local plugins easily and efficiently, no longer needing you to `npm link` packages or adjust your `docker-compose.yml` file.

### Update various `api-plugins`

- api-core ([Release notes](https://github.com/reactioncommerce/api-core/releases/tag/v1.4.0))
- api-plugin-accounts ([Release notes](https://github.com/reactioncommerce/api-plugin-accounts/releases/tag/v1.3.0))
- api-plugin-carts ([Release notes](https://github.com/reactioncommerce/api-plugin-carts/releases/tag/v1.2.0))
- api-plugin-catalogs ([Release notes](https://github.com/reactioncommerce/api-plugin-catalogs/releases/tag/v1.0.2))
- api-plugin-orders ([Release notes](https://github.com/reactioncommerce/api-plugin-orders/releases/tag/v1.2.0))
- api-plugin-shops ([Release notes](https://github.com/reactioncommerce/api-plugin-shops/releases/tag/v1.0.1))
- api-plugin-taxes-flat-rate ([Release notes](https://github.com/reactioncommerce/api-plugin-taxes-flat-rate/releases/tag/v1.0.1))
- api-utils ([Release notes](https://github.com/reactioncommerce/api-utils/releases/tag/v1.14.2))

## Chore

- chore: add package link and unlink scripts ([#6238](https://github.com/reactioncommerce/reaction/pull/6238))
- chore: fix package link script issues ([#6251](https://github.com/reactioncommerce/reaction/pull/6251))

### CODE REVIEW

**Review by aldeed — CHANGES_REQUESTED** [review]
I think the change log should list the plugin updates, maybe with each one linking to the releases page for that plugin? For example https://github.com/reactioncommerce/api-plugin-carts/releases.

Otherwise 👍 but I only reviewed the code, didn't test.

**Comment by aldeed** [comment]
@kieckhafer Also need to figure out why a couple inventory test files started failing with these updates: https://app.circleci.com/pipelines/github/reactioncommerce/reaction/4991/workflows/8811421f-3743-42d3-8c03-afd40409cadf/jobs/70717/steps

Could be a bug introduced in one of the plugins, or possibly a bug fixed such that the test should now expect something different. I didn't dig into it.

**Comment by kieckhafer** [comment]
@aldeed added the plugins to the CHANGELOG. Will look into the test, seems odd it would be triggered in this PR.

**Comment by kieckhafer** [comment]
I locked all the packages to the version number pre-update here, and these tests are still failing. Not sure how we wouldn't catch this before, but it doesn't look like it's being caused by these version updates.

**Review by aldeed — DISMISSED** [review]

**Comment by kieckhafer** [comment]
@aldeed issue fixed. I'm not entirely sure how the tests were passing before with this update, but... they work.

https://github.com/reactioncommerce/reaction/pull/6253/commits/3b244cef0203fedd2b6167718bfdb9eb4aa561fb

**Comment by kieckhafer** [comment]
@manueldelreal @aldeed I think we should hold off on this until #6251 is merged, considering the feature that it's fixing is the primary feature in this release.

**Comment by manueldelreal** [comment]
> @manueldelreal @aldeed I think we should hold off on this until #6251 is merged, considering the feature that it's fixing is the primary feature in this release.

watching #6251 status to start testing this release

**Comment by trojanh** [comment]
@kieckhafer the `Release notes` links are broken as tag should have `v` in them ie. `v1.3.0`
this : 
https://github.com/reactioncommerce/api-plugin-accounts/releases/tag/1.3.0
should be: 
https://github.com/reactioncommerce/api-plugin-accounts/releases/tag/v1.3.0

**Review by manueldelreal — APPROVED** [review]
issues with decoded id's on pdp's haven been resolved.

**Pull request merged**
