### PR TITLE
Release 18

### PR DESCRIPTION
**Pull request by zenweasel**
**Code Complete**: 11/3
**Release**: 11/15

This release will include the following tickets:
#1429 Create Transactional Email templates
#1515 Ability to modify email templates from the dashboard
#1512 Discounts
#431 Email confirmation on guest order entry
#1224 Order progress status is not correctly being updated on the Orders admin page
#1448 Invitation email - User Name should be invited user not logged in user
#1456 [PDP] Revision images
#1457 Revision for Tags
#1455 Revisions UX updates
#1399 disabled search is displaying
#1503 [PDP] Public/Private mode workflow
#500 Products without Variants
#517 PDP Package.layout implementation
#1480 Placeholders for variant inputs
#1502 [PDP] Use "Archive" instead of "Delete"
#1408 Group payment methods into single app card 
Also Resolves: #423

### CODE REVIEW

**Comment by lcampanis** [comment]
It looks like currently Discounts have partially been merged into develop and is causing the following error
```
Debugger listening on port 5050
/Users/lorenzo/.meteor/packages/meteor-tool/.1.4.2_3.11kwaek++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
						throw(ex);
						^

Error: Cannot find module '/imports/plugins/core/discounts/server'
    at Function.require.resolve (packages/modules-runtime.js:129:19)
    at Module.resolve (packages/modules-runtime.js:81:25)
```
Working off of this branch works fine.

**Comment by aaronjudd** [comment]
@lcampanis this is a [WIP] branch, the discount rate hooks aren't in yet.  Use `development` branch instead. Updates coming to this branch very soon though.

**Comment by aaronjudd** [comment]
👍  Approved release-0.18.0 to merge into `development`.

**Comment by kieckhafer** [comment]
👍  looks good to merge to `development`

**Pull request merged**
