### PR TITLE
(ref): remove unused Router code

### PR DESCRIPTION
**Pull request by kieckhafer**
While working on a client project, we discovered this extraneous `Router` code that was left over from a previous refactor, and was causing some conflicts in the client project. 

The code was used to push all routes from all shops into the `Router`. In core Reaction, this is unneeded functionality, as we do not publish all routes from all shops, therefore the code seemed to be doing nothing in it's current state.

Removing it should have no affect on the existing `Router` functionality.

### CODE REVIEW

**Comment by spencern** [comment]
@mikemurray will you give this a review

**Comment by kieckhafer** [comment]
@mikemurray not seeing that, everything looks spaced correctly to me:

cart_js_ ___projects_reaction_foray-reaction

**Comment by spencern** [comment]
@kieckhafer @mikemurray I'm seeing the linter issues in the router as well, not seeing the cart indentation issues and that file isn't changed in this PR.

```
$ eslint .

/Users/spencer/reaction/reaction/imports/plugins/core/router/lib/router.js
  569:9   error  'shops' is assigned a value but never used      no-unused-vars
  582:13  error  'shopCount' is assigned a value but never used  no-unused-vars

✖ 2 problems (2 errors, 0 warnings)
```

not sure why codacy didn't get triggered by those eslint issues.

**Comment by spencern** [comment]
@kieckhafer new one for ya
```
$ eslint .

/Users/spencer/reaction/reaction/imports/plugins/core/router/lib/router.js
  13:10  error  'Counts' is defined but never used  no-unused-vars

✖ 1 problem (1 error, 0 warnings)

```

**Comment by kieckhafer** [comment]
@spencern i think they are all fixed now

**Pull request merged**
