### PR TITLE
Fix for "dirty badge in product grid does not work"

### LINKED ISSUE #398: Deeper security review of the Cart publication
Make sure we aren't leaving an open security hole w/ the Cart pub.

Why take the user id here? (Cart)

```
dig into 'getCurrentCart' that's the heart of session/user.  You can be a registered account (userId) and share your cart across all logged in sessions, or not be a user/ logged out and use just sessions.
```

### LINKED ISSUE #3982: "Dirty badge" in product grid does not work
## Prerequisites
* [x] Are you running the latest version?
* [x] Are you able to consistently reproduce the issue?
* [x]  Did you search the issue queue for existing issue? [Search issues]

## Issue Description
The product grid should display unpublished changes via red dot (a badge). This tells the admin that products shown in the grid hold un-commited changes.

## Steps to Reproduce
1. As an admin , create at least two products
2. Navigate to the product grid
3. Swap the order of the products via drag'n'drop
4. See the red dot on each product that tells the admin about the un-commited (unpublished) changes
5. Reload the page
6. See the dots are gone.

## Possible Solution
Could be similar in scope than this PR: https://github.com/reactioncommerce/reaction/pull/3970 , which is somewhat analogous, but focuses on the `product` subscription

### Versions

Node: 8.2.1
NPM: 5.3.0
Meteor Node: 8.9.4
Meteor NPM: 5.6.0
Reaction CLI: 0.26.4
Reaction: 1.9.0
Reaction branch: release-1.9.0
Docker: 17.03.1-ce

### PR DESCRIPTION
**Pull request by prinzdezibel**
Resolves #3982 
Impact: **major**  
Type: **bugfix**

## Issue
The product grid should display unpublished changes via red dot (a badge). This tells the admin that products shown in the grid hold un-commited changes.

## Solution 

This PR fixes the issue described above AND a problem on master where revisions are over-published (see attached gif).

This change is very similar to what have been done in this companion PR: https://github.com/reactioncommerce/reaction/pull/3970 

##  Changes
Product revisions need to be pushed to client, even if the product document (that contain all other fields besides __revisions) is not published yet.

Just adding
  `this.added("Products", revision.documentId, { __revisions: [revision] });`
in line 400 is not sufficient, because then revisions would be over-published. (Which is actually the case in master branch right now.)

To prevent over-publishing, the Revision observer needs to be more specific and select only those revisions, that are not published AND are shown in the product grid. This constraint resulted in the new function "extendSelectorWithVariants".

## Breaking changes
none expected

## Testing
1. As an admin , create at least two products
2. Navigate to the product grid
3. Swap the order of the products via drag'n'drop
4. See the red dot on each product that tells the admin about the un-commited (unpublished) changes
5. Reload the page
6. All dots should still be there until "Publish all" button is pressed (ensure that no product is selected, otherwise the button will have the text "Publish" and does only affect the currently selected product.

### CODE REVIEW

**Comment by prinzdezibel** [comment]
TODO: Placeholder for gif that shows over-publication of Revision collection on master

**Comment by prinzdezibel** [comment]
@mikemurray Yes, that's what I'm thinking as well. My original intention was to put that into a own ticket to keep the changes more managable. It does also affect the product subscription in the same way ( I assume this is what you mean regarding PR #3825, right?)

**Comment by mikemurray** [comment]
Approved. Fix an issue with sorting on the grid with revisions. Waiting on tests to pass / a double-check review from @willopez

**Comment by willopez** [comment]
Badges are now updating reactively and repositioning products works. 👍

**Pull request merged**
