### PR TITLE
1628 Move Toolbar & Admin View is Dashboard

### LINKED ISSUE #841: Standardize admin toolbar buttons
Remove the ability to add buttons to the admin toolbar through templates.
Define all toolbar buttons in the registry.

### LINKED ISSUE #885: UI Edit mode for everything, not only for top tags
Edit mode works for top tags very well, and I think it could works for product page as well. Also It will give ability for administrators to see the site as regular guest do. 

@aaronjudd @mikemurray, what do you think?

### LINKED ISSUE #1598: Create content menu persists after focus is lost.
### Expected behavior

On focus loss, add menu should disappear.

### Actual Behavior

On focus loss, menu persists. Seems to be two separate menus for the responsive design, i can open it on fullscreen and then make the window smaller to make the menu hide, but when i maximize again it reappears. If i open the menu when the window is small, and then maximize, the same behavior occurs in reverse. If i open it in both the menu never goes away.

screen shot 2016-12-02 at 11 06 58 am

### Steps to Reproduce the Behavior

Click on the "+" button (Create Content). Click anywhere else. Resize screen.

For enhancements or other issues, please describe in as much detail as
possible how the app should be changed and how this would benefit
users/developers

Bad UX to not have the create content menu disappear.

<hr>

If someone can point me to where that code is I can investigate. I'm just starting to hack on this framework so I'm not familiar with where everything is yet.

### LINKED ISSUE #1604: Sidebar disappears at 1200px
### Expected behavior
Sidebar should appear at all widths

### Actual Behavior
Sidebar disappears around 1200 and then reappears at about 1300(?)

### Steps to Reproduce the Behavior
1. Login as admin
1. Resize window to 1200
1. Observe that the sidebar is gone

sidebar

### LINKED ISSUE #1624: Move the publish bar on the PDP to the top of the page
1. Move publish bar to the top. 
2. Use Toggle for customer view with label 'Preview'
3. Undo as icon with tool-tip for those that don't understand the icon
4. Use eye icon for Public/Private

See Attached Mock-up
publish-bar

### LINKED ISSUE #1654: Sidebar behavior fixes
What happens when you transition to a new page? Does the sidebar stay open, close, or show relevant information.

### LINKED ISSUE #1683: Dashboard plugins disappears from dashboard when disabled
### Expected behavior
The plugin should still appear even after it has been disabled

### Actual Behavior
When a plugin is disabled it disappears from the dashboard

### Steps to Reproduce the Behavior
- Go to the dashboard
- Disable any plugin.

### PR DESCRIPTION
**Pull request by mikemurray**
Fixes #1654 
Fixes #1624
Fixes #1598
Closes #1604 ( no longer relevant since it refers to the vertical toolbar )
Closes #1683 ( disable plugin button is removed - for now )
Closes #885 ( we not have a preview toggle that can be used to toggle edit mode )
Closes #841 ( toolbar buttons are now a react component in the new toolbar )

- Adds toolbar to top of screen. Replaces the Vertical toolbar of old
- Publish controls now live in the top toolbar when available
- Move all of dashboard to admin view in sidebar
- Remove icon toolbar (vertical toolbar)

### CODE REVIEW

**Comment by kieckhafer** [comment]
Definitely not a blocker, but something @rymorgan should probably look at... it's very hard to tell the difference on the publish button when there are changes to be published. Maybe we fill the button in when there are pending changes?

**Comment by kieckhafer** [comment]
Seeing this error in the browser console when trying to Archive a product from the PDP using the new publish bar Archive:

```
Exception in delivering result of invoking 'products/deleteProduct': Error
    at http://localhost:3000/app/app.js?hash=56659dcb07118c74cb0ade61ff995e626ef819d3:57622:17
    at MethodInvoker._callback (http://localhost:3000/packages/meteor.js?hash=e3f53db3be730057fed1a5f709ecd5fc7cae1229:1105:22)
    at MethodInvoker._maybeInvokeCallback (http://localhost:3000/packages/ddp-client.js?hash=bc32a166cd269e06a394f9418e0024d805bab379:3557:12)
    at MethodInvoker.dataVisible (http://localhost:3000/packages/ddp-client.js?hash=bc32a166cd269e06a394f9418e0024d805bab379:3586:10)
    at http://localhost:3000/packages/ddp-client.js?hash=bc32a166cd269e06a394f9418e0024d805bab379:4471:7
    at Array.forEach (native)
    at Function._.each._.forEach (http://localhost:3000/packages/underscore.js?hash=cde485f60699ff9aced3305f70189e39c665183c:149:11)
    at Connection._runAfterUpdateCallbacks (http://localhost:3000/packages/ddp-client.js?hash=bc32a166cd269e06a394f9418e0024d805bab379:4470:7)
    at Connection._performWrites (http://localhost:3000/packages/ddp-client.js?hash=bc32a166cd269e06a394f9418e0024d805bab379:4460:10)
    at Connection._flushBufferedWrites (http://localhost:3000/packages/ddp-client.js?hash=bc32a166cd269e06a394f9418e0024d805bab379:4423:10)
```

The archive still works fine from the Grid view.

**Comment by kieckhafer** [comment]
Toggle isn't doing anything for me on the PDP (nor other pages, but I believe the PDP is the only place it should be doing something at the moment).

toggle mov

**Comment by mikemurray** [comment]
Given the `Action View` (the sidebar) is a shared resource. If you open the dashboard your work on the Grid View or PDP page is lost; unless you use `Reaction.pushActionView` in which case you'd get a back button that you could use to go back the the grid settings.

The close button will close the `Action View` as if you were wanting to hide it completely. 

I think the functionality you're looking for is a back button maybe? Though when you click the dashboard button, do you expect a clean navigation stack from that point?

More discussion / testing since we do not yet know how this + saving the `Action View` navigation state to the user profile will affect each other.

**Pull request merged**
