### PR TITLE
Release 1.16.0

### LINKED ISSUE #4441: Eliminate dependency on Velocity
## Issue Description
We currently have a dependency on `Velocity` for animating parts of our client application.
Velocity is a DOM animation library which makes doing some complex animations performant and simple.
We currently use velocity to do one of two things.
1. Animate the cart drawer opacity
2. Animate the background color of changed fields from green and then back to white.

Neither of these animations should need a library to do well or simply and don't justify the added overhead of [94.5kb](https://bundlephobia.com/result?p=velocity-react@1.4.1)

The animations using velocity are contained in one of 6 files
- containers/cartIconContainer.js
- components/metadata/metafield.js
- components/tagItem.js
- components/productAdmin.js
- components/productField.js
- components/variantForm.js

This issue is to eliminate the dependency on Velocity and replace any animations that are using Velocity with another method of animation.

### LINKED ISSUE #4502: Register and sign in buttons in checkout are stuck in loading state
## Issue Description
Register and sign in buttons in checkout are stuck in loading state when email address and password are empty.

## Steps to Reproduce
1. As an anonymous consumer, add a product to your cart.
2. Checkout.
3. Leaving email and password fields empty, click Register.
4. Observe that the button gets stuck at showing the spinner and the browser console displays:

```
Uncaught TypeError: Cannot read property 'trim' of null
    at Object.email (account-validation.js:50)
    at AuthContainer.handleFormSubmit (auth.js:24)
    at SignUp.handleSubmit.event (signUp.js:18)
    at HTMLUnknownElement.callCallback (modules.js?hash=69f0a557d2146cce696d30ed0217c3fe2615ba47:195880)
    at Object.invokeGuardedCallbackDev (modules.js?hash=69f0a557d2146cce696d30ed0217c3fe2615ba47:195918)
    at Object.invokeGuardedCallback (modules.js?hash=69f0a557d2146cce696d30ed0217c3fe2615ba47:195967)
    at Object.invokeGuardedCallbackAndCatchFirstError (modules.js?hash=69f0a557d2146cce696d30ed0217c3fe2615ba47:195981)
    at executeDispatch (modules.js?hash=69f0a557d2146cce696d30ed0217c3fe2615ba47:196241)
    at executeDispatchesInOrder (modules.js?hash=69f0a557d2146cce696d30ed0217c3fe2615ba47:196263)
    at executeDispatchesAndRelease (modules.js?hash=69f0a557d2146cce696d30ed0217c3fe2615ba47:196361)
```
5. Do the same steps for sign in.

## Possible Solution
None

### Versions
```
Node: 8.11.2
NPM: 5.6.0
Meteor Node: 8.11.3
Meteor NPM: 5.10.0
Reaction CLI: 0.29.0
Reaction: 1.14.0
Reaction branch: release-1.14.0
Docker: 18.03.1-ce
```

### LINKED ISSUE #4608: Missed Shops migration for Products template
## Issue
Migration 33 was added in v1.15.0 to change the "products" template name to "Products". It neglected to do this in the Shops collection, which also has layouts stored there. Depending on whether you are upgrading, whether your Packages collection is regenerated on startup, and what version your database is already on, this sometimes leads to the app starting as just a white screen with no errors in the console.

This is actually pretty likely to happen in an upgrade situation.

## Solution
Add another migration to convert the Shops collection.

### PR DESCRIPTION
**Pull request by spencern**
# v1.16.0

### Features
 - feat: return absolute media URLs from GraphQL (#4565)

### Features
 - feat 4571 Replace all Meteor.userId() with util function (#4582)
 - feat: Improve animations and dynamically import animation libraries to reduce bundle size (#4500) .. Resolves #4441

### Fixes
 - fix: reaction error swallowing (#4592)
 - fix: update file-collections dependency from 0.5.0 to 0.6.0 (#4589)
 - fix: null check in email validation (#4520) .. Resolves #4502
 - fix: Add missing Shops.layout migration (#4609) .. Resolves #4608  

## Contributors
Thanks to @pardyot for contributing to this release! 🎉

### CODE REVIEW

**Comment by willopez** [comment]
add_error

**Comment by willopez** [comment]
@dancastellon I believe it's related to the CSS animation refactor.

**Comment by dancastellon** [comment]
@willopez Just pushed the fix!

**Comment by spencern** [comment]
@dancastellon we should not be pushing commits directly to release-1.16.0, but instead to a fix branch and then merged in after accepted review.

**Comment by jeffcorpuz** [comment]
Getting console errors after publishing a product to the catalog:

____
modules.js?hash=1993a0b9b4ab0d2ceed63210284891d0a3ff1e2d:62718 

```
taMask: web3 will be deprecated in the near future in favor of the ethereumProvider 
https://github.com/MetaMask/faq/blob/master/detecting_metamask.md#web3-deprecation
get @ inpage.js:1
equalsConstructorPrototype @ modules.js?hash=1993a0b9b4ab0d2ceed63210284891d0a3ff1e2d:236503
(anonymous) @ modules.js?hash=1993a0b9b4ab0d2ceed63210284891d0a3ff1e2d:236536
index.js @ modules.js?hash=1993a0b9b4ab0d2ceed63210284891d0a3ff1e2d:236546
fileEvaluate @ modules-runtime.js?hash=59942621baf2d3ff23916a0f601008fd2e310b63:349
require @ modules-runtime.js?hash=59942621baf2d3ff23916a0f601008fd2e310b63:248
index.js @ modules.js?hash=1993a0b9b4ab0d2ceed63210284891d0a3ff1e2d:236404
fileEvaluate @ modules-runtime.js?hash=59942621baf2d3ff23916a0f601008fd2e310b63:349
require @ modules-runtime.js?hash=59942621baf2d3ff23916a0f601008fd2e310b63:248
index.js @ modules.js?hash=1993a0b9b4ab0d2ceed63210284891d0a3ff1e2d:236241
fileEvaluate @ modules-runtime.js?hash=59942621baf2d3ff23916a0f601008fd2e310b63:349
require @ modules-runtime.js?hash=59942621baf2d3ff23916a0f601008fd2e310b63:248
index.js @ modules.js?hash=1993a0b9b4ab0d2ceed63210284891d0a3ff1e2d:236048
fileEvaluate @ modules-runtime.js?hash=59942621baf2d3ff23916a0f601008fd2e310b63:349
require @ modules-runtime.js?hash=59942621baf2d3ff23916a0f601008fd2e310b63:248
index.js @ modules.js?hash=1993a0b9b4ab0d2ceed63210284891d0a3ff1e2d:236032
fileEvaluate @ modules-runtime.js?hash=59942621baf2d3ff23916a0f601008fd2e310b63:349
require @ modules-runtime.js?hash=59942621baf2d3ff23916a0f601008fd2e310b63:248
registerCSSInterfaceWithDefaultTheme.js @ modules.js?hash=1993a0b9b4ab0d2ceed63210284891d0a3ff1e2d:235317
fileEvaluate @ modules-runtime.js?hash=59942621baf2d3ff23916a0f601008fd2e310b63:349
require @ modules-runtime.js?hash=59942621baf2d3ff23916a0f601008fd2e310b63:248
initialize.js @ modules.js?hash=1993a0b9b4ab0d2ceed63210284891d0a3ff1e2d:235295
fileEvaluate @ modules-runtime.js?hash=59942621baf2d3ff23916a0f601008fd2e310b63:349
require @ modules-runtime.js?hash=59942621baf2d3ff23916a0f601008fd2e310b63:248
initialize.js @ modules.js?hash=1993a0b9b4ab0d2ceed63210284891d0a3ff1e2d:235283
fileEvaluate @ modules-runtime.js?hash=59942621baf2d3ff23916a0f601008fd2e310b63:349
require @ modules-runtime.js?hash=59942621baf2d3ff23916a0f601008fd2e310b63:248
dayPickerRangeController.js @ dayPickerRangeController.js:1
fileEvaluate @ modules-runtime.js?hash=59942621baf2d3ff23916a0f601008fd2e310b63:349
require @ modules-runtime.js?hash=59942621baf2d3ff23916a0f601008fd2e310b63:248
calendarPicker.js @ calendarPicker.js:1
fileEvaluate @ modules-runtime.js?hash=59942621baf2d3ff23916a0f601008fd2e310b63:349
require @ modules-runtime.js?hash=59942621baf2d3ff23916a0f601008fd2e310b63:248
index.js @ index.js:1
fileEvaluate @ modules-runtime.js?hash=59942621baf2d3ff23916a0f601008fd2e310b63:349
require @ modules-runtime.js?hash=59942621baf2d3ff23916a0f601008fd2e310b63:248
forgotPassword.js @ forgotPassword.js:1
fileEvaluate @ modules-runtime.js?hash=59942621baf2d3ff23916a0f601008fd2e310b63:349
require @ modules-runtime.js?hash=59942621baf2d3ff23916a0f601008fd2e310b63:248
index.js @ index.js:1
fileEvaluate @ modules-runtime.js?hash=59942621baf2d3ff23916a0f601008fd2e310b63:349
require @ modules-runtime.js?hash=59942621baf2d3ff23916a0f601008fd2e310b63:248
plugins.js @ plugins.js:1
fileEvaluate @ modules-runtime.js?hash=59942621baf2d3ff23916a0f601008fd2e310b63:349
require @ modules-runtime.js?hash=59942621baf2d3ff23916a0f601008fd2e310b63:248
(anonymous) @ app.js?hash=e693072880595c1f8d167f32ac3e6d5f34805d98:82651
modules.js?hash=1993a0b9b4ab0d2ceed63210284891d0a3ff1e2d:62718 Warning: Can't call setState on a component that is not yet mounted. This is a no-op, but it might indicate a bug in your application. Instead, assign to `this.state` directly or define a `state = {};` class property with the desired state in the ActionView component.
printWarning @ modules.js?hash=1993a0b9b4ab0d2ceed63210284891d0a3ff1e2d:62718
warning @ modules.js?hash=1993a0b9b4ab0d2ceed63210284891d0a3ff1e2d:62742
warnNoop @ modules.js?hash=1993a0b9b4ab0d2ceed63210284891d0a3ff1e2d:61094
enqueueSetState @ modules.js?hash=1993a0b9b4ab0d2ceed63210284891d0a3ff1e2d:61163
Component.setState @ modules.js?hash=1993a0b9b4ab0d2ceed63210284891d0a3ff1e2d:61208
ActionView.handleResize.debounce @ actionView.js:147
invokeFunc @ modules.js?hash=1993a0b9b4ab0d2ceed63210284891d0a3ff1e2d:14541
trailingEdge @ modules.js?hash=1993a0b9b4ab0d2ceed63210284891d0a3ff1e2d:14590
timerExpired @ modules.js?hash=1993a0b9b4ab0d2ceed63210284891d0a3ff1e2d:14578
setTimeout (async)
leadingEdge @ modules.js?hash=1993a0b9b4ab0d2ceed63210284891d0a3ff1e2d:14549
debounced @ modules.js?hash=1993a0b9b4ab0d2ceed63210284891d0a3ff1e2d:14618
```

____
publishContainer.js:17 

```
publishContainer.js:17 Uncaught TypeError: Cannot read property 'filter' of undefined
    at Object.PublishContainer.handlePublishClick [as onPublishClick] (publishContainer.js:17)
    at PublishControls.handlePublishClick (publishControls.js:106)
    at Button.handleClick.event (button.jsx:25)
    at HTMLUnknownElement.callCallback (modules.js?hash=1993a0b9b4ab0d2ceed63210284891d0a3ff1e2d:174749)
    at Object.invokeGuardedCallbackDev (modules.js?hash=1993a0b9b4ab0d2ceed63210284891d0a3ff1e2d:174787)
    at Object.invokeGuardedCallback (modules.js?hash=1993a0b9b4ab0d2ceed63210284891d0a3ff1e2d:174836)
    at Object.invokeGuardedCallbackAndCatchFirstError (modules.js?hash=1993a0b9b4ab0d2ceed63210284891d0a3ff1e2d:174850)
    at executeDispatch (modules.js?hash=1993a0b9b4ab0d2ceed63210284891d0a3ff1e2d:175110)
    at executeDispatchesInOrder (modules.js?hash=1993a0b9b4ab0d2ceed63210284891d0a3ff1e2d:175132)
    at executeDispatchesAndRelease (modules.js?hash=1993a0b9b4ab0d2ceed63210284891d0a3ff1e2d:175230)
PublishContainer.handlePublishClick @ publishContainer.js:17
handlePublishClick @ publishControls.js:106
Button.handleClick.event @ button.jsx:25
callCallback @ modules.js?hash=1993a0b9b4ab0d2ceed63210284891d0a3ff1e2d:174749
invokeGuardedCallbackDev @ modules.js?hash=1993a0b9b4ab0d2ceed63210284891d0a3ff1e2d:174787
invokeGuardedCallback @ modules.js?hash=1993a0b9b4ab0d2ceed63210284891d0a3ff1e2d:174836
invokeGuardedCallbackAndCatchFirstError @ modules.js?hash=1993a0b9b4ab0d2ceed63210284891d0a3ff1e2d:174850
executeDispatch @ modules.js?hash=1993a0b9b4ab0d2ceed63210284891d0a3ff1e2d:175110
executeDispatchesInOrder @ modules.js?hash=1993a0b9b4ab0d2ceed63210284891d0a3ff1e2d:175132
executeDispatchesAndRelease @ modules.js?hash=1993a0b9b4ab0d2ceed63210284891d0a3ff1e2d:175230
executeDispatchesAndReleaseTopLevel @ modules.js?hash=1993a0b9b4ab0d2ceed63210284891d0a3ff1e2d:175241
forEachAccumulated @ modules.js?hash=1993a0b9b4ab0d2ceed63210284891d0a3ff1e2d:175211
runEventsInBatch @ modules.js?hash=1993a0b9b4ab0d2ceed63210284891d0a3ff1e2d:175372
runExtractedEventsInBatch @ modules.js?hash=1993a0b9b4ab0d2ceed63210284891d0a3ff1e2d:175381
handleTopLevel @ modules.js?hash=1993a0b9b4ab0d2ceed63210284891d0a3ff1e2d:179126
batchedUpdates$1 @ modules.js?hash=1993a0b9b4ab0d2ceed63210284891d0a3ff1e2d:191309
batchedUpdates @ modules.js?hash=1993a0b9b4ab0d2ceed63210284891d0a3ff1e2d:176780
dispatchEvent @ modules.js?hash=1993a0b9b4ab0d2ceed63210284891d0a3ff1e2d:179205
interactiveUpdates$1 @ modules.js?hash=1993a0b9b4ab0d2ceed63210284891d0a3ff1e2d:191364
interactiveUpdates @ modules.js?hash=1993a0b9b4ab0d2ceed63210284891d0a3ff1e2d:176799
dispatchInteractiveEvent @ modules.js?hash=1993a0b9b4ab0d2ceed63210284891d0a3ff1e2d:179182
```

**Comment by zenweasel** [comment]
@spencern Can we add a thank you to @pardyot for #4520?

**Pull request merged**
