### PR TITLE
(chore): update node dependencies

### LINKED ISSUE #3029: review / update all dependencies
Task to run `ncu -a` and update all dependencies when we begin using Meteor 1.6.

Right now, you can't just force update/install because there is varying versions of node deps/engines involved in some of our dependencies, which should be resolved with Meteor 1.6, as this is also an update to Node v8.x

### PR DESCRIPTION
**Pull request by spencern**
Resolves #3029 

## major version bumps:
```
 libphonenumber-js  ^0.4.49  →   ^1.0.7
 babel-jest         ^21.2.0  →  ^22.1.0
 jest               ^21.2.1  →  ^22.1.4
```
We're not currently relying on any of our jest test suite, so `jest`/`babel-jest` shouldn't have material impact on the app. `libphonenumber-js` bumped to 1.0 for the first time, but did not report any breaking changes.

## minor/patch bumps:
```

 authorize-net         ^1.0.11  →   ^1.1.1
 autoprefixer           ^7.1.6  →   ^7.2.5
 braintree              ^2.4.0  →   ^2.5.0
 core-js                ^2.5.1  →   ^2.5.3
 i18next             10.2.2  →   10.3.0
 moment                ^2.19.3  →  ^2.20.1
 nexmo                  ^2.0.2  →   ^2.2.0
 nock                   ^9.1.3  →   ^9.1.6
 node-loggly-bulk       ^2.2.0  →   ^2.2.1
 paypal-rest-sdk        ^1.7.1  →   ^1.8.1
 postcss               ^6.0.14  →  ^6.0.17
 react-dropzone         ^4.2.3  →   ^4.2.7
 react-image-magnify    ^2.3.2  →   ^2.4.1
 react-onclickoutside   ^6.7.0  →   ^6.7.1
 react-select           ^1.1.0  →   ^1.2.1
 react-table            ^6.7.4  →   ^6.7.6
 react-tether           ^0.6.0  →   ^0.6.1
 shopify-api-node       ^2.9.0  →  ^2.10.2
 stripe                 ^5.3.0  →   ^5.4.0
 sweetalert2            ^7.0.5  →   ^7.8.7
 swiper                 ^4.0.6  →   ^4.1.0
 twilio                ^3.10.0  →  ^3.11.2
 velocity-animate       ^1.5.0  →   ^1.5.1
 babel-eslint           ^8.0.2  →   ^8.2.1
 enzyme                 ^3.2.0  →   ^3.3.0
 enzyme-to-json         ^3.2.2  →   ^3.3.1
 eslint-plugin-react    ^7.5.1  →   ^7.6.1
 radium             ^0.19.6  →  ^0.21.2
```

## Not bumped
```
 bootstrap           ^3.3.7  →   ^4.0.0
 react               15.6.2  →   16.2.0
 react-dates        ^15.1.0  →  ^16.2.1
 react-dom           15.6.2  →   16.2.0
```
These were not bumped because `bootstrap` would be a breaking change, and `react` and it's deps should be bumped when we intentionally upgrade to React 16 in https://github.com/reactioncommerce/reaction/issues/3495. Which we should schedule for the next sprint.

### CODE REVIEW

**Comment by zenweasel** [comment]
Seeing some translation issues

**Comment by zenweasel** [comment]
I think you are aware of this already but these Sweetalert alerts have some weird styling now

**Comment by zenweasel** [comment]
Don't understand this exactly but seeing this `setState` warning here now:
```
modules.js?hash=de5a80e9546086ed0b2ee30d7105d0b2c409cfb1:43263 Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the Reaction(NotificationRoute) component.
```

**Comment by zenweasel** [comment]
I can't remove a product from the cart in the cart drawer any longer.

**Comment by spencern** [comment]
@zenweasel 
Seeing the translation issues as well.
I'm not seeing the sweet alert issues anymore with my css push, but did see that issue previously
Also seeing the cart removal issue.

**Comment by zenweasel** [comment]
Seeing this error on the PDP when I add a product as a shop admin and view it as a marketplace admin.
```
modules.js?hash=de5a80e9546086ed0b2ee30d7105d0b2c409cfb1:43263 Warning: `NaN` is an invalid value for the `top` css style property. Check the render method of `Lens`.
```

**Comment by zenweasel** [comment]
Seeing this error when I checkout with a marketplace product
```
Exception while invoking method 'cart/submitPayment' TypeError: Cannot read property '_id' of undefined
    at server/methods/core/cartToOrder.js:93:50
    at Array.map (<anonymous>)
    at DDPCommon.MethodInvocation._copyCartToOrder (server/methods/core/cartToOrder.js:91:22)
    at DDPCommon.MethodInvocation._MethodHooks._wrappers.(anonymous function) (server/api/method-hooks.js:118:70)
    at packages/check.js:128:16
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
    at Object._failIfArgumentsAreNotAllChecked (packages/check.js:127:41)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1765:18)
    at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:1686:15)
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
    at resolve (packages/ddp-server/livedata_server.js:1684:36)
    at new Promise (<anonymous>)
    at Server.applyAsync (packages/ddp-server/livedata_server.js:1683:12)
    at Server.apply (packages/ddp-server/livedata_server.js:1622:26)
    at Server.call (packages/ddp-server/livedata_server.js:1604:17)
    at DDPCommon.MethodInvocation.<anonymous> (server/methods/core/hooks/cart.js:31:32)
    at server/api/method-hooks.js:126:36
    at arrayEach (/Users/brenthoover/Projects/js/reaction/node_modules/lodash/_arrayEach.js:15:9)
    at forEach (/Users/brenthoover/Projects/js/reaction/node_modules/lodash/forEach.js:38:10)
    at DDPCommon.MethodInvocation._MethodHooks._wrappers.(anonymous function) (server/api/method-hooks.js:125:5)
    at packages/check.js:128:16
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
    at Object._failIfArgumentsAreNotAllChecked (packages/check.js:127:41)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1765:18)
    at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
    at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
```

**Comment by zenweasel** [comment]
@spencern Last commit fixed issues with Sweetalert

**Pull request merged**
