### PR TITLE
Fix : Cannot complete checkout on second visit when using Anonymous user

### LINKED ISSUE #3638: Cannot complete checkout on second visit when using Anonymous user
While trying to familiarise myself w/ React Commerce, I thought I'd try some of the acceptance tests documented [here](https://docs.reactioncommerce.com/reaction-docs/master/acceptance-testing).  

### Expected behavior

To be able to successfully complete tests 1A and 1B acceptable tests.

### Actual behavior

After completing 1A and then moving onto 1B, the checkout is stalled by the inability to select `Shipping options`.  A shipping and billing address are present from the order placed in 1A, but the `Shipping options` box is empty on the second checkout which prevents the checkout from proceeding.

### Steps to reproduce the behavior

In my testing, I:

1. Enabled `Flat Rate` shipping followed by the `Free` method
1. Enabled the `Example Provider` payment option

### Workarounds

Either of the following workarounds cause the `Shipping options` box to populate and the checkout to proceed:

1. Delete shipping addresses and re-add
2. Edit shipping addresses, click `Save and continue`

### Versions

```
Node: 8.9.4
NPM: 5.6.0
Meteor Node: 8.9.3
Meteor NPM: 5.5.1
Reaction CLI: 0.26.4
Reaction: 1.7.0
Reaction branch: master
Docker: 17.12.0-ce
```

I had a quick look through existing issues and found https://github.com/reactioncommerce/reaction/issues/674, which appears to be the exact same issue I'm experiencing here.

### PR DESCRIPTION
**Pull request by prinzdezibel**
Closes #3638

Changes:
Whenever the user choose to checkout as anonymous user, the address
book step should be skipped, if there's already a shipping AND billing
address specified for the cart.

Otherwise the address book grid would come up, but both options are
already selected (green check icon). Repeatedly clicking the active
item does not help, one would need to change the address to move beyond
the addressBook workflow step.

### To test:
1A - Place an order for a single product as an anonymous user

- Click on “Basic Reaction Product”
- Click “Add to Cart”
- Click on “Checkout Now”
- Click on “Continue As Guest”
- Fill out address
- Click on “Save and Continue”
- Select “Free Shipping”
- (The Generic Payment method should be expanded by default) Enter any name
- Enter 4242424242424242 for credit card number
- Choose an expiration month
- Choose an expiration year
- Enter 345 as the CV2 code
- Select “Complete your order”
- Verify that you receive the confirmation screen (“Thank You!”)

1B - Place two consecutive orders as an anonymous user

- Follow the instructions for “Place an order for a single product as an anonymous user”
- Return to the home screen by clicking on “Reaction” up in the upper left corner
- Click on “Basic Reaction Product”
- Click “Add to Cart”
- Click on “Checkout Now”
- Select "Continue As Guest"

**EXPECTED: The shipping workflow step should be active now.**

**EDIT 2**:  Please do also check the above another time with stripe payment selected.

### CODE REVIEW

**Comment by prinzdezibel** [comment]
@jshimko Brent asked me to get my code changes reviewed from you.

**Comment by mattt416** [comment]
Hi @prinzdezibel I've made this modification locally but am still running into the reported issue.  I reset the database after making the change but continue to hit the issue.  As I'm unsure if anything needs to be reset/flushed in the JavaScript console, I've tried with a new browser/email combination but still hit the same problem on the 2nd checkout.

**Comment by prinzdezibel** [comment]
@mattt416 Did you have a chance to look into this again? I can't reproduce the problem you're describing.

**Comment by mattt416** [comment]
Hi @prinzdezibel , I just started a new app (`reaction init`), applied your fix, ran `reaction run`, and then went through the steps to replicate this.  I'm still seeing the behaviour from before.  Are there any client-side caches that I would need to flush here, even though I've started with a fresh app?

**Comment by prinzdezibel** [comment]
Hi @mattt416 , can we chat on Gitter? I'd like to go this through with you.

**Comment by prinzdezibel** [comment]
@mattt416  I also fixed it for the case that Stripe as payment option is enabled. Which was obviously the case in your scenario, even if it was not checked active in the settings (I can re-construct your behavior when changing the following values directly in db - which  essentially is a data corruption):

edit_document


I don't know if this is what resulted in the observations that you made, nor do I know if such a db state can happen in an erroneous situation. If so and you know why, I'd be glad to get more details on this.

But as far as the original problem goes: This should be fixed with my latest changes.

Thank you again, Michael.

**Comment by mattt416** [comment]
Hi @prinzdezibel, I just did a db reset on my dummy install and this is what I see:

```
meteor:PRIMARY> db.Packages.find({name: 'reaction-stripe'}).pretty()
{
        "_id" : "LD9s6WgxZqu8otQbx",
        "name" : "reaction-stripe",
        "shopId" : "J8Bhq3uTtdgwZx3rz",
        "icon" : "fa fa-cc-stripe",
        "enabled" : true,
        "settings" : {
                "mode" : false,
                "api_key" : "",
                "reaction-stripe" : {
                        "enabled" : false,
                        "support" : [
                                "Authorize",
                                "Capture",
                                "Refund"
                        ]
                },
                "public" : {
                        "client_id" : ""
                },
                "connectAuth" : {

                }
        },
        "registry" : [
                {
                        "label" : "Stripe",
                        "provides" : [
                                "paymentSettings"
                        ],
                        "container" : "dashboard",
                        "template" : "stripeSettings",
                        "hideForShopTypes" : [
                                "merchant",
                                "affiliate"
                        ]
                },
                {
                        "template" : "stripePaymentForm",
                        "provides" : [
                                "paymentMethod",
                                "marketplacePaymentMethod"
                        ],
                        "icon" : "fa fa-cc-stripe"
                },
                {
                        "route" : "/stripe/connect/authorize",
                        "template" : "stripeConnectAuthorize"
                },
                {
                        "label" : "Stripe Merchant Account",
                        "icon" : "fa fa-cc-stripe",
                        "container" : "dashboard",
                        "provides" : [
                                "marketplaceMerchantSettings"
                        ],
                        "template" : "stripeConnectMerchantSignup",
                        "hideForShopTypes" : [
                                "primary"
                        ]
                }
        ],
        "layout" : null
}
meteor:PRIMARY>
```

Nothing has been toggled in the admin panel yet.

**Comment by prinzdezibel** [comment]
@mattt416 Thanks for hint! this looks like an error. I'm going to file a separate ticket for this.

**Comment by mattt416** [comment]
@prinzdezibel Regarding the actual bug tho -- I've tested this with stripe implicitly enabled, with it explicitly enabled, and with it explicitly disabled, and the 2nd checkout now pops up the shipping selection as expected.  So, tl;dr your fix seems to be working!  👍

**Comment by prinzdezibel** [comment]
@mattt416  Please check your reaction.json file in /private/settings/. I guess there's a wrong default there.

**Comment by mattt416** [comment]
@prinzdezibel Looks like the default is wrong?  https://github.com/reactioncommerce/reaction/blob/master/private/settings/reaction.json.example#L77

**Comment by prinzdezibel** [comment]
@mattt416  that's it !! Thanks for your help. I'm going to file a new ticket for that.

**Comment by mattt416** [comment]
@prinzdezibel Unless the cart code shouldn't be using isStripeEnabled, but rather something that checks if the `enabled` inside reaction-stripe's settings is `enabled`?

**Comment by prinzdezibel** [comment]
@mattt416 yup, not sure which one is the source of truth actually. Not sure why this field is redundant at all. Need to dig into it.

**Comment by zenweasel** [comment]
@prinzdezibel Just to clarify. There should be two `enabled` values there. The top-level one might be better labeled "installed" but it controls whether the payment function would display in the dashboard, the second whether the payment method is actually used during checkout.

**Comment by prinzdezibel** [comment]
i ve been thinking this too, but realized, that toggling stripe on/off
actually alters both booleans. which doesnt quite make sense. also the
plugin appears still in dashboard, even if upper boolean is false

**Comment by zenweasel** [comment]
@prinzdezibel So what's the status of this PR?

**Comment by prinzdezibel** [comment]
ready for approval ;)

Sent from mobile device. Please excuse brevity and typos.

On Feb 8, 2018 12:26 AM, "Brent Hoover" <notifications@github.com> wrote:

@prinzdezibel <https://github.com/prinzdezibel> So what's the status of
this PR?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/reactioncommerce/reaction/pull/3640#issuecomment-363946536>,
or mute the thread

**Comment by aaronjudd** [comment]
@jshimko @prinzdezibel do you think this PR introduced this new behavior?

1__rc__node__and_basic_reaction_product_and_slack_-_reaction_commerce

Was checkout testing completed with anonymous, guest, registered users?
Was checkout testing completed with Avalara, Shippo, multiple payment packages?

**Comment by prinzdezibel** [comment]
@aaronjudd: yes, but should be addressed already by this: https://github.com/reactioncommerce/reaction/issues/3766

**Comment by prinzdezibel** [comment]
@aaronjudd   Tested with avalara, stripe, paypal, shippo.
Tested anonymously and registered. Looks good to me after applying @Akarshit 's PR. Moving to ready again.

**Pull request merged**
