### PR TITLE
Fix translation issues in PDP

### LINKED ISSUE #2676: Translation issues in PDP
### Expected behavior
basic_reaction_product

### Actual Behavior
basic_reaction_product

### Steps to Reproduce the Behavior
1. Login as admin on either `development` or `marketplace` branch
1. Switch your language to German
1. Click on the option edit icon to open the side panel
1. Observe that no fields here are translated.

### Versions
```
Node: 7.10.0
NPM: 5.3.0
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction CLI: 0.11.0
Reaction: 1.4.1
Reaction branch: marketplace
Docker: 17.06.0-ce
```

### PR DESCRIPTION
**Pull request by awadesmoline**
Resolves #2676

I had to manually update the non-English translations from master. This should work now on `marketplace`

### Steps to test
1. Login as admin on `marketplace` branch
1. Select product and go to the PDP
1. Switch your language to German
1. Click on the option edit icon to open the side panel
1. Observe that fields here are translated.
1. Switch to any other language and observe that side panel fields are appropriately translated

### CODE REVIEW

**Comment by zenweasel** [comment]
@awadesmoline How am I able to test this if there are no non-English translations? These translations definitely existed at some point since they are on `master`?

**Comment by awadesmoline** [comment]
I didn’t add the non-English translations because I thought the lingohub service would update them.
I will try and update all of them with the translations from `master` and test.

**Comment by zenweasel** [comment]
This one isn't translated on `master` either but let's go ahead and add the key while we're here?

basic_reaction_product

**Comment by awadesmoline** [comment]
@zenweasel I have added  and Fixed the English key for "Drop file to Upload". tested it with dummy translations for non-English languages and it worked. With LingoHub update, it should translate to other languages.

**Pull request merged**
