### PR TITLE
create launchdock-connect plugin

### LINKED ISSUE #1061: Reset password uses wrong email
For bugs, please fill out the three following sections completely

### Expected behavior
Reset password email should be configured from the shop settings

### Actual Behavior
Reset password emails from address are being influenced by launchdock-connect package settings

### Steps to Reproduce the Behavior
1. Change the shop email to something other than `hello@reactioncommerce.com`
2. Reset your password
3. Email will come from `hello@reactioncommerce.com`

Hard-coded in:
https://github.com/reactioncommerce/launchdock-connect/blob/development/server/email.js#L6

### PR DESCRIPTION
**Pull request by jshimko**
- convert launchdock-connect package into a plugin module
- allow `Accounts.sendVerificationEmail()` to use shop name and email for "from" fields (used to be hard coded)

Also fixes #1061

### CODE REVIEW

**Comment by kieckhafer** [comment]
Everything looks good when manually testing, I am seeing this issue with our tests though:

screen shot 2016-08-03 at 5 01 55 pm

**Comment by mikemurray** [comment]
There are 13 code climate issues. Most are the `keyword-spacing` issue.. not sure if we can fix that yet. Some other are legit though.

**Comment by kieckhafer** [comment]
👍  approved, tests are working for me now, and it seems all non `keyword-spacing` codeclimate issues are resolved.

**Comment by mikemurray** [comment]
👍

**Pull request merged**
