### PR TITLE
Fix for errors while viewing orders made with Braintree

### LINKED ISSUE #2622: [Marketplace] Receive multiple errors in server console when there are Braintree orders
### Expected behavior
No errors in server console

### Actual Behavior
Receive the following errors when visiting the order panel where there have been Braintree orders
```
00:38:40.011Z ERROR Reaction: Cannot read property 'settings' of undefined
  TypeError: Cannot read property 'settings' of undefined
      at getAccountOptions (imports/plugins/included/payments-braintree/server/methods/braintreeApi.js:45:20)
      at getGateway (imports/plugins/included/payments-braintree/server/methods/braintreeApi.js:70:26)
      at Object._BraintreeApi.apiCall.listRefunds (imports/plugins/included/payments-braintree/server/methods/braintreeApi.js:205:19)
      at [object Object]._listRefunds (imports/plugins/included/payments-braintree/server/methods/braintreeMethods.js:142:51)
      at packages/check.js:129:16
      at [object Object]._.extend.withValue (packages/meteor.js:1126:17)
      at Object.exports.Match._failIfArgumentsAreNotAllChecked (packages/check.js:128:41)
      at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1765:18)
      at packages/ddp-server/livedata_server.js:1686:15
      at [object Object]._.extend.withValue (packages/meteor.js:1126:17)
      at packages/ddp-server/livedata_server.js:1684:36
      at [object Object]._.extend.applyAsync (packages/ddp-server/livedata_server.js:1683:12)
      at [object Object]._.extend.apply (packages/ddp-server/livedata_server.js:1622:26)
      at [object Object]._.extend.call (packages/ddp-server/livedata_server.js:1604:17)
      at [object Object].ordersRefundsList (server/methods/core/orders.js:817:12)
      at packages/check.js:129:16
00:38:40.011Z FATAL Reaction: Braintree call failed, refunds not listed
````

### Steps to Reproduce the Behavior
1. Login as admin
1. Set payment processor as Braintree
1. Place order
1. Visit order dashboard and open order panel
1. Observe errors

### Versions
```
Node: 7.10.0
NPM: 5.0.3
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction CLI: 0.11.0
Reaction: 1.5.0
Reaction branch: marketplace
Docker: 17.06.0-ce
commit: b6e18a4b5a35b852bd75648ae395a2f4b77eae81
```

### PR DESCRIPTION
**Pull request by foladipo**
Resolves #2622 .

There was a recurring error in the terminal that was thrown when viewing orders made using Braintree WHILE it wasn't the payment processor in use. A similar error occured for Authorize.net too. These errors were both fixed.

*Test instructions*

### For the Braintree bug:

- Sign in as admin.
- Set Braintree as your payment processor.
- Place a new order.
- Set another payment processor apart from Braintree e.g Authorize.net.
- Open the Orders dashboard. Move the new order from "New" to "Processing".
- Click "Approve" in the orders panel for that product. 
- Click "Capture payment" and then check your terminal for the errors reported in #2622. They should be absent.

### For the Authorize.net bug:
- Sign in as admin.
- Set Authorize.net as your payment processor.
- Place a new order.
- Set another payment processor apart from Authorize.net e.g Braintree.
- Open the Orders dashboard. Move the new order from "New" to "Processing".
- Click "Approve" in the orders panel for that product. 
- Click "Capture payment" and wait. This action should be successfully done, which will result in the display of a form for making refunds or cancelling the order. Also check your terminal for any errors: they should be absent.

### CODE REVIEW

**Comment by mikemurray** [comment]
Updated from `marketplace` and fixed conflicts.

**Comment by zenweasel** [comment]
When testing this with Authorize, I am still getting the endless spinner and "loading refunds". I wonder if there is a better way to handle this.
cart_completed

**Comment by zenweasel** [comment]
Actually it seems like once I get that spinner error the entire order dashboard becomes unresponsive.

**Comment by zenweasel** [comment]
So I think what the solution needs to be is that you should be able to disable some actions (the settings allow this already) but leave the method enabled and throw an error when you try to perform an action you have disabled. This might work already (though I doubt it). It should be relatively easy to implement so I think it's worth doing.

If it gets too hard I might vote for putting this bug on the back burner as we have more impactful bugs to fix.

**Comment by foladipo** [comment]
@zenweasel Just to be clear, you mean we should be able to disable refunds actions here while leaving the payment method (Authorize) enabled, right?

**Comment by zenweasel** [comment]
@foladipo Yes, that's the idea. I can see some user wanting to just turn off the Refund feature since they don't offer refunds on their products.

Generally, you should be able to disable method of the actions for a particular payment provider and it should operate correctly.

But I want to emphasize again, if it's going to take a lot of time let's maybe table this ticket and work on other things.

**Comment by foladipo** [comment]
Ok. I'll give it a shot and give you an update today.

**Comment by foladipo** [comment]
@zenweasel I have fixed the remaining issues as follows:
* if refunds are disabled for a particular payment method, then the refunds form will not show up in the orders panel.
* the "Loading refunds" section is now hidden by default and only shows whenever we are actually loading refunds.

**Comment by foladipo** [comment]
Thanks for the compliment! Glad you liked the fixes.

**Pull request merged**
