### PR TITLE
Fix for variant option not updating when edited

### LINKED ISSUE #2582: Option name does not change when edited
### Expected behavior
When you change the option title (not the label) it should change elsewhere

### Actual Behavior
It does not change unless you delete the existing contents and then click away and then replace it.
basic_t-shirt

### Steps to Reproduce the Behavior
1. Login as admin
1. Create a new product
1. Set the Variant label
1. Change title, label, quantity and price.
1. Observe that the option title shown does not change but remains "Untitled Option" even when you publish

### Versions
```
Node: 7.10.0
NPM: 5.0.3
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction CLI: 0.11.0
Reaction: 1.4.0
Reaction branch: development
Docker: 17.06.0-ce
```

### PR DESCRIPTION
**Pull request by foladipo**
Resolves #2582 

This PR fixes a bug with creating product variant options. Previously, editing a product did not update parts of UI. This bug fixes that.

### Testing steps
* Log in as admin.
* Open the panel for editing a product.
* Create a new variant option and try to edit its `option` or `price` form field. Immediately you hit `Enter`, click elsewhere on the page or hit `Tab`, the UI is updated with the text you added to the form field.

### CODE REVIEW

**Comment by mikemurray** [comment]
This should be going into `marketplace`, right @aaronjudd ?

**Comment by foladipo** [comment]
@mikemurray The initial bug report stated `development` as the branch on which the bug was observed, and that was why I branched off it.

**Comment by zenweasel** [comment]
This fixes the bug but why did you change the titles and the placement of the fields? We would need to get design guidance before doing that.

**Comment by zenweasel** [comment]
@foladipo Can you close this and rebranch from `marketplace`. It's not your mistake but we want all PR's to go into `marketplace` from now on. Thanks.

**Comment by foladipo** [comment]
Ok. I'll rebranch, restore the order of that form and raise another PR.

**Pull request closed without merging**
