### PR TITLE
Fix variant display

### PR DESCRIPTION
**Pull request by Stat1c14**
Fixes issue #2199

### CODE REVIEW

**Comment by zenweasel** [comment]
@Stat1c14 Curious why this PR includes changes to package versions

**Comment by Stat1c14** [comment]
When I first ran 'reaction run', it modified those. They aren't necessary

**Comment by zenweasel** [comment]
@Stat1c14 We don't accept PR's against `master` only `development`. I changed the target branch of your PR

**Comment by zenweasel** [comment]
Closing as this currently works as designed.

**Pull request closed without merging**
