### PR TITLE
Fix "Card not properly implemented" bug

### PR DESCRIPTION
**Pull request by efalayi**
Resolves [#2921](https://github.com/reactioncommerce/reaction/issues/2921)
Cards in action panel have extra space and double lines. And the panel lines don't extend all the way down the page.

`.accounts-table .col-md-3` had padding-left of 5px
`.accounts-table .col-md-9` also had border-right defined as: 1px solid #ccc;

###### Fix
- Remove padding left from `.accounts-table .col-md-3`
- Remove border-right from `.accounts-table .col-md-9`

###### Test
```
Sign in
Navigate to accounts.
```

### CODE REVIEW

**Comment by rymorgan** [comment]
permissions-side-view

**Comment by mikemurray** [comment]
The issue @rymorgan is pointing at is as follows.

The way the orders panel works is how this split between the "big" portion of the action view and the "smaller" detail view.

In the orders panel, you have an independent scrollable area for the "big" and "small" sides. See the below picture.

reaction

Rough example below of how to open.

"big" **Reaction.setActionView**
```
Reaction.setActionView({
  label: "Label",
  i18nKeyLabel: "some.i19n.key.label",
  template: "NameOfRegisteredTamplate",
  data: {}
});
```

"small" **Reaction.setActionViewDetail**
```
Reaction.setActionViewDetail({
  label: "Permissions",
  i18nKeyLabel: "admin.settings.permissionsSettingsLabel",
  data: {}, // Any data you want to pass in, like the context of the user
  template: "memberSettings"
});
```

**Comment by impactmass** [comment]
@mikemurray It's fuzzy memory now....., but I remember when adding the accounts UI running into an issue with "reactivity" that created this whole situation in the first place. I think the issue was around data (either group / account or the combination) getting modified in the small actionViewDetail and not immediately reflecting big actionView. This might not help much but just throwing it out there in case it speeds this up.
I just went with this then, as the accounts work was holding up other things.

**Comment by rymorgan** [comment]
I made a separate issue for the further fixes here: https://github.com/reactioncommerce/reaction/issues/2963

**Comment by mikemurray** [comment]
@impactmass When you pass `data` into the action view, it's not meant to be reactive. The registered component/container component passed into `template` is then responsible for setting up its own tracker to then take that data and use it to query a reactive data source.

**Comment by mikemurray** [comment]
So essentially, if you clicked on a group to the right, you'd pass in 

```
Reaction.setActionViewDetail({
  template: "groupSidebar"
  data: { groupId: "1234" }
});
```

Then in `groupSideba`r, you would have a composer, that subscribed to groups, takes in that data as a prop, and does a query for that actual group data.

**Comment by spencern** [comment]
@mikemurray you've got comments here, but no review? Should this be merged?

**Comment by mikemurray** [comment]
@spencern Those comments are better served in https://github.com/reactioncommerce/reaction/issues/2963. This PR is fine to merge.

**Pull request merged**
