### PR TITLE
Wrong subject for generated emails

### LINKED ISSUE #3575: Wrong email email subject for generated mails
### Expected behavior
Emails should get their subject from the Templates collection. This does not happen for the email template `accounts/verifyEmail` and `accounts/verifyUpdatedEmail`. 
I would expect the emails to the subject `{{shopName}}: Please verify your email address`
and `Verify your new email address`.

### Actual behavior
An email with the default subject `A message from {{shop.name}}` is sent.

### Steps to reproduce the behavior

```
$ reaction reset
$ # please set REACTION_EMAIL in settings.json
$ # please make sure the MAIL gateway is properly configured in reaction.json
$ export NODE_TLS_REJECT_UNAUTHORIZED=0 && export REACTION_SECURE_DEFAULT_ADMIN=true && reaction
$ # Check your inbox
```

### PR DESCRIPTION
**Pull request by duanhong169**
Fixes wrongly sent emails with default subject instead of customized version from Templates collection

Closes #3575 

### How to Test
```
$ reaction reset
$ # please set REACTION_EMAIL in settings.json
$ # please make sure the MAIL gateway is properly configured in reaction.json
$ export NODE_TLS_REJECT_UNAUTHORIZED=0 && export REACTION_SECURE_DEFAULT_ADMIN=true && reaction
$ # Check your inbox. Subject should read: {{shopName}}: Please verify your email address
```

### CODE REVIEW

**Comment by prinzdezibel** [comment]
Tested and verified that this PR works.

**Comment by spencern** [comment]
@prinzdezibel @duanhong169 
The title and body of this PR suggest that the fixes are typos, but the code in this PR is changing how the app works. I'd like more details on what is wrong (e.g. bug report), how we know it's wrong, and how we know this solution fixes it before merging this PR in.

**Comment by prinzdezibel** [comment]
@spencern  will do

**Comment by prinzdezibel** [comment]
### How to Test
$ reaction reset
$ # please set REACTION_EMAIL in settings.json
$ # please make sure the MAIL gateway is properly configured in reaction.json
$ export NODE_TLS_REJECT_UNAUTHORIZED=0 && export REACTION_SECURE_DEFAULT_ADMIN=true && reaction
$ # Check your inbox

**Pull request merged**
