### PR TITLE
More consistent Usage of ES6+ Code

### PR DESCRIPTION
**Pull request by DomAmato**
Resolves N/A
Impact: **minor**  
Type: **style|refactor|chore**

## Issue

Just uses more consistent ES6+ grammar such as 
- Using includes instead of indexOf
- Property Shorthand
- Default parameters

## Solution

N/A

## Breaking changes

No breaking changes or functional changes

## Testing

No new testing, tested on circleci and tests passed

### CODE REVIEW

**Comment by DomAmato** [comment]
Thanks for changing the branch I forgot about it while I was filling out the PR form

**Comment by aldeed** [comment]
Thanks @DomAmato. You will have to merge in latest `develop` to fix conflicts.

While we do want to move toward using modern patterns, I don't think we're comfortable merging this many changes of functions to arrow functions, which may cause subtle bugs. If any of the functions use `this` inside them, you have now changed the value of `this`. And in JS, if there aren't tests covering it, this may not be noticeable until that code is executed. Were you checking for this when making these changes?

You will also need to sign all of your commits while rebasing. See https://github.com/reactioncommerce/reaction-component-library/blob/master/docs/contributing.md#signing-your-commits

**Comment by zenweasel** [comment]
Also from the Mocha docs:

```
Passing arrow functions (aka "lambdas") to Mocha is discouraged. Lambdas lexically bind this and cannot access the Mocha context.
```

**Comment by DomAmato** [comment]
Perhaps it would be best if I drop the arrow function changes since sifting through it and troubleshooting it might be more problematic?

**Comment by aldeed** [comment]
@DomAmato Yes if you can remove those it will be easier to review and approve. You can feel free to force push on this PR branch if necessary.

**Comment by DomAmato** [comment]
ok i squashed the commits since it was easier to sign it once and removed all the arrow function changes

**Comment by DomAmato** [comment]
fixed the merge conflicts that came about since I last updated everything. Let me know if there is anything else I need to do pending approval

**Comment by aldeed** [comment]
Thanks @DomAmato. I looked through the changes. All of the changes to the app source code are fine, but some files in `.reaction/jsdoc` directory were changed. Those files are for the API docs and I don't know for sure if any of the jsdoc templates go through Babel or can use ES6+. I suspect they should remain ES5 pending a larger project to update those.

Can you remove those files from this PR? After that it should be OK to merge.

**Comment by DomAmato** [comment]
ok i removed those changes that affected those files

**Comment by aldeed** [comment]
Waiting until next week to merge but looks good now.

**Comment by cos** [comment]
@aldeed, fixed the alignment conflict. Ready for merge again.

**Pull request merged**
