### PR TITLE
(docs): namespace Meteor/ui methods into Methods/ui

### PR DESCRIPTION
**Pull request by machikoyasuda**
## what this PR does
1. adds `Methods/ui` namespace
2. adds `server/api/core/ui` methods to this namespace

## how that renders
screen shot 2017-11-07 at 11 27 00 am
screen shot 2017-11-07 at 11 27 03 am

### CODE REVIEW

**Comment by machikoyasuda** [comment]
A lot of this code is not being used right now, so maybe we can use this PR to discuss whether to remove the code and the theme editor. We could always bring it back via Git.

@spencern @aaronjudd @mikemurray

**Comment by spencern** [comment]
I'd vote to remove any of this that we're not using.

**Comment by zenweasel** [comment]
We already have this PR regarding removing the theme editor: https://github.com/reactioncommerce/reaction/issues/2468

**Comment by spencern** [comment]
@machikoyasuda Is there anything in this PR that _should_ get merged if we're going to be removing the theme editor? Does this PR need to get updated to reflect that goal?

**Comment by mikemurray** [comment]
@machikoyasuda Removed myself as a reviewer as I will not be able to check the status of this over the next week.

**Comment by aaronjudd** [comment]
@machikoyasuda do you want to keep this PR open? is it still WIP? should we merge?

**Comment by machikoyasuda** [comment]
It's not WIP. But maybe we should add a new ticket to discuss how to document and communicate unused methods in core and how we plan to deprecate them.

**Comment by mikemurray** [comment]
@aaronjudd @spencern 

Are we keeping the theme editor in any capacity? If not. Then we should remove it and close this PR.

**Comment by spencern** [comment]
@mikemurray I think @aldeed removed the remaining meteor packages that were associated with the old theme editor in a recent PR

**Comment by spencern** [comment]
I'd vote to close this PR but I think we should create an issue to remove any remaining theme editor code as well if we go that direction and this PR serves as a decent reminder to do that.

**Comment by zenweasel** [comment]
I think we have this issue already: https://github.com/reactioncommerce/reaction/issues/2468 that's in the performance sprint

**Comment by machikoyasuda** [comment]
Closing this PR b/c of https://github.com/reactioncommerce/reaction/issues/2468

**Pull request closed without merging**
