### PR TITLE
Release 0.20.0

### PR DESCRIPTION
**Pull request by kieckhafer**
Release 0.20.0 will focus on bug fixes and polish.

https://waffle.io/reactioncommerce/reaction?milestone=v0.20.0

# Major Features
- Added UI to allow switching between templates on the Product Detail Page ( #1909 )
- Avalara Tax integration ( #1870 )

## Other Features
- New `meta` key in registry ( #1865 ) 
-- Allow package registry to override default meta title ( #1865 ) 
-- Allow packages to determine the size of their `actionView` panel
- Better organization of localization options ( #1947 )

## Other Changes / Fixes
- Convert various dashboard panels to React ( #1848 , #1854 , #1947 )
- Add switch component to list item in dashboard ( #1936 )
- Various Lint fixes ( #1937 )
- Add feedback / loading spinner when waiting on refund data ( #1926 )
- Update product handle when title changes ( #1898 )
- Fix Sold Out / Low Inventory warning always showing on products in search view ( #1904 )
- Add context to actionView / sidebar throughout checkout process ( #1932 , #1956 )
- Remove inventory subscription that is not in use (  #1951 )
- Get package data by shopId, in addition to package name ( #1949 )
- Localization of currency in order emails ( #1957  )
- Updates to i18n translations ( #1977 )
- Fix Login Services settings panel ( #1991  )
- Fix issue where search results don't link to PDP ( #1984 )
- Update to Meteor 1.4.3.2 ( #1992 )

## Breaking Changes
- #1914 - We have removed `react-bootstrap` from our `npm` packages. If you need `react-bootstrap`, you can re-add it to your dependencies.

## Contributors

@reactioncommerce/core
@reactioncommerce/engineering 
@lcampanis 
@hrath2015

### CODE REVIEW

**Comment by zenweasel** [comment]
I'm still seeing the endless spinner when saving settings in the SMS panel

**Comment by zenweasel** [comment]
This might be a one-off, but if I am in the Email settings panel I see this error:
```
Warning: Failed prop type: Invalid prop `data` of type `string` supplied to `EmailTableColumn`, expected `object`.
    in EmailTableColumn (created by GridRow)
    in GridRow (created by GridRowContainer)
    in GridRowContainer (created by GridTable)
    in tbody (created by GridTable)
```

**Comment by zenweasel** [comment]
I'm still seeing the error when the Email logging panel closes every time an email is sent (aka the publication is updated). If this isn't a blocker we should create an issue for it.

**Comment by zenweasel** [comment]
If I go to `Login Services` and click on Update Settings I get this server error. Not sure why those update settings buttons are there?

reaction


```
Exception while invoking method 'accounts/updateServiceConfiguration' MongoError: '$set' is empty. You must specify a field like so: {$set: {<field>: ...}}
    at Object.Future.wait (/Users/brenthoover/.meteor/packages/meteor-tool/.1.4.2_7.1uflov0++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:449:15)
    at [object Object].<anonymous> (packages/meteor.js:213:24)
    at [object Object].MongoConnection.(anonymous function) [as update] (packages/mongo/mongo_driver.js:774:49)
    at [object Object].update (packages/mongo/collection.js:581:29)
    at [object Object].Mongo.Collection.(anonymous function) (packages/aldeed_collection2-core.js:232:19)
    at [object Object].Mongo.Collection.(anonymous function) [as update] (packages/dispatch_run-as-user.js:325:19)
    at [object Object].upsert (packages/mongo/collection.js:668:15)
    at [object Object].Meteor.methods.accounts/updateServiceConfiguration (server/methods/accounts/serviceConfiguration.js:16:50)
    at packages/check.js:130:16
    at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
    at Object.exports.Match._failIfArgumentsAreNotAllChecked (packages/check.js:129:41)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1734:18)
    at packages/ddp-server/livedata_server.js:719:19
    at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
    at packages/ddp-server/livedata_server.js:717:40
    at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
    at packages/ddp-server/livedata_server.js:715:46
    at [object Object]._.extend.protocol_handlers.method (packages/ddp-server/livedata_server.js:689:23)
    at packages/ddp-server/livedata_server.js:559:43
    - - - - -
    at Function.MongoError.create (/Users/brenthoover/.meteor/packages/npm-mongo/.2.2.16_1.d514h5++os+web.browser+web.cordova/npm/node_modules/mongodb-core/lib/error.js:31:11)
    at toError (/Users/brenthoover/.meteor/packages/npm-mongo/.2.2.16_1.d514h5++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/utils.js:114:22)
    at /Users/brenthoover/.meteor/packages/npm-mongo/.2.2.16_1.d514h5++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/collection.js:1048:67
    at /Users/brenthoover/.meteor/packages/npm-mongo/.2.2.16_1.d514h5++os+web.browser+web.cordova/npm/node_modules/mongodb-core/lib/connection/pool.js:455:18
    at nextTickCallbackWith0Args (node.js:436:9)
    at process._tickCallback (node.js:365:13)
```

**Comment by zenweasel** [comment]
If I load the "Social" panel, it's empty and I get this error?
```
TypeError: Cannot read property 'expanded' of undefined
    at SettingsCard.get (settingsCard.js:58)
    at SettingsCard.render (settingsCard.js:76)
    at modules.js?hash=505ad10…:97285
    at measureLifeCyclePerf (modules.js?hash=505ad10…:96564)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (modules.js?hash=505ad10…:97284)
    at ReactCompositeComponentWrapper._renderValidatedComponent (modules.js?hash=505ad10…:97311)
    at ReactCompositeComponentWrapper.performInitialMount (modules.js?hash=505ad10…:96851)
    at ReactCompositeComponentWrapper.mountComponent (modules.js?hash=505ad10…:96747)
    at Object.mountComponent (modules.js?hash=505ad10…:89672)
    at ReactCompositeComponentWrapper.performInitialMount (modules.js?hash=505ad10…:96860)
```

**Comment by aaronjudd** [comment]
Dear GitHub, please provide a button to turn @zenweasel's comments into issues.

**Comment by aaronjudd** [comment]
Able to replicate the "Login Services", configuration forms have all disappeared, and the $set error.

**Comment by zenweasel** [comment]
If I go into "Accounts" and try to send an invite, I am getting "Username already exists" for any email I enter there.

**Comment by zenweasel** [comment]
Tax code dropdown is not properly styled when populated:

basic_reaction_product

**Comment by kieckhafer** [comment]
Created issue #1985 to deal with the email panel closing

**Pull request merged**
