### PR TITLE
Release 1.4.0 (#2558)

### PR DESCRIPTION
**Pull request by spencern**
Merge 1.4.0 into development

### CODE REVIEW

**Comment by zenweasel** [comment]
I think I speak for everyone when I say, WHY? (why is this diff so large?)

**Comment by spencern** [comment]
@zenweasel I had that same thought. Should this be done by just merging locally and pushing?

**Comment by zenweasel** [comment]
I _think_ you end up with the same result? I think it's just this diff display that's messed up. I think that's what we normally do though?

**Comment by spencern** [comment]
Closed in favor of doing it locally.

**Pull request merged**
