### PR TITLE
more email templates

### PR DESCRIPTION
**Pull request by kieckhafer**
Having issues with the last PR, so making a new one.

### CODE REVIEW

**Comment by kieckhafer** [comment]
This, along with a few others, fixes #423, allowing email template editing in the dashboard.

**Comment by aaronjudd** [comment]
@kieckhafer did you want `name` in the template editor to be editable? Wasn't this supposed to be disabled?

**Comment by aaronjudd** [comment]
how would I create a new email template (say for another language), based on an existing one? 
(or is that an enhancement?)

I also was able to get an empty update screen from the settings in the dashboard card, but the form is not functional. 
dashboard_and_slack_-_reaction

**Comment by zenweasel** [comment]
Seeing this error in the server console after placing an order

```
03:08:52.788Z ERROR Reaction: Error in orders/sendNotification for order W2BGyczBMJoqQ9egH
  Error: Access Denied [403]
      at [object Object].ordersRefundsList (server/methods/core/orders.js:857:13)
      at packages/check.js:130:16
      at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
      at Object.exports.Match._failIfArgumentsAreNotAllChecked (packages/check.js:129:41)
      at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1709:18)
      at packages/ddp-server/livedata_server.js:1625:18
      at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
      at Server.apply (packages/ddp-server/livedata_server.js:1624:45)
      at Server.call (packages/ddp-server/livedata_server.js:1567:17)
      at packages/kadira:flow-router-ssr/server/plugins/ssr_data.js:67:23
      at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
      at Object.Meteor.(anonymous function) [as call] (packages/kadira:flow-router-ssr/server/plugins/ssr_data.js:66:44)
      at [object Object].ordersSendNotification (server/methods/core/orders.js:390:33)
      at packages/check.js:130:16
      at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
      at Object.exports.Match._failIfArgumentsAreNotAllChecked (packages/check.js:129:41)
      at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1709:18)
      at packages/ddp-server/livedata_server.js:1625:18
      at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
      at Server.apply (packages/ddp-server/livedata_server.js:1624:45)
      at Server.call (packages/ddp-server/livedata_server.js:1567:17)
      at packages/kadira:flow-router-ssr/server/plugins/ssr_data.js:67:23
```

**Comment by zenweasel** [comment]
When editing a template and hitting "Update", I am getting an error saying the name field is missing even though it's right there.

templates

**Comment by aaronjudd** [comment]
👍  @kieckhafer need to track the remaining couple of issues needing cleanup.. 

- [ ] adding new templates
- [ ] form validation on template editor

**Pull request merged**
