### PR TITLE
Hide user menu

### PR DESCRIPTION
**Pull request by priezz**
Hide user menu after clicking on any link, including "add product"

### CODE REVIEW

**Comment by aaronjudd** [comment]
👍

**Comment by zenweasel** [comment]
Approved - tested and works as expected. Branch needs to be updated before it can be merged however.

**Comment by priezz** [comment]
> Branch needs to be updated before it can be merged however.

@zenweasel, do I need to do something for that?

**Comment by zenweasel** [comment]
@priezz Yes, you need to merge the current `development` branch into your branch and resolve any conflicts.

**Comment by aaronjudd** [comment]
Also, a new feature from GitHub is `Allow edits from maintainers`.  See: https://github.com/blog/2247-improving-collaboration-with-forks

**Pull request merged**
