### PR TITLE
Update current user's name on Navbar and profile page when address is added.

### LINKED ISSUE #2445: Navbar profile no longer shows user's name
Navbar Profile always says either "Admin" or "Guest", it no longer says my name / initials / display name.

I don't see this being an issue for "Admin" (although I liked seeing my initials insteadd), but I think it's kind of impersonal for registered non-admins to always say "Guest".

reaction
reaction

### PR DESCRIPTION
**Pull request by awadesmoline**
This resolves #2445 

### Steps to test

1. Sign in as Guest or Admin
1. Update your profile and create a new address
1. Observer the display name change on profile page and navbar

### CODE REVIEW

**Comment by zenweasel** [comment]
When I log in I briefly see my name and then it goes back to just "Admin"

login_name

**Comment by zenweasel** [comment]
Still not working for me. Can you test with setting user information in environment variables? That's how I have my system set up.

**Comment by awadesmoline** [comment]
Paused work on this to finish a Critical Issue.

**Comment by awadesmoline** [comment]
Hi @zenweasel this should work now. Please test again.

**Pull request merged**
