### PR TITLE
[WIP] Merge development marketplace two

### PR DESCRIPTION
**Pull request by spencern**
Merge development / 1.5 into marketplace take 2.

Tests pass and the app loads, but we've got some errors in certain areas..

The new accounts / groups admin section seems to be the main area throwing errors, but the analytics section seems to have been reset to the old panel as well, so there may be other problems.

### CODE REVIEW

**Comment by impactmass** [comment]
From what I've observed re: the last commit about the warning, the lint rule at play (https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-multi-comp.md) enforces one component per file (even for func style stateless component. So it's treating the `Cell` field in that particular object as a new comp declaration. 

I've found that when the component is changed from func style to Class the warning stops. I can do that, or another option is to update/extend the rule with  `{ "ignoreStateless": <boolean> }`.

**Comment by aaronjudd** [comment]
I think this should be merged, I see two main issues, there's some UI issues in the account login and the accounts @impactmass does not load.

**Comment by spencern** [comment]
@jshimko and @impactmass are working through a few of the merge related issues and then will merge it after they are done cleaning it up

**Comment by jshimko** [comment]
The issues mentioned by @aaronjudd should be fixed now.  And there's a decent possibility that I fixed most of #2593 because I removed all of the `PureComponent` instances that were blocking re-renders of components when the language changed.

**Comment by spencern** [comment]
Tested this again after the merges and groups works now as it did before. With @aaronjudd's approval above I'm gonna go ahead and merge this so we can get the rest of our outstanding marketplace branches updated and merged

**Pull request merged**
