### PR TITLE
refactor: use docker exec instead of docker-compose

### PR DESCRIPTION
**Pull request by ghost**
use conainers started with run command such as npm debug scripts

Signed-off-by: Josh Habdas <jhabdas@protonmail.com>

Impact: **minor**
Type: **refactor**

## Issue
API package linking scripts does not allow linkage of containers started with `docker-compose run` commands without using `--name api`, which is not intuitive and [requires a look-up](https://docs.reactioncommerce.com/docs/3.2.0/testing-debugging-server-code) in the docs.

Without `--name api` added, the package link script currently outputs the following error (actual docker output squelched presumably by bash strict mode, making the error harder to debug):

```shell
\nUsing local package path /Users/jos/Developer/reaction-development-platform/api-plugins/api-plugin-files
If this is not correct, specify the correct path as the second argument.\nbin/package-link: line 70: ../api-plugins/api-plugin-files: Is a directory
Copying  package code into container...ERROR: No container found for api_1
```

## Solution
Enhance package linking scripts so they may be used against API container run without `--name api`. Also cleans up some shellcheck issues and fixes a cosmetic bug where package wasn't printed to stdout.

## Breaking changes
None

## Testing
1. Start API for debugging: `dcr --service-ports api npm run inspect:docker
2. Link an API module for development: `bin/package-link @reactioncommerce/api-plugin-files`
2. Update an API module for development: `bin/package-update @reactioncommerce/api-plugin-files`
2. Unlink an API module for development: bin/package-unlink @reactioncommerce/api-plugin-files
2. Confirm you receive output like:

<details>
<summary>Expected output</summary>

```shell
❯ bin/package-link @reactioncommerce/api-plugin-files
Using local package path /Users/jos/Developer/reaction-development-platform/api-plugins/api-plugin-files
If this is not correct, specify the correct path as the second argument.
Copying @reactioncommerce/api-plugin-files package code into container...
Linking package into API...
@reactioncommerce/api-plugin-files@0.0.0-development+d182d7ad published in store.
Package @reactioncommerce/api-plugin-files@0.0.0-development+d182d7ad linked ==> /usr/local/src/app/node_mo
dules/@reactioncommerce/api-plugin-files.
Restarting API...
   ~/Dev/reaction-development-platform/reaction on    v3.10.0-custom !2 ··· took   13s at   03:44:08
❯ bin/package-link @reactioncommerce/api-plugin-files
Using local package path /Users/jos/Developer/reaction-development-platform/api-plugins/api-plugin-files
If this is not correct, specify the correct path as the second argument.
Copying @reactioncommerce/api-plugin-files package code into container...
Linking package into API...
@reactioncommerce/api-plugin-files@0.0.0-development+d182d7ad published in store.
Package @reactioncommerce/api-plugin-files@0.0.0-development+d182d7ad linked ==> /usr/local/src/app/node_mo
dules/@reactioncommerce/api-plugin-files.
Restarting API...
   ~/Dev/reaction-development-platform/reaction on    v3.10.0-custom !2 ··· took   16s at   03:52:31
❯ bin/package-link @reactioncommerce/api-plugin-files
Using local package path /Users/jos/Developer/reaction-development-platform/api-plugins/api-plugin-files
If this is not correct, specify the correct path as the second argument.
Copying @reactioncommerce/api-plugin-files package code into container...
Linking package into API...
@reactioncommerce/api-plugin-files@0.0.0-development+d182d7ad published in store.
Package @reactioncommerce/api-plugin-files@0.0.0-development+d182d7ad linked ==> /usr/local/src/app/node_mo
dules/@reactioncommerce/api-plugin-files.
Restarting API...
```

</details>

Incorporating this change makes it less likely users will customize the NPM manifest to modify the scripts, improves the console output and simplifies the use of the package linker scripts.

### CODE REVIEW

**Comment by balibebas** [comment]
Same issue with `package-update` script; changes there to be included in this pull pending review.

**Comment by kieckhafer** [comment]
@balibebas Trying to test this out, I'm running your script in step one above, but then get this output when trying to link a package:
```
bin/package-link: line 69: ../api-plugins/api-plugin-files: is a directory
Copying  package code into container...
ERROR: No container found for api_1
```

It looks like my `api` container is not `api_1` in this case, when I `docker ps`, it's: `reaction_api_run_51265b36adbc`

So it seems I'll still need to look up my container to get the correct name, unless I'm doing something wrong here.

**Comment by ghost** [comment]
Interesting. The purpose of using `docker exec` over `docker-compose` is to bypass the need to pass `--name` and those with `_run_foo` are what this pull aims to allow. I'll run then again tomorrow and make sure the pull is on the right commit.

**Comment by ghost** [comment]
Checked out commit again to retest. Looks good on my end. The error seen is what happens when `docker exec` is not used—otherwise the script changes in this pull should be pulling a container ID and not referencing a service `--name` as suggested. @kieckhafer could you verify: 1) you do not see more than one ID output when running command `echo $(docker-compose ps api)` before running the script and 2) your node volume is cleared out?

composeexec-reaction-fs8

Tested here against Reaction `v3.9.0` and `3.10.0` with success as pictured above.

**Comment by ghost** [comment]
Closing due to age.

**Comment by loan-laux** [comment]
Too bad, I think we'd benefit from this being merged. Whose court was the ball in? Can this be reviewed & merged?

**Comment by nnnnat** [comment]
@Akarshit think you can take a look at this if you've got some capacity this week or next?

**Comment by ghost** [comment]
Happy to pair on the +8 TZ if it helps. This is primarily a DX change to simplify CLI usage.

**Comment by Akarshit** [comment]
@balibebas Hey! Somehow this slipped my notification queue. Apologies.
I will get this tested and merged by tomorrow :)

**Comment by Akarshit** [comment]
@balibebas I was testing this and I think I understand what the problem could be. My old reaction was running(from `make` script) and then I stopped it and started with `dcr`.
Now `docker-compose ps -q api` gives the container id of the first service(which has already been killed).
Screen Shot 2021-03-16 at 12 18 29 PM
Now if everyone was to use `dcr` this won't be a problem, but devs switch between `dcr` and `make` frequently. So maybe we can look into modifying the command to get the id of the container that's still running.
What do you think?

**Comment by ghost** [comment]
Ah that makes sense. I don't think I even realized there was a Make task to handle this. I'll brain on it a little more to see what works best. Appreciate the quick feedback @Akarshit.

**Comment by Akarshit** [comment]
@balibebas No problem at all. Let me know if I can help on this one in any way.

**Pull request closed without merging**
