### PR TITLE
Variant Image Issue

### PR DESCRIPTION
**Pull request by arsen3d**
Resolved issue I submitted a few weeks ago:
https://github.com/reactioncommerce/reaction/issues/3227
https://github.com/reactioncommerce/reaction/issues/3208

### CODE REVIEW

**Comment by josx** [comment]
I also need it! 
Please review it to merge it

**Comment by zenweasel** [comment]
@arsen3d @josx Are you still seeing this issue on the current `master`? I am no longer able to reproduce this after the fix by @Akarshit

**Comment by josx** [comment]
Sorry i dont know, i am not using latest reaction version in my project. 
Maybe @arsen3d can confirm it

**Comment by arsen3d** [comment]
I am not running latest from this repository. I fixed it in my local version and did a pull request.

**Comment by zenweasel** [comment]
The issues referenced have been fixed in previous PR's so closing this one.

**Pull request closed without merging**
