### PR TITLE
Marketplace 1.1.1 merge

### PR DESCRIPTION
**Pull request by spencern**
Manual merge of 1.1.1 with `marketplace`
```
Conflicts:
	imports/plugins/included/product-detail-simple/client/containers/productDetailContainer.js
	server/methods/catalog.js
	server/publications/collections/product.js
	server/publications/collections/products.js
```

### CODE REVIEW

**Comment by aaronjudd** [comment]
I am seeing that the merge of 1.1.1 into marketplace is going to require the fixes to permissions from #2145.  Most of the dashboard is showing where those elements should be hidden from the marketplace seller.

**Comment by spencern** [comment]
@aaronjudd I'd propose that we merge this anyway. This is how the `marketplace` branch has been working for some time and is not an issue that was introduced in `1.1.1` or in this merge. 

It _is_ an issue, and there are a lot of permissions issues to sort out in `marketplace` but I think we should still merge so that we're tracking with the latest version of `master`

image

**Comment by aaronjudd** [comment]
@spencern agreed. the fixes are coming anyways.

**Comment by spencern** [comment]
Merging despite the bithound dependency warning.

All 5 failing dependencies are related to pinning `react` at `15.4.2`

**Pull request merged**
