### PR TITLE
fix: update surcharge mutation will send the whole item

### LINKED ISSUE #6508: updateSurcharge should return the full item from db
## Issue Description
The `updateSurcharge `Mutation will only return the updated fields instead of returning the full item from db including the changes here: https://github.com/reactioncommerce/api-plugin-surcharges/blob/98cb4ca48fcd53edbfd36dedbe6986bfe8bf795c/src/mutations/updateSurcharge.js#L40

The mutation will fail to return properly, if mandatory fields like `createdAt` are not part of the update.

## Steps to Reproduce
1. Create a surcharge
2. Use updateSurcharge to update e.g. the amount and query all Surcharge fields in the return
3. Observe that `Cannot return null for non-nullable field Surcharge.createdAt.` is thrown.

## Possible Solution
Use `findOneAndUpdate` with `returnOriginal: false` would probably be a better fit here, to return the full upldated item

### Versions
trunk

### PR DESCRIPTION
**Pull request by sushmitha-malae**
Signed-off-by: Sushmitha Malae [malaesushmitha@gmail.com](mailto:malaesushmitha@gmail.com)

Resolves #6508 
Impact: **minor**
Type: **bugfix**

## Issue

The updateSurcharge Mutation will only return the updated fields instead of returning the full item from db

## Solution

Returning the updated full document instead of the partially updated fields.

## Breaking changes

None

## Testing

Modified the existing utc, to test the change.

More detail for what each of these sections should include are available in our [Contributing Docs](CONTRIBUTING.md). This project uses [semantic-release](https://semantic-release.gitbook.io/semantic-release/), please use their [commit message format.](https://semantic-release.gitbook.io/semantic-release/#commit-message-format).

### CODE REVIEW

**Comment by sushmitha-malae** [comment]
@delagroove Please review the changes, Thanks!

**Comment by delagroove** [comment]
Hi @sushmitha-malae, can you sign-off your commits?
https://github.com/reactioncommerce/reaction/pull/6569/checks?check_run_id=8954488990

**Comment by brent-hoover** [comment]
@sushmitha-malae You have failing tests here

**Comment by sushmitha-malae** [comment]
having some problem with the sign off on the commits, raised duplicate [PR](https://github.com/reactioncommerce/reaction/pull/6576). Closing this.

**Pull request closed without merging**
