### PR TITLE
switch back to official standard-minifier-js

### LINKED ISSUE #2629: Development version of React in production
I am checking https://hello.reactioncommerce.com/ with [React Developer Tools](https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi?hl=en) and it says that the site is using development version of React. Does this deployment do it intentionally or is this a bug?

### PR DESCRIPTION
**Pull request by jshimko**
This resolves #2629 where the production version of React wasn't being used in production builds.  We already made this switch when updating to Meteor 1.5 (#2371), but I don't know why we switched back to `abernix:standard-minifier-js` shortly after that.  Somewhere between June 7 (where Meteor 1.5 was merged) and the release of Reaction 1.3.0 on June 21 it appears that it got reverted to `abernix:standard-minifier-js`.  Possibly a mistake during a merge conflict resolution?  There are no commits to the `.meteor/packages` file during that period that directly reference changing that package, so I'm thinking it had to be unintentional during a merge conflict.

Anyway, please give this a thorough test and see if you can find any build issues.  I've done a full production build/deployment with Docker and haven't seen any issues.

### CODE REVIEW

**Comment by zenweasel** [comment]
I've been using the React developer tool plugin to verify. `swag.getreaction.io` still gives me
```
This page is using the development build of React. 🚧

Note that the development build is not suitable for production. 
Make sure to use the production build before deployment.
```

I guess we need to dig into the plugin a little and determine how exactly it's deciding this is the `development` build

**Comment by zenweasel** [comment]
A quick check of the code says
```
  function detectReactBuildType(renderer) {
    try {
      if (typeof renderer.version === 'string') {
        // React DOM Fiber (16+)
        if (renderer.bundleType > 0) {
          // This is not a production build.
          // We are currently only using 0 (PROD) and 1 (DEV)
          // but might add 2 (PROFILE) in the future.
          return 'development';
```

**Comment by zenweasel** [comment]
Found these. Looks like this switch was made to fix an issue with Docker builds?

https://github.com/reactioncommerce/reaction/issues/2475
https://github.com/reactioncommerce/reaction/pull/2486
^^ that pull on the 22nd of June seems to be where the abernix fork was reintroduced?

**Comment by aaronjudd** [comment]
After not seeing any error, I thought the build had succeeded, but the image wasn't actually created, and after re-running twice more, both the docker build fails.  Are there other recommended config options?
```
docker build --build-arg TOOL_NODE_FLAGS="--max-old-space-size=2048" -t reactioncommerce/reaction:latest .
```

```
/opt/build_scripts/build-meteor.sh: line 30:  5174 Killed                  meteor build --directory $APP_BUNDLE_DIR
The command '/bin/sh -c cd $APP_SOURCE_DIR &&             $BUILD_SCRIPTS_DIR/install-deps.sh &&             $BUILD_SCRIPTS_DIR/install-node.sh &&             $BUILD_SCRIPTS_DIR/install-phantom.sh &&             $BUILD_SCRIPTS_DIR/install-mongo.sh &&             $BUILD_SCRIPTS_DIR/install-meteor.sh &&             $BUILD_SCRIPTS_DIR/build-meteor.sh &&             $BUILD_SCRIPTS_DIR/post-build-cleanup.sh' returned a non-zero code: 137```

**Comment by jshimko** [comment]
This just worked for me multiple times on both Mac and Linux.
```sh
docker build --build-arg TOOL_NODE_FLAGS="--max-old-space-size=2048" -t reactioncommerce/reaction:latest .
```
So am I the only person not running into the issue?

**Comment by spencern** [comment]
pulling a fresh copy and reviewing now.

**Comment by zenweasel** [comment]
I followed the steps that Spencer outlined above and it failed. I then switched to `master` and it worked.

Also, Bithound be gone.

**Pull request merged**
