### PR TITLE
Fixed missing placeholders on Social textfields in Product Detail Settings

### LINKED ISSUE #3016: show placeholder / default text in PDP social settings
### Expected behavior
Default text should show in social settings fields on PDP

### Actual Behavior
No default text shows, you don't see it until you actually click the share button

basic_reaction_products

### PR DESCRIPTION
**Pull request by aanchirinah**
Resolves #3016 ,

The textfield components for Social sharing were missing the `i18nKeyPlaceholder` property in their components, this also caused the default text for share messages to be `undefined`.

#### How to test placeholder fix
- Login as an admin 
- Select a product.
- Click on the edit social settings icon as seen in the image below with the blue square highlighting the icon,
placeholder-fix-screenshot
- As seen in the image above all the social textfields have their placeholders displaying

#### How to test default text also displays
We will use Twitter for this test
- Login as an admin. 
- Select a product.
- Click on the twitter icon to share as shown in the image below with the oval circle highlighting it,
share-with-twiiter
- Notice in the image below that a default text `ie. Injustice` is in the twitter share message as seen below,
twiitter-example-screenshot

### CODE REVIEW

**Comment by zenweasel** [comment]
It doesn't seem like these placeholders are styled with the same light-grey I see other placeholders have. They look more like values than placeholders

basic_reaction_product

basic_reaction_product

**Comment by zenweasel** [comment]
@aanchirinah What's the status on this?

**Comment by aanchirinah** [comment]
@zenweasel , I noticed the textarea is from an external react component library and does not have any styles defined as the textfields.

**Comment by aanchirinah** [comment]
@zenweasel , I have fixed the requested changes and added a style for textarea placeholders.

**Pull request merged**
