### PR TITLE
[CircleCI] Hard code cache keys prefix

### PR DESCRIPTION
**Pull request by elhil**
Amended version of #5221 to include feedback.

### CODE REVIEW

**Comment by focusaurus** [comment]
I'll work on addressing the CI failures which are unrelated to your changes. Thanks for this!

**Comment by spencern** [comment]
Hi @elhil 
Thanks so much for your PR - we'd love to use this in Reaction! Before we can merge this, we need you to sign your commits. 

We use the [Developer Certificate of Origin (DCO)](https://developercertificate.org/) in lieu of a Contributor License Agreement for contributions to Reaction Commerce projects. 

If you click the `details` link in the "checks" section of this PR - it will walk you through how to do this for your PR.
image

You can read more about how to generally sign your commits here: https://probot.github.io/apps/dco/

Thanks for contributing!!

**Comment by elhil** [comment]
@spencern fixed 👍

**Comment by focusaurus** [comment]
CI snyk failure was because circleci won't expose our snyk token to PRs from forks (which makes sense). The other checks passed. Merged in.

**Pull request merged**
