### PR TITLE
Implement babel-preset-env

### PR DESCRIPTION
**Pull request by aaronjudd**
- Remove es2015 preset
- Remove browerstack-local (not in use)
- Remove npm-shrinkwrap (not in use, deprecated)

### CODE REVIEW

**Comment by aaronjudd** [comment]
Just a note on this, I tested removing only using `babel-preset-meteor`, only `babel-preset-env`, `env`+`preset:react`, without installing `babel-preset-react` and without `babel-preset-stage2`.. well, we need them all (preset + reset + stage2), so I opted for `env` over `meteor` as the base preset package.

**Comment by spencern** [comment]
Any way to get bithound to rerun?

**Comment by aaronjudd** [comment]
No idea what's going on there. Looks, their status page says all is good, but looks like our analysis' are just stuck in some queued land..  I'm good with this going, if you want to hit the button.

**Comment by spencern** [comment]
I'll hit the button. I've had the bitHound link open for a while and it's still printing off nerdspirational messages.

Seems like perhaps the queue is borked or super backed up.

image

**Pull request merged**
