### PR TITLE
Fix for ui glitches using dynamic merchandising

### LINKED ISSUE #3880: Difficulties and glitches using dynamic merchandising
## Prerequisites
* [x] Are you running the latest version?
* [x] Are you able to consistently reproduce the issue?
* [x] Did you search the issue queue for existing issue?

## Issue Description
Dynamically merchandising by drag and drop has UI glitches and doesn't order products consistently, making it difficult to order products.

**Screen recording:**

No client or server error or warning logs.

## Steps to Reproduce
Please provide starting context, i.e. logged in as a user, configure a particular payment method.
1. Logged in as Admin
2. Add images to the default product from the PDP
3. From the product Grid, clone the default product several times
4. Drag and drop products to arrange them in a different order.

## Acceptance Criteria
When arranging products/dynamically merchandising via drag and drop, the products should stick in the positions where they are dropped. When "publish" is clicked, the new arrangement should be published to the consumer view.

### Versions
```
Node: 8.9.0
NPM: 5.6.0
Meteor Node: 8.9.4
Meteor NPM: 5.6.0
Reaction CLI: 0.28.0
Reaction: 1.8.2
Reaction branch: master
Docker: 17.12.0-ce
```

### PR DESCRIPTION
**Pull request by prinzdezibel**
Resolves #3880   
Impact: **major**  
Type: **bugfix**

## Issue
Dynamically merchandising by drag and drop has UI glitches and doesn't order products consistently, making it difficult to order products.

## Solution
This bug happened whenever products with different sized were juggled
around. The moment the drag source hovered the drop target they got
swapped, which would potentially result in a different arrangement of
the items. This could lead to the unfortunate situation, that the very
same item gets swapped over and over endlessly.

## Changes
 -  Don't apply layout (box size) changes on swaps until the drag source is
 actually dropped.
 - Update of the collection that persists the new order gets delayed
 until drag source is dropped. Before this change a mere hovering resulted in
 swapping AND persisting the new product order.

## Breaking changes
none expected

## Testing
1) Logged in as Admin
2) Add images to the default product from the PDP with different sizes
3) From the product Grid, clone the default product several times
4) Drag and drop products to arrange them in a different order.
5) There should no longer be a limbo state where products are swapping wild or endlessly.

### CODE REVIEW

**Comment by aldeed** [comment]
@jshimko Can you prioritize this one? I am making related fixes in my CFS replacement branch and would like to get this merged prior to that.

**Comment by spencern** [comment]
@prinzdezibel The issue screen recording does show this with different sized images, but I'm certain that I was seeing issues with products that are all using the same sized layout as well. Pretty sure that @aaronjudd has seen that behavior as well.

**Comment by prinzdezibel** [comment]
Funny, because I couldn't get it replicated with identical sizes. But maybe it had to do with the server-side update happening as soon as the drag source hovered the target. This has now been delayed until the drag source is actually dropped onto the target.

**Comment by jshimko** [comment]
I get tons of console errors on the drag event.  And when I sit there holding it mid-drag over another item, it just floods the console with about 100 instances of that error per second.  

drag-error

**Comment by prinzdezibel** [comment]
@jshimko Please try again, all my products already had positions structure, which was the reason I didn't get that error.

**Comment by jshimko** [comment]
@prinzdezibel Ok, that seems to have fixed it.  This all appears to work fine for me.  👍

**Pull request merged**
