### PR TITLE
(fix): also send notification to shop owners upon order creation

### LINKED ISSUE #4211: Merchant Notifications Only Appear For Primary Shop Owner
## Issue Description
Upon sale of an item by a merchant shop, no notification is shown to the merchant. The primary shop owner does however receive a notification. 

## Steps to Reproduce
1. Setup Marketplace and order an item from a merchant
2. Login as merchant
3. Observe no notifications

### Versions
1.10

### PR DESCRIPTION
**Pull request by ajporlante**
Resolves #4211   
Impact: minor
Type: bugfix

## Issue
When an order is created, it's always the case that only the marketplace admin is notified even when the order contains items sold by other merchants. There is currently no functionality to support such case.

## Solution
Update code for notifications such that we loop through the items of the order, check who owns the shop of each item, and send each owner a notification.

## Breaking changes
None

## Testing
1. Activate the marketplace feature.
2. Invite a new shop owner/merchant.
3. Activate the new shop created.
4. Click 'Get Started' from the e-mail invite. While logged in as the merchant, update the address of the shop and setup Stripe payment. Create and publish a product. 
5. As another user or possibly guest, create an order for that merchant product along with product/s from the primary shop.
6. Possibly, more merchants can be created and order can have items from different merchants.
7. Admin and all merchants involved in the order should receive notification.

### CODE REVIEW

**Comment by zenweasel** [comment]
@ajporlante You've got failing tests and linter errors

**Comment by zenweasel** [comment]
When I test this PR and place an order with items from the primary shop and a second shop I get this error:

```
=> App running at: http://localhost:3000/
06:16:11.302Z  INFO Reaction: Created shop:  kD7gDu4PoLBFTkBCE
Exception while invoking method 'cart/submitPayment' TypeError: Cannot read property 'items' of undefined
    at MethodInvocation.MethodHooks.after.options (imports/plugins/included/notifications/server/hooks/notification.js:50:9)
    at _each (server/api/method-hooks.js:114:36)
    at arrayEach (/Users/brenthoover/Projects/js/reaction/node_modules/lodash/_arrayEach.js:15:9)
    at forEach (/Users/brenthoover/Projects/js/reaction/node_modules/lodash/forEach.js:38:10)
    at MethodInvocation.MethodHooks._wrappers.(anonymous function) (server/api/method-hooks.js:113:5)
    at packages/check/match.js:108:16
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
    at Object._failIfArgumentsAreNotAllChecked (packages/check/match.js:107:41)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1765:18)
    at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:1686:15)
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
    at resolve (packages/ddp-server/livedata_server.js:1684:36)
    at new Promise (<anonymous>)
    at Server.applyAsync (packages/ddp-server/livedata_server.js:1683:12)
    at Server.apply (packages/ddp-server/livedata_server.js:1622:26)
    at Server.call (packages/ddp-server/livedata_server.js:1604:17)
    at MethodInvocation.MethodHooks.after.options (server/methods/core/hooks/cart.js:31:32)
    at _each (server/api/method-hooks.js:114:36)
    at arrayEach (/Users/brenthoover/Projects/js/reaction/node_modules/lodash/_arrayEach.js:15:9)
    at forEach (/Users/brenthoover/Projects/js/reaction/node_modules/lodash/forEach.js:38:10)
    at MethodInvocation.MethodHooks._wrappers.(anonymous function) (server/api/method-hooks.js:113:5)
    at packages/check/match.js:108:16
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
    at Object._failIfArgumentsAreNotAllChecked (packages/check/match.js:107:41)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1765:18)
    at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
    at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
    at Promise (packages/ddp-server/livedata_server.js:715:46)
    at new Promise (<anonymous>)
    at Session.method (packages/ddp-server/livedata_server.js:689:23)
    at packages/ddp-server/livedata_server.js:559:43
 => awaited here:
    at Promise.await (/Users/brenthoover/.meteor/packages/promise/.0.10.2.1t35cy5.uudhh++os+web.browser+web.cordova/npm/node_modules/meteor-promise/promise_server.js:60:12)
    at Server.apply (packages/ddp-server/livedata_server.js:1635:14)
    at Server.call (packages/ddp-server/livedata_server.js:1604:17)
    at MethodInvocation.MethodHooks.after.options (server/methods/core/hooks/cart.js:31:32)
    at _each (server/api/method-hooks.js:114:36)
    at arrayEach (/Users/brenthoover/Projects/js/reaction/node_modules/lodash/_arrayEach.js:15:9)
    at forEach (/Users/brenthoover/Projects/js/reaction/node_modules/lodash/forEach.js:38:10)
    at MethodInvocation.MethodHooks._wrappers.(anonymous function) (server/api/method-hooks.js:113:5)
    at packages/check/match.js:108:16
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
    at Object._failIfArgumentsAreNotAllChecked (packages/check/match.js:107:41)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1765:18)
    at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
    at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
    at Promise (packages/ddp-server/livedata_server.js:715:46)
    at new Promise (<anonymous>)
    at Session.method (packages/ddp-server/livedata_server.js:689:23)
    at packages/ddp-server/livedata_server.js:559:43
```

**Comment by ajporlante** [comment]
Fixed the cause for failing the integration test.

@zenweasel This bug you reported is gone in `1.13.0`.

**Comment by spencern** [comment]
@zenweasel @ajporlante this seems to be ready for another review.

**Comment by spencern** [comment]
@ajporlante @zenweasel I'd like to merge this into 1.14 now that it's ready. Looks like there's a slight conflict with imports since migrating the core server api to plugins

**Pull request merged**
