### PR TITLE
Make order details panel visible.

### LINKED ISSUE #2617: [Marketplace] When using "collapsed" order view, order detail is not always visible.
### Expected behavior
Order detail panel should always be visible

### Actual Behavior
Order detail panel appears not to open because it is hidden. The main list view area should shrink to accomodate the expanded panel. Moving to "expanded" view shows the panel however.
order-detail-panel

### Steps to Reproduce the Behavior
1. Place an order
1. Make browser width around 1133px.
1. Go to order view
1. Click on an order
1. Observe that panel appears now to open

### Versions
```
Node: 7.10.0
NPM: 5.0.3
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction CLI: 0.11.0
Reaction: 1.5.0
Reaction branch: marketplace
Docker: 17.06.0-ce
```

### PR DESCRIPTION
**Pull request by foladipo**
Resolves #2617.

This PR resolves a bug with the orders page. Using the `Collapsed` mode to view the list of orders, the details panel for any specific order wasn't showing up because of some CSS issues.

## Test instructions
- Log in as admin and make one or two orders.
- Use the admin menu (on the right) to go to the `Orders` page.
- Switch to `Collapsed` view.
- Click the `>` beside any listed order and you'll notice that the details panel for that order now show up correctly in the browser.
- Try to resize the browser window. You'll notice that the order details panel stays visible throughout.

### CODE REVIEW

**Comment by zenweasel** [comment]
When I first open the orders panel I get this big blank space where there should be none:

thfh7gymvdgsrzdms

**Comment by zenweasel** [comment]
It seems like at wider widths we would want the main order grid to fill all available space and possibly add more fields rather than just having a blank space there.

thfh7gymvdgsrzdms

**Comment by zenweasel** [comment]
At more narrow widths we don't want to lose the order selector there.

thfh7gymvdgsrzdms

@rymorgan Is there an already existing spec for how this order table should operate at all the varying widths? I feel like there is but I am not sure where one would look.

**Comment by foladipo** [comment]
@zenweasel Thanks for the feedback. I have tested this PR and it truly displays the orders table in a weird way at wider screen widths. I'll fix that and update my PR.

As for the orders' table's behaviour at smaller widths, especially in the screenshot you shared, what happens is that the container for the table becomes scrollable. So, if you scroll to the right, the order selector is still visible.

PS: Other than the above, this PR also hides various columns as the screen size reduces in order to fit the orders' table to the screen.

**Comment by aaronjudd** [comment]
@foladipo can you come back to this soon, and fix the merge conflicts, and get this ready for review, or can you close the PR until you are ready?

**Comment by foladipo** [comment]
Thanks for the heads-up @aaronjudd . I put this in the icebox to work on #2265 because of how important it was to fix that bug.

I've now fixed the issues observed by @zenweasel and pushed the commits.

**Comment by zenweasel** [comment]
This is what I am seeing upon opening the order dashboard for the first time

dashboard_orders

**Comment by zenweasel** [comment]
@foladipo I thought the above corrupted view might be dependent on a particular width but that's the way it is at all widths, rendering the order panel unusable.

**Comment by foladipo** [comment]
@zenweasel I've tried to reproduce this both on my computer's screen and a large monitor but can't. Can you tell me the steps you carried out to get the bug?

I also wonder why the order's detail panel (to the right) is actually duplicating itself.

**Comment by zenweasel** [comment]
@foladipo I followed the instructions in the PR

**Comment by rymorgan** [comment]
I'm seeing the same thing. There is something more going on with sidebar than just this. I created an issue for what I'm seeing in general with the sidebar UI in orders. The sidebar for orders is basically unusable in Marketplace right now. 

https://github.com/reactioncommerce/reaction/issues/2775

**Comment by foladipo** [comment]
@rymorgan @zenweasel So, I've figured out where this happens, being guided by what Ryan reported in #2775. Apparently, you can reproduce this bug as follows:

- Add items to your cart and checkout (i.e pay for the products and get to the "Thank you" page.

- While on the checkout page, try to open the orders panel. It will open as a modal, as expected

- Click the blue, "manage order" button beside any new order. Instead of still have a modal, the orders panel is now a main page by itself, and the order details panel at the side is duplicated.

- If you go to the products' dashboard/grid and try to open the orders panel again, it functions as normal.

I'm guessing this was caused by some new code pushed to `marketplace`. I'll investigate it further, try to fix it and add that fix to this one.

**Comment by foladipo** [comment]
@rymorgan and @zenweasel So, I've figured out that it doesn't even happen on the "Thank you" page alone. It happens on all pages that are *NOT* the index. So, if you go to `localhost:XXXX/product/XXXX` or some other non-index URL, you will see the orders panel misbehave.

I eventually traced the source down to [this section of code](https://github.com/reactioncommerce/reaction/pull/2719/commits/231d4007548eae32c496be62441c44e58ee4595d). So, I wish to know your corrections (e.g that that code isn't actually the root of the bug) or suggestions as to how to update that section to fix the bug *WHILE* not breaking other parts of the codebase.

**Comment by rymorgan** [comment]
@mikemurray @kieckhafer Can one you two take a look at this. I can get you up to speed on the bug if needed.

**Comment by mikemurray** [comment]
@foladipo The action view is split up into 2 sections.

[ actionView | actionViewDetail ]

You open the main action view with `Reaction.setActionView()` and the detail view `Reaction.setActionViewDetail()`, which opens a smaller sidepanel inside the big action view panel.

The button that opens the order detail should be doing `Reaction.setActionViewDetail()`.

**Comment by foladipo** [comment]
@mikemurray Yes, the button that opens the order detail does call `Reaction.setActionViewDetail()`.

The problem is that that call eventually gets into [this function](https://github.com/reactioncommerce/reaction/blob/231d4007548eae32c496be62441c44e58ee4595d/client/modules/core/main.js#L625). What I don't understand is why we have to open either `admin/detailView` or `admin/actionView` based on whether or not we are on the index page.

In fact, if I simply open `admin/detailView` always, it fixes this new bug reported by Brent and Ryan.

Now, after doing some more digging, I found out that that section of code was written by Jeremy about two weeks ago in [this commit](https://github.com/reactioncommerce/reaction/commit/b2a192c3fd4076ee5bc12727b9cc6110062fff79).

@jshimko Please can you explain the aim of that section of code?

**Comment by zenweasel** [comment]
@foladipo I don't know that Jeremy will know any thing particularly about that code as it was a merge commit. It was probably to fix a bug but that history has probably been lost with `development`.

Either way, does this current code fix this bug? I am going to re-test now because it's my assumption from your notes that that's the status and it's not marked [WIP].

**Comment by zenweasel** [comment]
So it looks like this is still broken.

@mikemurray Can you help us understand why/when/if we would want to open `admin/adminView` for orders if there is any case for that? Is there no case for this (even for index right?). Maybe this is just some merge weirdness and we can get rid of that if branch.

**Comment by mikemurray** [comment]
@zenweasel @foladipo I'm not sure why there is a check for the index page in the actionView function. It shouldn't care about that at all.

I think at some point that `index` was meant for the internal navigation stack of the action view itself, and not the actual Reaction Router routing/pages.

**Comment by zenweasel** [comment]
So I just removed that branching since no one could understand why it's there and everything about orders seems to work great. A quick check of admin panels seems to be fine as well.

@mikemurray Would you mind taking one last look at this and make sure everything is operating as it should be?

**Comment by foladipo** [comment]
@mikemurray Thanks for the heads up. That bug has now been fixed.

cc @zenweasel

**Pull request merged**
