### PR TITLE
Product.positions refactoring

### PR DESCRIPTION
**Pull request by newsiberian**
Hello, there was a number of bugs with it. And we were using an array to store `positions` which is slow in our case, because, in that case we need to do heavy computations while sorting products.

### CODE REVIEW

**Comment by newsiberian** [comment]
Oh, man! I've just realize the main benefit of this approach. Now, in theory, we can completely remove sorting from client, by passing new `getTag` method's result to publication and there, we could have something like:
```js
const position = `positions.${tag}.position`;
const defaultSort = { sort: [position] }
```

**Comment by ramusus** [comment]
:+1: sorting should be on the server side for sure. It's annoying to see, when new just uploaded products starts to reordering right after they appear on the site.

**Comment by aaronjudd** [comment]
:+1:  approved, I tested - looks good - the important test here is that the positions and layout are specific per tag. (and that seems to be working well).

**Comment by aaronjudd** [comment]
@newsiberian not sure why codeclimate didn't run for this PR, and I don't see a way to rerun, so I guess we don't get linting on this PR. :-(

**Comment by newsiberian** [comment]
@aaronjudd, hello, if it is important, I can update this PR via some comment or something and codeclimate could rerun. Should I try this?

**Comment by aaronjudd** [comment]
@newsiberian not that important, but I am curious..

**Comment by aaronjudd** [comment]
Accepting, created an issue for the for-func-loop, need to decide how/if we really want to enforce that or not.

**Pull request merged**
