### PR TITLE
feat: promotion add integration tests

### LINKED ISSUE #6712: Write Integration tests for complete promotion flow: Milestone 1
Milestone 1

Test One A "Golden Path with Dollar off"
1. Create a promotion via endpoint: $10 off when you spend more than $100
2. Create cart that meets promotion criteria with an order discount
3. Validate that correct discount is applied
4. Validate that correct promotions are applied
5. Place order with cart
6. Validate order has discounts applied

Test One B "Golden Path with percentage"
1. Create a promotion via endpoint: %10 off when you spend more than $100
2. Create cart that meets promotion criteria with an order discount
3. Validate that correct discount is applied
4. Validate that correct promotions are applied
5. Place order with cart
6. Validate order has discounts applied

Test Two "Don't apply"
1. Create promotion via endpoint
2. Create cart that does not meet criteria
3. Verify promotion is not applied

Test Three "Applies via inclusion criteria"
1. Create promotion that uses inclusion criteria e.g. $10 off when you buy $100 of Nike
2. Create cart that qualifies
3. Validate correct promotion is applied

Test Four "Doesn't apply via inclusion criteria"
1. Create promotion that uses inclusion criteria e.g. $10 off when you buy $100 of Nike
2. Create cart that is over $100 but not of Nike
3. Verify promotion is not applied

Test Five "Excluded products"
1. Create promotion that excludes some items from discount $10 off when you buy $100 of Nike except for Gift Cards
2. Create cart that qualifies
3. Validate that discount is not applied to Gift Cards

Test Six "Cart disqualified"
1. Create a promotion via endpoint
2. Create cart that qualifies
3. Verify promotion is applied
4. Modify cart so that it no longer qualifies
5. Validate that promotion and discount are removed

Test Seven "Promotion completed"
1. Create a promotion via endpoint
2. Create a cart that qualifies
3. Modify promotion so that it is no longer enabled
4. Touch cart in some manner 
5. Verify that promotion is removed and a message is added to the messages array

Test Eight "Stackability:None"
1. Create two promotions with both stackability "None"
2. Create a cart that qualifies for both
3. Verify that only one promotion is applied

Test Eight "Stackability:All"
1. Create two promotions with both stackability "All"
2. Create a cart that qualifies for both
3. Verify that both promotions are applied
4. Verify discounts are applied correctly

### PR DESCRIPTION
**Pull request by vanpho93**
Resolves #6712
Impact: **minor**
Type: **test**

## Issue

Missing integration test cases for promotion

### CODE REVIEW

**Comment by brent-hoover** [comment]
@vanpho93 You have no reviews requested. Is this PR ready to go?

**Comment by vanpho93** [comment]
> @vanpho93 You have no reviews requested. Is this PR ready to go?

@zenweasel It's ready now.

**Review by brent-hoover — CHANGES_REQUESTED** [review]
This does not satisfy the requirements of the original ticket which were perhaps too vague but this needs to add new integration tests for promotion endpoints such as createPromotion etc. Not sure exactly what's in this PR.

**Review by brent-hoover — APPROVED** [review]
We might want to exclude the Snyk update but I think this is ready

**Pull request merged**
