### PR TITLE
WIP - Fix 2895 impactmass has permisssion owner fix

### LINKED ISSUE #2895: Update Reaction.hasPermission's owner pass and replace instances of Roles.userIsInRole
Reaction.hasPermission currently gives global access for users with "owner" role (i.e it always returns true for owners). This means that a check like `Reaction.hasPermission("anonymous")` will return `true` when we want it to return `false`.

This happens because `Reaction.hasPermission` joins "owner" to the roles passed to it. We need to remove that join, so that when we check for particular role(s), we are sure that the response is really based on if user has that role.

Then we need to ensure that all current usage of Reaction.hasPermission still works with this change.

After that, we proceed to replace instances of `Roles.userIsInRole` with `Reaction.hasPermission`.

### PR DESCRIPTION
**Pull request by impactmass**
Resolves #2895  
Type: **fix|?feat**

## Task
Fix `Reaction.hasPermission` to work properly with “anonymous” role check.

Reason: This change is needed so we can be able to replace ALL current use of `Roles.userIsInRole` in the code to `hasPermission` (thus paving the way for removing dependency on Roles package later). See issues #2895 (old but yet-to-be-fixed issue) and #4525 for more details.

## Overview
**Brief summary chosen approach:** Add an extra `option` param to hasPermission. This will allow us to call hasPermission in a no “appendOwner” mode. This mode will not append the “owner” role as we currently have it. Existing checks that do not pass a “appendOwner” flag will go ahead with appending the “owner” role.

## Other Approaches
**Approach A:** Remove the addition/appending of the “owner” role happening within the hasPermission method. This will require explicitly adding “owner” to the list of roles in the arguments passed to ALL existing hasPermission calls.

**Why not chosen:** This approach will be very extensive (with a large surface area of code to change). It will also be a “avoidable” breaking change for plugins.

## Negatives
None that I can think of. Going the route of adding an extra field doesn't affect current code setup.

## Structure
Where will this code live: The changes are done in the current Reaction.hasPermission (in the frontend code and server code)

## User Interface Changes
None

## Breaking Changes
None

## Future Effects
What effects on future code (either positive or negative) will this have?

**Positive:** The addition of an options object introduces a way to later extend the behavior of this function. More options can be added when needed.

## Security Concerns
None

### CODE REVIEW

**Comment by spencern** [comment]
@impactmass This ticket has been in the icebox for a bit, what's the status of this PR?

**Comment by impactmass** [comment]
@spencern I was working on this as part of the Keycloak Auth Epic, which was paused in favor of setting up Hydra Auth for 2.0-release. Now, we are starting to revisit the next steps of our Identity and Access Management setup, and that will determine our approach to this PR.

**Comment by spencern** [comment]
@impactmass ping on this issue.

**Comment by impactmass** [comment]
At this point, the conversation around the roles and authorization piece of our IAM is steering in the direction of having a 'separate' roles/policy evaluation that is not tightly-coupled with one service (i.e the Reaction API service as we have it right now). 

It's still fairly open right now as no full decision has been made. 

The work in progress on this PR (if completed) is useful if our strategy on roles and auth follows the current path.

I will say I close this PR, but keep the branch up in case(?).

**Pull request closed without merging**
