### PR TITLE
Fix: Perform old password validation

### PR DESCRIPTION
**Pull request by trojanh**
Impact: minor
Type: bugfix

Issue
`validatedOldPassword` should validate `oldPassword` instead of new password

Solution
Replace the new password variable(i.e `password`) with old password variable i.e `oldPassword`

Breaking changes
None

Testing
See if the validation works correctly on the password update page

### CODE REVIEW

**Comment by kieckhafer** [comment]
@trojanh Thanks for the PR. We require all our contributors to sign off on their commits. It looks like your latest commit is not signed off. Please [follow the instructions here](https://github.com/reactioncommerce/reaction/pull/5527/checks?check_run_id=216179840) to do so before we can take a look at this.

**Comment by aldeed** [comment]
Changed to point to `develop`. Seems good to merge after commits are signed off.

**Comment by trojanh** [comment]
sure @kieckhafer , thanks for guiding as this my first PR here. 

Thanks @aldeed 

I will make the signed commit to fix this PR.

**Comment by trojanh** [comment]
@kieckhafer @aldeed I have made the signed commit and it seems to be fixed now.

**Comment by aldeed** [comment]
Thank you @trojanh, concise fix PRs are very much appreciated. This will be in the next 2.x release.

**Comment by trojanh** [comment]
Thanks, @aldeed  I am glad I got to contribute to the project I have been using recently. I am hoping to contribute more.

**Pull request merged**
