### PR TITLE
[WIP] Fix "Order filtering by status does not always refresh properly" bug #2902

### PR DESCRIPTION
**Pull request by efalayi**
Resolves [#2902](https://github.com/reactioncommerce/reaction/issues/2902)
After selecting one status then another, sometimes orders that are valid do not show up

**query** contains filter information sent to the server. From previous implementation, `Object.assign` is used to update `this.state.query` in Orders react component. However, this not only updates but also merges query keys in state. Hence a wrong query is parsed on to the server.
```
let query = OrderHelper.makeQuery(value);
query = Object.assign({}, this.state.query, query);
```

###### Fix
To update filter query and search query, current search query is also parsed to state. We can update query with just the current search query (if it exists)
```
let query = OrderHelper.makeQuery(value);
   if (this.state.query._id) {
     query._id = this.state.query._id;
   }
```

###### Test
```
Add some orders
Set some orders to different states
Select a filter for which no orders should show up ("Captured" or "Approved")
Select a filter for which some orders should show up
Observe orders shown
Search filtered orders
```

### CODE REVIEW

**Comment by spencern** [comment]
@kieckhafer @joykare Can you guys review this please

**Comment by efalayi** [comment]
@kieckhafer, the Shipping Status dropdown wasn't included for this PR. I think @joykare is working on that.

**Comment by joykare** [comment]
@kieckhafer wasn't already in marketplace there's a PR for that: https://github.com/reactioncommerce/reaction/pull/2914

However, LGTM

**Comment by kieckhafer** [comment]
@joykare OK, I just checked that PR so i know it works there. In that case, this also LGTM. There are some linting errors, however they are the same as the issues that were in #2893 and I've fixed those in that branch, so they will be resolved.

**Comment by spencern** [comment]
@kieckhafer is this good to go now?

**Comment by kieckhafer** [comment]
Yes... good to go... was waiting on tests/linting to pass

-- 
Erik Kieckhafer
Software Engineer, Reaction Commerce <http://www.reactioncommerce.com>

**Comment by kieha** [comment]
Fixed by #2972

**Pull request closed without merging**
