### PR TITLE
Fix #4057: Admin should have media editable

### LINKED ISSUE #4057: Incorrect featured image displayed after zooming
## Prerequisites
* [x] Are you running the latest version?
* [x] Are you able to consistently reproduce the issue?
* [x] Did you search the issue queue for existing issue?

## Issue Description
When browsing the PDP, the correct featured image is displayed as you click through various options until you hover over the featured image to zoom. Once the featured image has been hovered, it will no longer update when changing product options/variants until a refresh has occurred.
The featured image will update when hovering over the media gallery images, and the media gallery images do correctly update when selecting different options or variants.

See this screen recording:

## Steps to Reproduce
Please provide starting context, i.e. logged in as a user, configure a particular payment method.
1. Create a product with multiple options and multiple variants
2. Add images to each variant and option
3. Make the product public
4. As a customer, visit the PDP for that product
5. Be careful not to hover over the featured image, select between various options and variants.
6. Now hover over the featured image
7. Again, select various options and variants
8. Observe that the featured image is not updated when you change the selected option or variant

## Possible Solution
This may have been introduced while replacing CFS in #3782 

### Versions
```
Node: 8.9.0
NPM: 5.6.0
Meteor Node: 8.9.4
Meteor NPM: 5.6.0
Reaction CLI: 0.29.0
Reaction: 1.9.0
Reaction branch: master
Docker: 17.12.0-ce
```

### PR DESCRIPTION
**Pull request by Akarshit**
Resolves #4057  
Impact: **major**  
Type: **bugfix**

## Issue
The `featuredImage` is set when the mouse enter the image region and is unset when the mouse leaves the image region. But `onMouseLeave` wasn't being passed to the `MediaItem` component. Hence the image was only getting set and never unset.
When clicking on the variants, `featuredImage` is always given precedence over `variant`'s image.  Since the `featuredImage` was not null, the variants image was not being displayed.

## Solution
Passed the `onMouseLeave` to the `MediaItem` component which set's the `featuredImage` to null as soon as the mouse leaves the image. The `onMouseLeave` already had correct logic in place.

## Breaking changes
None

## Testing
1. Create a product with multiple options and multiple variants
2. Add images to each variant and option
3. Make the product public
4. As a customer, visit the PDP for that product
5. Be careful not to hover over the featured image, select between various options and variants.
6. Now hover over the featured image
7. Again, select various options and variants
8. Observe that the featured image is **now updated** when you change the selected option or variant

### CODE REVIEW

**Comment by spencern** [comment]
@Akarshit this looks like a good fix, I'd like to ask that you fill out the "issue" and "solution" sections with _much_ more detail. As it stands, I can't tell at a glance if this is a fix that might have other consequences or if the initial implementation of `!editable` was just wrong from the start.

At a minimum I think an explanation of what `editable` is doing, and why this would affect both the consumer and the operator view is necessary.

**Comment by Akarshit** [comment]
@spencern Sure I will take care of this from now on.

**Comment by zenweasel** [comment]
@Akarshit I think Spencer meant please fill out the Issue/Solution sections **on this PR** (as well as in the future) so that he feels comfortable merging it.

**Comment by Akarshit** [comment]
@zenweasel This will need another review. I think the old fix was incorrect.

**Pull request merged**
