### PR TITLE
Fix for missed import constant

### PR DESCRIPTION
**Pull request by newsiberian**
Hello, scrolling was broken because of this.

- [ ] Description explains the issue / use-case resolved
- [ ] Only contains code directly related to the issue
- [ ] Has tests.
- [ ] Has docs.
- [ ] Passes all tests
- [ ] Has been linted and follows the style guide

### CODE REVIEW

**Comment by jshimko** [comment]
👍 

[Approved with PullApprove](https://pullapprove.com/reactioncommerce/reaction/pull-request/1131/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=reactioncommerce/reaction)

**Comment by zenweasel** [comment]
Approved

**Comment by zenweasel** [comment]
Could you resolve the conflict and we can merge?

**Comment by zenweasel** [comment]
@newsiberian Sorry I missed that you fixed this and now it's out-of-date again. Remember that you have the rights to create branches directly on this repo so in the future we can just update it ourselves. I have added your change to https://github.com/reactioncommerce/reaction/pull/1144/ so I am going to close this one. Thanks.

**Pull request closed without merging**
