### PR TITLE
Fix Setting product visibility is not reflected in the Product Grid reactively

### LINKED ISSUE #2522: Setting product visibility is not reflected in the Product Grid reactively
### Expected behavior
Setting a product as "visible" or "invisible" should be reflected immediately in the product grid when published.

### Actual Behavior
Changes are only shown on reload

### Steps to Reproduce the Behavior
1. Create a product, set it to visible and publish
1. Observe it in the Product grid
1. Set it to "Private" and publish
1. Observe that the Product Grid does not change
1. Reload page and observe that the changes are visible

### Versions
```
Node: 7.10.0
NPM: 5.0.3
Meteor Node: 4.8.3
Meteor NPM: 4.6.1
Reaction CLI: 0.10.0
Reaction: 1.3.0
Reaction branch: master
Docker: 17.06.0-ce
```

### PR DESCRIPTION
**Pull request by awadesmoline**
This resolves #2522

### Steps to Test
1. Create a product, set it to visible and publish
1. Observe it in the Product grid in an incognito browser, as non-admin
1. Set it to "Private" and publish
1. Observe that the disappears from the grid
1. Set it to "Public" and publish 
1. Observe that it comes back on the grid reactively.

### CODE REVIEW

**Comment by aaronjudd** [comment]
Also confirming works for existing products. Did not work for new products. 

Since that is step one of #2522 steps to reproduce is a new product, let's get that working before accepting this PR.

I also cloned and existing product, and published it, and all my products in the incognito grid disappeared.

**Comment by awadesmoline** [comment]
@aaronjudd, @kieckhafer this should work now.

**Comment by aaronjudd** [comment]
Tests are failing.

**Comment by awadesmoline** [comment]
Tests fixed.

**Comment by aaronjudd** [comment]
@awadesmoline When we see underscore/lodash -> we should be attempting to replace with native ES6.  We should really try hard to not implement in new code.

**Comment by awadesmoline** [comment]
Okay @aaronjudd. Noted.

**Pull request merged**
