### PR TITLE
Show proper error messages when Stripe payments fail

### LINKED ISSUE #2483: Payment processor API key error shown to customers
### Expected behavior

When the payment provider is misconfigured, give the customer a generic error that tells them to contact the site admin.

### Actual Behavior

When an API key doesn't work for a payment provider (Stripe, in my example) the customer gets an alert in the UI that says `Oops! Invalid API key provided:  ACTUAL_API_KEY_HERE`.  Not only is that something that makes no sense to a customer, an API key should never be revealed on the client side to non-admin user (and this was even a guest user in my case).

Ideally, this should never happen in a real production shop, but if an API key ever got revoked on the payment provider end, this could actually happen.

### Steps to Reproduce the Behavior

Add an invalid API key to the Stripe config, add a product to your cart, and checkout.  When you try to submit payment, you receive:

cart_checkout

### Versions

Node: 8.1.2
NPM: 5.0.3
Meteor Node: 4.8.3
Meteor NPM: 4.6.1
Reaction CLI: 0.10.0
Reaction: 1.3.0
Reaction branch: Release-1.3.0
Docker: 17.03.1-ce

### PR DESCRIPTION
**Pull request by zenweasel**
Resolves #2483 

Sanitize error messages from server and pass them directly up to the client

### Testing

1. Configure Stripe with an invalid API key
1. Attempt to check out
1. Observe the error message contains no sensitive information

1. Configure Stripe with a valid API key
1. Attempt to check out using `4000000000000002` as your CC so that your card will be declined
1. Observer that a "Your card was declined" is displayed to the client
1. Attempt to check out with a card number of `4242424242424141` (so that Luhn check fails)
1. Observe you get an appropriate error

### CODE REVIEW

**Comment by spencern** [comment]
@zenweasel got a couple failing tests here.

**Comment by zenweasel** [comment]
@kieckhafer Yeah, they are within the tests. I noticed the failing tests at the last minute yesterday and forgot to put the PR back into WIP

**Comment by zenweasel** [comment]
@spencern @kieckhafer tests are passing now

**Comment by spencern** [comment]
Tests are passing:

I'm getting `An unexpected error has occurred` for all error messages.
image

**Comment by spencern** [comment]
I am seeing Package subscription Match errors after the payments have failed.
```
Exception from sub Packages id ALyt7ZEm5g82Nvoeb Error: Match error: Failed Match.OneOf, Match.Maybe or Match.Optional validation
    at exports.check (packages/check.js:56:15)
    at [object Object].<anonymous> (server/publications/collections/packages.js:74:3)
    at packages/matb33_collection-hooks.js:307:21
    at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
    at [object Object]._handler (packages/matb33_collection-hooks.js:306:28)
    at packages/check.js:129:16
    at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
    at Object.exports.Match._failIfArgumentsAreNotAllChecked (packages/check.js:128:41)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1734:18)
    at [object Object]._.extend._runHandler (packages/ddp-server/livedata_server.js:1035:17)
    at [object Object]._.extend._startSubscription (packages/ddp-server/livedata_server.js:853:9)
    at [object Object]._.extend.protocol_handlers.sub (packages/ddp-server/livedata_server.js:625:12)
    at packages/ddp-server/livedata_server.js:559:43
Sanitized and reported to the client as: Match failed [400]

Exception from sub Packages id wX2pYy9HTzdRE66eK Error: Match error: Failed Match.OneOf, Match.Maybe or Match.Optional validation
    at exports.check (packages/check.js:56:15)
    at [object Object].<anonymous> (server/publications/collections/packages.js:74:3)
    at packages/matb33_collection-hooks.js:307:21
    at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
    at [object Object]._handler (packages/matb33_collection-hooks.js:306:28)
    at packages/check.js:129:16
    at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
    at Object.exports.Match._failIfArgumentsAreNotAllChecked (packages/check.js:128:41)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1734:18)
    at [object Object]._.extend._runHandler (packages/ddp-server/livedata_server.js:1035:17)
    at [object Object]._.extend._startSubscription (packages/ddp-server/livedata_server.js:853:9)
    at [object Object]._.extend.protocol_handlers.sub (packages/ddp-server/livedata_server.js:625:12)
    at packages/ddp-server/livedata_server.js:559:43
Sanitized and reported to the client as: Match failed [400]
```

**Comment by zenweasel** [comment]
@spencern As far I know there is no way to hide that server error when I Match fails. And that's the way it has always behaved.

Are you still seeing "An unexpected error has occurred" for all errors?

**Comment by spencern** [comment]
I should have clarified, for all errors with an incorrect stripe API key - which I assumed is how it's supposed to function.

**Comment by zenweasel** [comment]
Yeah, I am open to another wording. The server log should get the unsanitized error.

**Comment by rymorgan** [comment]
Is it possible to have an error that's specific and tell the user something that helps them correct the error? Like "Error: Incorrect Stipe API Key" ?

**Comment by zenweasel** [comment]
@rymorgan The admin should be getting the unsanitized message (e.g. Incorrect API Key) in the logs. The "user" here is just some random consumer.

**Comment by rymorgan** [comment]
Ah, ok, makes sense.

**Comment by zenweasel** [comment]
@spencern Okay to merge?

**Comment by spencern** [comment]
Yeah, we're good.

**Pull request merged**
