### PR TITLE
translation: update NL translation files

### PR DESCRIPTION
**Pull request by firstred**
Resolves **N/A**
Impact: **none**  
Type: **translation**

## Issue
Time to finish what I started. The Dutch translations for Reaction Commerce :)

## Solution
This completes the Dutch translations.

Note: not every file has been translated. E.g. I don't see Dutchies using TaxCloud or Avalara anytime soon.
Because of the fact that differentiating between `nl_NL` (Netherlands Dutch) and `nl_BE` (Belgium Dutch [Flemmish]) is not possible, I have used a more formal/neutral tone in the translations. This should make it suitable for both countries.

## Breaking changes
N/A

## Testing
1. Merge the `nl.json` files
2. Switch to Dutch
3. Watch the gobbledy gook appear on your screen

### CODE REVIEW

**Comment by firstred** [comment]
Not much movement here. Are translations being managed via your GitHub repo or is there something else?

**Comment by zenweasel** [comment]
@firstred Hey, we used to use a third-party service for managing translations (LingoHub) but we haven't been happy with it lately so we've just been doing them manually. I'll make sure this gets reviewed and approved for the next release, but it appears you have failing tests

**Comment by aldeed** [comment]
@firstred Ping

**Comment by spencern** [comment]
Closing due to lack of response. We'd love to get these translations merged if the conflicts can get resolved. Feel free to re-open if you'd like to update the PR.

**Comment by firstred** [comment]
Oops, sorry about the delay! I'll try to make a new PR as soon as possible.

**Pull request closed without merging**
