### PR TITLE
METEOR 1.4.4.2

### PR DESCRIPTION
**Pull request by aaronjudd**
Meteor 1.4.4.2, Node 4.8.2, Mongo 3.4.4

### CODE REVIEW

**Comment by zenweasel** [comment]
If I just switch to the branch (no reset, no fresh clone) I see this error. Since this updates the job-control package I wonder if there is an incompatibility with data between versions.
```
Exception in setTimeout callback: Error: JobQueue: Invalid root, must be nonempty string
    at new JobQueue (packages/vsivsi_job-collection/job/src/job_class.coffee:114:17)
    at job/src/job_class.coffee.js:175:45
    at Function.JobQueue [as processJobs] (packages/vsivsi_job-collection/job/src/job_class.coffee:110:18)
    at module.export.exports.default (server/jobs/email.js:14:34)
    at module.export.exports.default (server/jobs/index.js:5:2)
    at server/api/core/core.js:25:6
    at packages/vsivsi_job-collection/job/src/job_class.coffee:17:7
    at packages/vsivsi_job-collection/src/server.coffee:83:15
    at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
    at packages/meteor.js:445:45
    at runWithEnvironment (packages/meteor.js:1176:24)
```

**Comment by zenweasel** [comment]
Same issue on fresh clone

**Comment by jshimko** [comment]
Yep.  I fixed the same error in Launchdock last week.  The jobs package deprecated a particular syntax.

https://github.com/reactioncommerce/reaction/blob/Meteor-1.4.4.2/server/jobs/email.js#L13

This...
```js
Job.processJobs(Jobs, "sendEmail", {
```
Needs to be this...
```js
Jobs.processJobs("sendEmail", {
```

**Comment by zenweasel** [comment]
@jshimko Well, since you are so good at fixing that bug....:)

**Pull request merged**
