### PR TITLE
Additional navigation visibility options

### LINKED ISSUE #5146: Navigation editor needs more options for staging pre-release changes
## Issue Description

Navigation items cannot be pre-setup and staged for release. The navigation as a whole is either published or in draft-mode which doesn't allow for staging a subtree of items for release at a later date.

## Possible Solution

Add visibility options to the navigation tree node. This could range from `isVisible`, `isPublished`, `isShownInMenu` for either a hard "don't publish through the API", to a client-side check of whether or not to show something.

### PR DESCRIPTION
**Pull request by mikemurray**
Resolves #5146  
Impact: **minor**  
Type: **feature**

## Issue

Navigation items need some additional visibility options

## Solution

Add the following options
- `Show in storefront (isVisibile)` - show or hide from API / storefront etc
- `Admin access only (isPrivate)` - only show to admins in storefront, if `isVisibile: true`
- `Secondary nav only (isSecondary)` - show in the secondary nav, useful if you use the same nav for the main / sidebar, but want the sidebar to have some additional items.

## Breaking changes

- `navigationTreeById` now accepts an object containing params `{ language, navigationTreeId, shouldInlcudeSecondary }` instead of individual params.
- `draftItems` is admin only now so to not expose work-in-progress changes to the public

## Testing
1. Add navigations items to the navigation tree in the `Navigation` editor
1. Edit an item in the tree
1. Set `Show in storefront`, `Admin access only`, `Secondary nav only` options for various items
1. Be sure to "Save Changes" in the toolbar at the top to ensure all items get published
1. Ensure the following queries give you the items you expect

Keep in mind a few things for these queries.
- `items` gets filtered by `isVisible`, `isPrivate` automatically and by the `shouldShowSecondary` arg
- `draftItems` is admin only now and is not filtered by permissions

```graphql
{
  primaryShop {
    defaultNavigationTree(language: "en", shouldIncludeSecondary: true) {
      name
      items {
        isVisible
        isPrivate
        isSecondary
        navigationItem {
          data {
            content {
              value
            }
          }
        }
      }
      draftItems {
        isVisible
        isPrivate
        isSecondary
      }
    }
  }
}
```
---

Get the default navigation tree id
```graphql
{
  primaryShop {
    defaultNavigationTreeId
  }
```

Use the ID for this query
```graphql
{
  navigationTreeById(
    id: "<nav-tree-id>,
    language: "en",
    shouldIncludeSecondary: true
  ) {
    items {
        isVisible
        isPrivate
    	isSecondary
         navigationItem {
          data {
            content {
              value
            }
          }
        }
      items {
        isVisible
        isPrivate
        isSecondary
         navigationItem {
          data {
            content {
              value
            }
          }
        }
      }
    }
  }
}
```

### CODE REVIEW

**Comment by machikoyasuda** [comment]
LGTM:

Screen Shot 2019-05-01 at 4 37 05 PM
Screen Shot 2019-05-01 at 4 39 56 PM

Copy note: I was confused that checking `Hide from primary` shows a label that says `Secondary nav only`. I think the checkbox copy and the badge copy should mirror each other. For example:

- [ ] *Secondary nav only*: Hide from primary navigation
Prevent this item from showing up as a main navigation item. This item may still be visible in some navigation bars or sidebars.

**Comment by machikoyasuda** [comment]
Requesting Design review from @rymorgan

**Comment by rymorgan** [comment]
- @mikemurray I think @machikoyasuda makes a good point. I'd vote to match the modal to the badge. So both would say "Secondary nav only". 
- Also @machikoyasuda had an idea of color coding items that are "live" and not "live". I wonder if we showed anything that was admin only as a light yellow (as in a warning color?). LIke @yellow-100 (#fcf3dc)? Thoughts?

**Comment by mikemurray** [comment]
@rymorgan the modal does have padding at the bottom. It's too tall for the window so the content is scrolling. The current way the dialog is set up puts everything in the content region. I'd need to split it into header, content, footer, and only have the content scroll.

I'd like to revisit some of these things in another ticket if possible...
- Modal design
- Color coding (if necessary)
- Is Saving / some notifications. I can't tell when things are saved or not saved
- Preview maybe?

**Comment by mikemurray** [comment]
Here's the ticket for UI tweaks: https://github.com/reactioncommerce/reaction/issues/5163

**Comment by mikemurray** [comment]
@machikoyasuda 

- Updated checkbox to say "Secondary nav only"
- Made `isVisible`, `isPrivate`, `isSecondary` required fields in the SimpleSchema. Added defaults for the UI/API when the values are not defined. I think its best they're explicitly `true/false` and never `undefined` and left to interpretation.

**Comment by machikoyasuda** [comment]
LGTM

**Pull request merged**
