### PR TITLE
Integration 0.12 with flat-pages 0.1.5

### PR DESCRIPTION
**Pull request by ramusus**
This PR is example to show how to integrate reaction-flat-pages with 0.12 version. I created it for fast and easy integration and to show what is necessary to change in the core for successful integration with my package.

Features:
* Translations for package;
* FlatPagesWorkflow;
* "Add Page" link in right side-bar;
* "Flat Pages" link in the bottom of right side-bar for FlatPagesWorkflow;

### CODE REVIEW

**Comment by zenweasel** [comment]
@ramusus If we are going to move this info Reaction, we want to move it into the main repo or it needs to be a completely independent third-party package (i.e. no PR needed). If we move it into reaction proper, we need to get permission from the original author @kefirchik as well.

**Comment by ramusus** [comment]
I would like to have it in main repo and plugged the same way as `reaction-product-variant`. Let's ask permission of @kefirchik for this

**Comment by zenweasel** [comment]
I put in an issue on the original project, so we will give him a couple of days to get back to us.

**Comment by ramusus** [comment]
released version 1.4.5 with updates for the latest development branch
recorded short screencast with all main features:
screencast

**Comment by aaronjudd** [comment]
:+1: nice work @ramusus

**Comment by aaronjudd** [comment]
Closing this PR, same comment from the filtration PR:  still going to make an attempt to merge parts of this, but it will need some refactoring for the module structure, and we'll probably want some more refactoring as well for ideas we have for adding revision control.

**Pull request closed without merging**
