### PR TITLE
[issue #3355]

### PR DESCRIPTION
**Pull request by AshtonHarding**
This PR is intended to fix the issue mentioned in #3355 for firefox
Here is an image of my results: https://i.imgur.com/b6hCPGT.png

The reason the error was occurring is because Firefox doesn't have the global `window.event` available. I looked into alternatives for `window.event` and this deals with the problem.

I know it's minor, but I hope this helps. :)

### CODE REVIEW

**Comment by AshtonHarding** [comment]
I'll figure out why it's not passing the checks real quick.

**Comment by AshtonHarding** [comment]
Ok, it appears bitHound isn't a requirement to pass. However, over the next few days, when I have the time, I will be working on getting my fork to completely pass these checks.

**Comment by zenweasel** [comment]
The linting error looks to be related to the solution. Not sure if we maybe need to disable this check?

```
/Users/brenthoover/Projects/js/reaction/imports/plugins/included/product-variant/containers/productGridItemsContainer.js
  52:9  error  Read-only global 'event' should not be modified  no-native-reassign
```

**Comment by AshtonHarding** [comment]
The latest push has made the error stop occurring. (This is the first time I've been using ESLint, pretty neat that they use comments!)

**Comment by spencern** [comment]
@zenweasel @AshtonHarding I'm wary of reassigning the global event here. Should the event be coming in the function args here? Are we sure that the global event is what we're needing to reassign?

@mikemurray any thoughts on this?

**Comment by zenweasel** [comment]
Taking the solution in #3429 over this since we don't need to overwrite the global event.

**Pull request closed without merging**
