### PR TITLE
(refactor) Remove shipping-shippo plugin

### PR DESCRIPTION
**Pull request by Akarshit**
Partially resolves: #4308
Impact: **breaking**  
Type: **refactor**

## Issue
This plugin is included by default even though the vast majority of people will not be using it.

## Solution
Move this plugin to the ["community" namespace](https://github.com/reaction-contrib/meteor-shipping-shippo).

## Breaking changes
To continue to use this plugin after this change you will need to:
1. Clone [this repo](https://github.com/reaction-contrib/meteor-taxes-taxcloud) into `<reaction root>/imports/plugins/custom/`
1. `meteor npm install` in this repo

### App works w/o plugin
1. `rm -rf node_modules`
1. `meteor npm install`
1. Start app
1. Ensure everything works as normal

### Community app works 
1. `reaction reset -y`
1. Start app and ensure Shippo is not available.
1. Follow above instructions for installing.
1. Ensure Shippo plugin works as before.

### CODE REVIEW

**Comment by Akarshit** [comment]
There are no docs for `Shippo`, so no changes required to `reaction-docs`.

**Comment by zenweasel** [comment]
@Akarshit Do you need to assign a reviewer here?

**Comment by zenweasel** [comment]
@Akarshit Got conflicts and failing tests here

**Comment by Akarshit** [comment]
@zenweasel I have updated the PR and the tests are passing now.
Also I have opened a PR @reaction-contib/meteor-shipping-shippo#1 for migrating the changes that aldeed made here to that code.

**Pull request merged**
