### PR TITLE
chore: fix all `react/no-deprecated` and `react/prop-type` eslint warnings

### LINKED ISSUE #5247: Remove old router logic causing conflict with newer route registration methods
## Issue Description

The old Reaction Router and the new Operator UI routes are fighting with each other. The old router has event listing for routes but reports a `not-found` route for all operator routes because they're not loaded into its data store. There are also issues with the auth routes as they are registered with the old router because `registerOperatorRoute` is not for public routes.

While they both use the same React Router instance, the old router is trying to behave like a FlowRouter/React Router hybrid while the operator routes are React Router routes with very little management logic behind them.

## Steps to Reproduce

More difficult to reproduce now that we've patched in a quick fix to ensure the title bar doesn't say `Not Found` for every operator route as of this PR https://github.com/reactioncommerce/reaction/pull/5245.

## Possible Solution

- Update the `imports/plugins/core/router` plugin to remove a lot of the old route creation and handling logic. This code pulls routes from the database and renders them as React Router routes.
- Move the new router registration logic to that package. Seems like a better home for it.
- Refactor all imports for `registerOperatorRoute` to its new home
- Create a method, or rename/deprecate `registerOperatorRoute` for `registerRoute`. `registerOperatorRoute` could still exist, but maybe is an alias for `registerRoute` for operator routes only.
- `registerRoute` may be used to register routes for both public and admin access.
- Update routes that exist in plugin registration to use `registerRoute`. This will most likely be the public auth routes.
- Remove routes that don't exist anymore from the registry
- Ensure all routes have page title metadata, and that React Helmet is being populated with the correct information

### PR DESCRIPTION
**Pull request by kieckhafer**
Resolves #5247 & #5271    
Impact: **minor**  
Type: **chore**

## Issue
We currently have many `react/no-deprecated` and `react/prop-type` eslint warnings.

## Solution
Fix (or disable) these warnings, and then update our `eslint` rules to make `react/no-deprecated` and `react/prop-type` an `error` so new violations are not introduced.

I have update the components to use the `UNSAFE_` version fo deprecated react life cycle methods, as these components will be updated to be functional components in the future.

Updated rules: https://github.com/reactioncommerce/reaction-eslint-config/pull/15

## Breaking changes
None.

## Testing
1. run eslint
1. see there are no longer any `react/no-deprecated` and `react/prop-type` warnings (and no errors)

### CODE REVIEW

**Comment by kieckhafer** [comment]
@machikoyasuda not sure what the deal is with the DCO issue - it involves Maria's commits that aren't even in this branch. I've filed a ticket with them to see if they know what's going on: https://github.com/reactioncommerce/reaction-eslint-config/pull/15

**Comment by machikoyasuda** [comment]
@kieckhafer You have 2 commits incorrectly signed off. To fix, head to your local branch and run:

`git rebase HEAD~72 --signoff`

Now your commits will have your sign off. Next run

`git push --force-with-lease origin chore-kieckhafer-esling-reactNoDeprecated`

**Comment by kieckhafer** [comment]
@machikoyasuda but those aren't my commits, and they aren't in this branch at all. They are commits from Maria... somewhere in the app. I've only made 3 commits to this branch, all signed-off.

**Comment by kieckhafer** [comment]
Fixed... somehow?

**Pull request merged**
