### PR TITLE
add custom palyment method

### PR DESCRIPTION
**Pull request by bongster**
* add imports/node-app/plugins/payments-vcoin
* add imports/plugins/included/payments-vcoin
* register plugin imports/node-app/registerPlugins.js

Resolves #issueNumber  
Impact: **breaking|critical|major|minor**  
Type: **feature|bugfix|performance|test|style|refactor|docs|chore**

## Issue
Description of the issue this PR is solving, why it's happening, and how to reproduce it. This may differ from the original ticket as you now have more information at your disposal.

## Solution
Summarize your solution to the problem. Please include short descriptions of any solutions you tested before arriving at your final solution. This will help reviewers know why you decided to solve this problem in this particular way and will speed up the review process.

If you're solving a UIX related issue, please attach screen-caps or gifs showing how your solution differs from the issue.

## Breaking changes
If you have a breaking changes, list them here, otherwise list none.

Examples of breaking changes include changing file names, moving files, deleting files, renaming functions or exports, or changes to code which might cause previous versions of Reaction or third-party code not to work as expected.

Note any work that you did to mitigate the effect of any breaking changes such as creating migrations, deprecation warnings, etc.

## Testing
1. List the steps needed for testing your change in this section.
2. Assume that testers already know how to start the app, and do the basic setup tasks.
3. Be detailed enough that someone can work through it without being too granular

More detail for what each of these sections should include are available in our [Contributing Docs](https://docs.reactioncommerce.com/reaction-docs/master/contributing-to-reaction)

### CODE REVIEW

**Comment by HarisSpahijaPon** [comment]
Could you clean up the PR a bit, I am not quite sure what this is for? Try to fill out the template first so it is clear to the reviewers what you are trying to accomplish

**Comment by loan-laux** [comment]
@HarisSpahijaPon, I'm pretty sure that @bongster meant to merge this on his own repo. Happens often here. @bongster let us know if that's the case.

**Comment by bongster** [comment]
@loan-laux @HarisSpahijaPon i'm so sorry. i got a make a mistake. i wonder testing reaction feature in my local repository and when i make a pull request in my repository I'm missing check my base repository

**Comment by spencern** [comment]
Not a problem @bongster 
This seems like an interesting plugin - once you get it working are you considering releasing it on npm?

**Pull request closed without merging**
