### PR TITLE
feat: prerelease

### LINKED ISSUE #6746: Prerelease for packages
To unblock people from trying packages that have been waiting for release.

Approach:
Using [changeset prerelease](https://github.com/changesets/changesets/blob/main/docs/prereleases.md), create version PR on a prerelease branch. When we merge that PR, it will release packages under @next on npm.

### PR DESCRIPTION
**Pull request by vanpho93**
Signed-off-by: vanpho93 <vanpho02@gmail.com>

Resolves #6746
Impact: **major**
Type: **feature**

## Issue

To unblock people from trying packages that have been waiting for release.

## Solution

Using [changeset prerelease](https://github.com/changesets/changesets/blob/main/docs/prereleases.md), create version PR on a prerelease branch. When we merge that PR, it will release packages under https://github.com/next on npm.

### CODE REVIEW

**Comment by brent-hoover** [comment]
Concerned about this `bump up packages versions as `1.0.0-next.{number}`. Is that going to be confusing if a plugin is already at 2.x.x?

**Comment by vanpho93** [comment]
> Concerned about this `bump up packages versions as `1.0.0-next.{number}`. Is that going to be confusing if a plugin is already at 2.x.x?

@zenweasel If it's already 2.x.x and we have a major upgrade, the package version will be `3.0.0-next.{number}`

**Review by brent-hoover — APPROVED** [review]
This looks good to me but I would like if @tedraykov could take a look at it.

**Review by aldeed — COMMENTED** [review]
Overall approach looks good to me

**Review by tedraykov — APPROVED** [review]
The code seems good. I reproduced the prerelease workflow on a fork and seems to work as expected. The only concern is if we would be able to publish to the @reactioncommerce npmjs org from GitHub action, rather than from a Circle CI as in the normal releases as we don't have the API keys configured in GitHub.

**Pull request merged**
