### PR TITLE
(fix): Determine denormalized product inventory status during Shopify import

### PR DESCRIPTION
**Pull request by spencern**
Fixes an unreported issue where denormalized product inventory status was not set during import of products from Shopify.

This PR resolves this by setting `isSoldOut`, `isLowQuantity`, and `isBackorder` flags correctly on the top level product during import.

### CODE REVIEW

**Comment by impactmass** [comment]
Looks good generally, but I have some questions:
- Looks like there's no equivalent `isLowQuantity` value from the Shopify data?
- How does this change affect anyone that already used the current version to import products?

**Comment by impactmass** [comment]
@spencern looks like you missed the comment above

**Comment by spencern** [comment]
arg. I thought I responded to this already, but probably have a draft mode somewhere.

`isLowQuantity` does not have an equivalent on Shopify, so we just set it to false.

Re: this change affecting anyone that already used the current version to import products, that's a great question. I'm pretty sure that top-level field gets updated every time inventory gets changed, but it might be worth including a migration here that loops through all products and updates them anyway?

**Comment by impactmass** [comment]
I think if we can confirm that the top-level field gets updated every time inventory gets changed, this should be good to approve then.

**Comment by spencern** [comment]
@impactmass Those do get updated as part of this `denormalize` function that gets called when variants are updated. See `catalog.js` https://github.com/reactioncommerce/reaction/blob/master/server/methods/catalog.js#L188

It's then called on L564 by updateVariant, and on L965 by updateProductField.

**Comment by spencern** [comment]
I've added one more update in here to fix the way variant images are imported. To this point only the first image imported was added to the grid via `toGrid: 1` but after experimenting with how Reaction assigns product media to the grid when creating a product and variants, I've updated the Shopify importer to now add the first image for each variant to the grid as well. This should resolve the situation we've seen in #3368 where grid item layouts do not show additional product media that has been imported from Shopify.

It will not affect existing images from Shopify that have been imported.

I'm not certain if we want to add a migration here, as it's possible that people have built their apps to account for the way that the media was imported originally, but a migration could be added to set the first image of each variant to have `toGrid: 1`

I lean towards this being a fix and not adding a migration, but could understand an argument either way. @impactmass what do you think?

**Comment by spencern** [comment]
@impactmass ready for another review here.

**Comment by impactmass** [comment]
Yes, doing a migration in this case can cause a break in the way someone else already built on earlier imports. So, I tend towards the way it's setup here.

**Pull request merged**
