### PR TITLE
refactor: cart token param name consistent to `cartToken`

### LINKED ISSUE #4642: Update SetEmailOnAnonymousCartInput to use cartToken instead of token param name
### Summary
`SetEmailOnAnonymousCartInput`, `RemoveCartItemsInput` and perhaps others  input types, use a param named `token` to required the request to provide an anonymous cart token, other input types use `cartToken` such as `SelectFulfillmentOptionForGroupInput`.  This inconsistency leads to unnecessary client code. Lets add consistency by using `cartToken` as the param name for all inputs.

### PR DESCRIPTION
**Pull request by trojanh**
Resolves #4642   
Impact: **minor**  
Type: **refactor**

## Issue
Cart tokens currently have three names i.e `token`, `cartToken` and `anonymousAccessToken`, need to rename all of them to same consistent name.

## Solution
Update `token` or `anonymousAccessToken` params name to `cartToken` to make it consistent

## Breaking Changes
Clients (such as those based on the example storefront codebase) that call cart-related mutations will need to pass `cartToken` param instead of `token` or `anonymousAccessToken`

## Testing
1. Test the following mutations:
`updateCartItemsQuantity`
`setEmailOnAnonymousCart`
`removeCartItems`
`reconcileCarts`
`addCartItems`

2. Test following query
`anonymousCartByCartId`

### CODE REVIEW

**Comment by aldeed** [comment]
@trojanh These changes look good but I don't want to merge this until the `release-v3.0.0` branch of [example-storefront](https://github.com/reactioncommerce/example-storefront) also has a PR submitted updating the mutations and state logic there. (The purpose of this issue was to simplify some things in the example storefront.) If you're not familiar with storefront codebase, @willopez may be able to help or do the storefront PR.

**Comment by trojanh** [comment]
Thanks, @aldeed I would like do the storefront changes as well. I will definitely take @willopez 's help if needed.

**Comment by trojanh** [comment]
I have made the changes for front-end,
https://github.com/reactioncommerce/example-storefront/pull/616

**Comment by willopez** [comment]
I reviewed and merged the related PR on the storefront https://github.com/reactioncommerce/example-storefront/pull/616 this one is good to go too. Thanks again @trojanh

**Pull request merged**
