### PR TITLE
Fix Payflow capture

### LINKED ISSUE #1146: Capture not working for Payflow Pro
For bugs, please fill out the three following sections completely

### Expected behavior
When you click on the "Capture" button after approving an order the dashboard totals should change to reflect the captured amount and the refund button should appear.

### Actual Behavior
Errors in the server console and the "Approve" button reappears.

### Steps to Reproduce the Behavior
1. Place an order using Payflow Pro
2. Go to the Admin panel
3. Select the order and view details
4. Click "Approve" and then "Capture". 
5. Observe the server logs.

### PR DESCRIPTION
**Pull request by zenweasel**
This fixes #1146 
However, currently you can only use a credit card you create [here](https://www.paypal-knowledge.com/infocenter/index?page=content&widgetview=true&id=FAQ1413&viewlocale=en_US&direct=en) using your test account.

I have created one so if someone at RC needs one just PM me (these are attached to our account so I can't make it public, I think)

This is still pending the status of https://github.com/paypal/PayPal-node-SDK/issues/168 since you are supposed to be able to test it with any card that passes MOD10

### CODE REVIEW

**Comment by aaronjudd** [comment]
👍  approved. works with special card, as noted in paypal issue.

**Comment by aaronjudd** [comment]
Still have an issue on refunds though, maybe a separate issue? ```Exception in delivering result of invoking 'payflowpro/refund/list': Error: Match error: Match error: Created must be a number in field [0]
    at exports.check (packages/check/match.js:34:1)
    at server/methods/core/orders.js:705:9```

**Comment by zenweasel** [comment]
@aaronjudd Retesting now I can't replicate the match error. Can you give me more details?

**Comment by kieckhafer** [comment]
👍  approved, was able to refund my order with no errors, looks good

**Pull request merged**
