### PR TITLE
Add validation for required fields on PDP

### PR DESCRIPTION
**Pull request by michael-alade**
*Resolves*
#2225 

*Testing*
- Login as admin
- Create a product
- Add a variant option.
- Fill all fields apart from product title, variant details label and variant options label.
- Click publish
- A toast message should show what fields are required.
- Now fill in all field required, then click publish
- The changes should be successfully published.

### CODE REVIEW

**Comment by zenweasel** [comment]
Well, this is not great. You still get "Label is required" whether you didn't enter an option of a variant title and the way "Untitled Option" shows up there is also not great. At it looks like if there are multiple errors it only shows one.

But we we probably need to always bubble up these errors from SimpleSchema so I guess this is an improvement. But we really need to do #2276

**Comment by rymorgan** [comment]
Jumping in on this too. I think there needs to be some indication of what fields are required. See example. 

validation

**Comment by zenweasel** [comment]
@rymorgan Yeah, so we are waiting for design on #2274 and we can revisit this. Should I assign that to you? Not really sure what the best way to do that is.

**Comment by rymorgan** [comment]
Yea, add it to the design project, which I think you have or I did. I'll pull it into view so it doesn't get lost.

**Pull request merged**
